// Generated by scripts/i18n_build.mjs. Do not edit by hand.
//
// Part of the generated src/ui/i18n.resolved.generated/ directory: one dense
// locale slice per file (each `: EnTranslations` = typeof en, so tsc red-fails a
// missing or renamed key), a back-compat barrel (index.ts) that re-exports every
// slice and assembles the runtime `translations` map, per-locale lazy loaders
// (loaders.ts), and the pending set (pending.ts). Regenerate with
// `npm run i18n:build` (also wired into `npm run build` and `pretest`).
// Reproducibility is checked by tests/i18n_resolved_equivalence.test.ts.

export const pending: Record<string, readonly string[]> = {
  "es": [
    "download.androidCta"
  ],
  "es_ES": [
    "download.androidCta"
  ],
  "fr_FR": [
    "download.androidCta"
  ],
  "fr_CA": [
    "download.androidCta"
  ],
  "en_CA": [],
  "it_IT": [
    "download.androidCta"
  ],
  "de_DE": [
    "download.androidCta"
  ],
  "zh_CN": [
    "entities.abilities.hamstring_bite.description",
    "entities.abilities.lunge.description",
    "guide.classPage.formsWolfEngage",
    "guide.interfacePage.framesGovernedTalkingHead",
    "guide.settingsPage.keybindsWheelBody",
    "hudChrome.archetypePair.alchemy+cooking",
    "hudChrome.archetypePair.armorcrafting+engineering",
    "hudChrome.archetypePair.cooking+leatherworking",
    "hudChrome.archetypePair.enchanting+jewelcrafting",
    "hudChrome.archetypePair.engineering+alchemy",
    "hudChrome.archetypePair.inscription+enchanting",
    "hudChrome.archetypePair.jewelcrafting+weaponcrafting",
    "hudChrome.archetypePair.leatherworking+tailoring",
    "hudChrome.archetypePair.tailoring+inscription",
    "hudChrome.archetypePair.weaponcrafting+armorcrafting",
    "hudChrome.auraEffect.bruinRushWindow",
    "hudChrome.auraOverlay.soundHint",
    "hudChrome.auraOverlay.watchlistHint",
    "hudChrome.deeds.accountScopeHint",
    "hudChrome.keybinds.wheelHeldRefused",
    "hudChrome.keybinds.wheelHint",
    "hudChrome.marketWindow.mixedListingsFooter",
    "hudChrome.materialHint.fineFarmGrade",
    "hudChrome.options.confirmVendorSellMinQualityNote",
    "hudChrome.tutorialGreeting.eastbrookGuidanceNote",
    "itemUi.market.sweepConfirmBody",
    "itemUi.market.sweepNote"
  ],
  "zh_TW": [],
  "ko_KR": [],
  "ja_JP": [],
  "pt_BR": [
    "download.androidCta"
  ],
  "ru_RU": [],
  "cs_CZ": [
    "download.androidCta"
  ],
  "nl_NL": [
    "download.androidCta"
  ],
  "pl_PL": [
    "download.androidCta"
  ],
  "id_ID": [
    "download.androidCta"
  ],
  "tr_TR": [
    "download.androidCta"
  ],
  "sv_SE": [
    "download.androidCta"
  ],
  "vi_VN": [
    "download.androidCta"
  ],
  "da_DK": [
    "download.androidCta"
  ]
};
