// NPC voice-line playback. Plays the pre-rendered ElevenLabs clips under
// public/audio/voice (generated by scripts/gen_npc_lines.mjs) via a single
// HTMLAudioElement — the same plain-`Audio` approach as the main-theme player in
// main.ts, so there's no AudioContext user-gesture gate to manage here.
//
// Lookup is by line key (`greeting__<npcId>`, `quest__<questId>__offer`,
// `quest__<questId>__complete`) against the generated manifest; unknown keys and
// missing files are silent no-ops, so the game runs fine before any audio exists.

import { VOICE_LINES } from './voice_manifest.generated';
import { VOICE_LINES_ZH } from './voice_manifest.zh_CN.generated';
import { getLanguage } from '../ui/i18n';

// Voices sit slightly under their slider value so NPC dialogue doesn't overpower
// the SFX/ambience mix.
const VOICE_BASE_GAIN = 0.9;

// Distance-attenuation curve for a talking NPC (world yards). At or within
// VOICE_FULL_DIST the line plays at full volume; past it the volume ramps down
// linearly to silence at VOICE_SILENT_DIST, so a dialogue you walk away from
// trails off as if heard from farther away. You open a dialog within
// INTERACT_RANGE (5), so FULL sits just past it and never dips the line on open.
export const VOICE_FULL_DIST = 6;
export const VOICE_SILENT_DIST = 22;
export const IGNIVAR_ROOM_WELCOME_VOICE_KEY =
  'yell__the_seal_hears_you_little_embers_step_closer_and_feed_the_la';

export function voiceDistanceGain(
  dist: number,
  full = VOICE_FULL_DIST,
  silent = VOICE_SILENT_DIST,
): number {
  if (!(dist > full)) return 1; // also catches NaN / negative: play at full
  if (dist >= silent) return 0;
  return (silent - dist) / (silent - full);
}

interface QueuedVoiceLine {
  lineKey: string;
  opts?: { gain?: number };
}

export class GameVoice {
  private el: HTMLAudioElement | null = null;
  private vol = 0.9; // 0..1, from the settings slider
  private enabled = true;
  private playGain = 1; // per-line gain passed to play()
  private distanceGain = 1; // live distance attenuation (1 = at the NPC)
  private currentKey: string | null = null;
  private queued: QueuedVoiceLine | null = null;

  private applyVolume(): void {
    if (this.el)
      this.el.volume = Math.min(1, this.vol * VOICE_BASE_GAIN * this.playGain * this.distanceGain);
  }

  /** Set voice volume (0..1). Safe any time. */
  setVolume(v: number): void {
    this.vol = Math.min(1, Math.max(0, v));
    this.applyVolume();
  }

  /** Live distance attenuation (0 = out of earshot, 1 = at the NPC) for the current line. */
  setDistanceGain(g: number): void {
    this.distanceGain = Math.min(1, Math.max(0, g));
    this.applyVolume();
  }

  /** True while a line is actively sounding (used to stop driving the fade once it ends). */
  isPlaying(): boolean {
    return !!this.el && !this.el.paused && !this.el.ended;
  }

  /** Enable/disable voice-over. Disabling also stops any line in progress. */
  setEnabled(on: boolean): void {
    this.enabled = on;
    if (!on) this.stop();
  }

  /** Whether semantic VO can currently sound, used to coordinate SFX vocals. */
  isAudible(): boolean {
    return this.enabled && this.vol > 0;
  }

  /** Stop and reset the current line (so a new NPC interrupts the last one). */
  stop(): void {
    this.queued = null;
    this.stopCurrent();
  }

  private stopCurrent(): void {
    if (this.el) {
      this.el.onended = null;
      this.el.pause();
      this.el.currentTime = 0;
    }
    this.currentKey = null;
  }

  private advanceQueue(finishedKey: string): void {
    if (this.currentKey !== finishedKey) return;
    this.currentKey = null;
    const next = this.queued;
    this.queued = null;
    if (next) this.play(next.lineKey, next.opts);
  }

  /** Play the clip for a line key, if one exists and voice-over is enabled. */
  play(lineKey: string, opts?: { gain?: number }): void {
    if (!this.enabled) return;
    const lang = getLanguage();
    const isZh = lang === 'zh_CN' || lang === 'zh_TW';
    const src = (isZh && (VOICE_LINES_ZH as Record<string, string>)[lineKey]) || VOICE_LINES[lineKey];
    if (!src) return;
    // The one-time room introduction is longer than the walk to Ignivar's
    // aggro edge. Preserve it for this player and queue the latest encounter
    // line locally instead of delaying simulation or the rest of the raid.
    if (this.currentKey === IGNIVAR_ROOM_WELCOME_VOICE_KEY && this.isPlaying()) {
      this.queued = { lineKey, opts };
      return;
    }
    this.queued = null;
    this.stopCurrent();
    if (!this.el) this.el = new Audio();
    this.el.src = src;
    this.currentKey = lineKey;
    this.el.onended = () => this.advanceQueue(lineKey);
    this.playGain = opts?.gain ?? 1;
    this.distanceGain = 1; // a fresh line starts at full: you just clicked the NPC, you are close
    this.applyVolume();
    // Autoplay restrictions / a missing file reject the promise — ignore, the
    // dialogue text is the source of truth and audio is an enhancement.
    void this.el.play().catch(() => this.advanceQueue(lineKey));
  }
}

export const voice = new GameVoice();
