// Generated by scripts/gen_chinese_voices.py. Do not edit by hand.
// Maps an NPC voice-line key to its localized Chinese audio path.
export const VOICE_LINES_ZH: Record<string, string> = 
{
  "greeting__alchemist_verane": "/audio/voice_zh/alchemist_verane/greeting__alchemist_verane.mp3?v=c13032dd535f"
} as const;
