// The client mirror's placeholder entity: every field an Entity carries, at
// its pre-first-snapshot default. ClientWorld hands one out when a read races
// the first snapshot (the self read before join completes, a wire row for an
// id the interest set has not delivered yet); the next snapshot overwrites
// every live field. Pure data, no ClientWorld state, which is why it lives as
// a sibling module rather than in online.ts. Defaults must stay in lockstep
// with the Entity shape in src/sim/types.ts: tsc enforces presence, and the
// value conventions (nulls, zeros, the procReadyAt cast) are the mirror's own.
import type { Entity } from '../sim/types';

export function blankEntity(id: number): Entity {
  return {
    id,
    kind: 'mob',
    templateId: '',
    name: '',
    level: 1,
    mendTimer: 0,
    wardTimer: 0,
    channelTimer: 0,
    channelRamp: 0,
    rallyTimer: 0,
    warcryTimer: 0,
    petPath: [],
    petPathCooldown: 0,
    petOwnerHpBonus: 0,
    castPushbackReduction: 0,
    knockbackResistance: 0,
    ccDurationReduction: 0,
    pos: { x: 0, y: 0, z: 0 },
    prevPos: { x: 0, y: 0, z: 0 },
    facing: 0,
    prevFacing: 0,
    vx: 0,
    vz: 0,
    vy: 0,
    onGround: true,
    jumping: false,
    fallStartY: 0,
    swimStroke: 0,
    swimDiving: false,
    fatigueTicks: 0,
    breathUsedTicks: 0,
    drownTicks: 0,
    hp: 1,
    maxHp: 1,
    resource: 0,
    maxResource: 0,
    resourceType: null,
    overheadEmoteId: null,
    overheadEmoteUntil: 0,
    overheadEmoteSeq: 0,
    stats: {
      str: 0,
      agi: 0,
      sta: 0,
      int: 0,
      spi: 0,
      armor: 0,
      pvpOffense: 0,
      pvpDefense: 0,
    },
    weapon: { min: 1, max: 2, speed: 2 },
    offhandWeapon: null,
    attackPower: 0,
    rangedPower: 0,
    spellPower: 0,
    healPower: 0,
    meleeHaste: 0,
    rangedHaste: 0,
    spellHaste: 0,
    setProcs: [],
    procReadyAt: undefined as unknown as Record<string, number>,
    critChance: 0.05,
    sharedCritBonus: 0,
    critRating: 0,
    hasteRating: 0,
    hitRating: 0,
    hitBonus: 0,
    critDmgSpellBonus: 0,
    critDmgPhysBonus: 0,
    critDmgHealBonus: 0,
    dodgeChance: 0.05,
    blockChance: 0,
    blockValue: 0,
    moveSpeed: 7,
    hostile: false,
    targetId: null,
    autoAttack: false,
    swingTimer: 0,
    offhandSwingTimer: 0,
    dualWielding: false,
    // Server-side combat state: the mirror never computes damage, so the
    // authoritative titansGrip never needs to cross the wire.
    titansGrip: false,
    inCombat: false,
    combatTimer: 99,
    auras: [],
    stealthed: false,
    ccDr: new Map(),
    castingAbility: null,
    castRemaining: 0,
    castTotal: 0,
    castTargetId: null,
    castAim: null,
    gatherCastNodeId: '',
    gatherCastToolRarity: '',
    gatherCastEffectConfirmed: false,
    craftCastRecipeId: '',
    craftCastCommission: false,
    craftCastBatchRemaining: 0,
    craftCastBatchTotal: 0,
    enchantCastItemId: '',
    enchantCastBagSlot: 0,
    enchantCastEnchantId: '',
    enchantCastEquipSlot: '',
    enchantCastConfirmReplace: false,
    enchantCastTargetPin: '',
    toolRechargeCastProfessionId: '',
    fishBiteAtTick: 0,
    fishReelDeadlineTick: 0,
    fishCastZoneId: '',
    channeling: false,
    channelTickTimer: 0,
    channelTickEvery: 0,
    channelTicksLeft: 0,
    gcdRemaining: 0,
    cooldowns: new Map(),
    queuedOnSwing: null,
    queuedCastAbility: null,
    queuedCastAim: null,
    queuedCastTargetId: null,
    fiveSecondRule: 99,
    comboPoints: 0,
    comboUntil: -1,
    overpowerUntil: -1,
    potionCooldownUntil: -1,
    potionCdRemaining: 0,
    firebottleCdRemaining: 0,
    savedMana: 0,
    chargeTargetId: null,
    chargeTimeLeft: 0,
    chargePath: [],
    followTargetId: null,
    sitting: false,
    riftSliding: false,
    afk: false,
    weaponStowed: false,
    helmHidden: false,
    modularAppearance: null,
    eating: null,
    drinking: null,
    aiState: 'idle',
    tappedById: null,
    pulseTimer: 0,
    stompTimer: 0,
    bigCastTimer: 0,
    deathZoneCastTimer: 0,
    deathZoneStrikeTimer: 0,
    infernoTimer: 0,
    infernoRemaining: 0,
    infernoPulsesFired: 0,
    infernoGatesFired: 0,
    yelledEngage: false,
    stoneskinTimer: 0,
    terrifyTimer: 0,
    aoeSlowTimer: 0,
    loudYellTimer: 0,
    loudYellIndex: 0,
    detonateTimer: Infinity,
    firedSummons: 0,
    summonedIds: [],
    summonedAdd: false,
    enraged: false,
    healedThisPull: false,
    threat: new Map(),
    bossDamagers: new Set(),
    forcedTargetId: null,
    forcedTargetTimer: 0,
    ownerId: null,
    petMode: 'defensive',
    petTauntTimer: 0,
    petSkillTimer: 0,
    petAutoTaunt: false,
    petAutoWaterJet: false,
    petAutoSkill: false,
    petManualTauntPending: false,
    spawnPos: { x: 0, y: 0, z: 0 },
    leashAnchor: null,
    evadeStall: 0,
    chaseStall: 0,
    evadeEpoch: 0,
    chainPullInbound: false,
    // The instance combat hold's pin clock (instances/instance_combat_hold.ts):
    // present from birth on the mirror too, so both hosts build one entity shape.
    evadeInPlace: undefined,
    fleeTimer: 0,
    fleeReturnTimer: 0,
    hasFled: false,
    wanderTarget: null,
    wanderTimer: 0,
    aggroTargetId: null,
    respawnTimer: 0,
    corpseTimer: 0,
    lootFfaTimer: Infinity,
    harvestClaimedBy: null,
    lootable: false,
    loot: null,
    xpValue: 0,
    questIds: [],
    vendorItems: [],
    objectItemId: null,
    dungeonId: null,
    dead: false,
    ghost: false,
    corpsePos: null,
    corpseInstanceId: null,
    scale: 1,
    color: 0xffffff,
    skinCatalog: 'class',
    skin: 0,
    mountKey: '',
    mountCastRemaining: 0,
    mountCastKey: '',
    mainhandItemId: null,
    offhandItemId: null,
    weaponSkinLoadout: {},
    weaponSkinId: null,
    mountSkinId: null,
    equippedItems: {},
    equippedInstances: {},
    guild: '',
    pledgeGuild: '',
    guildTier: 0,
    title: null,
    border: null,
  };
}
