#!/usr/bin/env bash
# Regenerates docs/rallycart-mount/reference/ from the unmerged mount branches.
#
# The Rallycart borrows from five other mounts. None of them are merged, so a
# cold reader cannot follow a reference without checking out four more branches.
# This script materializes the borrowed code inside this worktree, read only,
# with a provenance record of exactly which commit each file came from.
#
# Rerun it any time one of the source branches moves:
#   bash docs/rallycart-mount/refresh_reference.sh
#
# The output directory ignores itself (reference/.gitignore holds '*'), so none
# of the copied code can be committed by accident, and biome skips it because
# biome.json sets vcs.useIgnoreFile.

set -euo pipefail

cd "$(dirname "$0")/../.."
OUT=docs/rallycart-mount/reference

rm -rf "$OUT"
mkdir -p "$OUT"
printf '*\n' >"$OUT/.gitignore"

# Every file a mount has to be registered in. Doubles as the wiring checklist.
WIRING_FILES=(
  src/render/characters/manifest.ts
  src/render/mount_visuals.ts
  src/render/mount_visual_lifecycle.ts
  src/sim/content/mounts.ts
  src/sim/content/items.ts
  src/sim/content/reliquary.ts
  src/sim/content/deeds.ts
  src/game/sfx.ts
  scripts/sfx/sfx_prompts.mjs
  scripts/mounts_shot.mjs
)

# copy_tree BRANCH DEST PATHSPEC...
copy_tree() {
  local branch=$1 dest=$2
  shift 2
  local f
  git ls-tree -r --name-only "$branch" -- "$@" | while read -r f; do
    mkdir -p "$dest/$(dirname "$f")"
    git show "$branch:$f" >"$dest/$f"
  done
}

# excerpts BRANCH DEST KEY
# Pulls the mount's records out of the shared registries. Copying those files
# whole would be 3200 lines of unrelated content per mount.
excerpts() {
  local branch=$1 dest=$2 key=$3
  local out="$dest/WIRING_EXCERPTS.md" f body
  {
    echo "# Wiring excerpts: \`$key\`"
    echo
    echo "From \`$branch\` at \`$(git rev-parse --short "$branch")\`."
    echo "Grep context around \`$key\` in each shared registry. Line numbers are"
    echo "that branch's, not this worktree's."
    echo
  } >"$out"
  for f in "${WIRING_FILES[@]}"; do
    if ! git cat-file -e "$branch:$f" 2>/dev/null; then
      continue
    fi
    body=$(git show "$branch:$f" | grep -n -C 6 -- "$key" || true)
    if [ -z "$body" ]; then
      continue
    fi
    {
      echo "## \`$f\`"
      echo
      echo '```'
      echo "$body"
      echo '```'
      echo
    } >>"$out"
  done
}

# mount SLUG BRANCH KEY PATHSPEC...
mount_ref() {
  local slug=$1 branch=$2 key=$3
  shift 3
  local dest="$OUT/$slug"
  if ! git rev-parse --verify --quiet "$branch" >/dev/null; then
    echo "skip $slug: branch $branch not found"
    return
  fi
  mkdir -p "$dest"
  echo "$slug <- $branch @ $(git rev-parse "$branch")" >>"$OUT/PROVENANCE.txt"
  if [ "$#" -gt 0 ]; then
    copy_tree "$branch" "$dest" "$@"
  fi
  excerpts "$branch" "$dest" "$key"
  echo "wrote $slug"
}

{
  echo "Generated by docs/rallycart-mount/refresh_reference.sh"
  echo "Host worktree: $(pwd)"
  echo "Host branch:   $(git rev-parse --abbrev-ref HEAD) @ $(git rev-parse HEAD)"
  echo
} >"$OUT/PROVENANCE.txt"

cat >"$OUT/README.md" <<'EOF'
# Borrowed code, copied in

GENERATED. Do not edit by hand and do not commit. Rebuild with
`bash docs/rallycart-mount/refresh_reference.sh`.

The Rallycart RXT borrows from five other mounts, none of which are merged.
Each one lives on its own feature branch, so this directory carries a read only
copy of the borrowed code at its original repo-relative path. `PROVENANCE.txt`
records the exact commit each copy came from.

Per mount, `WIRING_EXCERPTS.md` holds that branch's records grepped out of
every shared registry a mount has to be registered in. Those registries run to
thousands of lines each, so only the matching context is kept. The file list in
that document is also the wiring checklist for finishing this mount.

This directory ignores itself through its own `.gitignore`, which is why biome
skips it as well.
EOF

# 1. Terrorspark Groundshaker (the tank). Proof a vehicle ships with skins: 0,
#    and the source of the seat/seatFwd spec shape.
mount_ref terrorspark-groundshaker-tank feature/tank-mount-sfx terrorspark_groundshaker \
  scripts/assets/terrorspark_groundshaker \
  scripts/assets/specs/terrorspark_groundshaker.json \
  scripts/gen_terrorspark_groundshaker_sfx.mjs \
  tests/terrorspark_groundshaker_asset.test.ts \
  tests/terrorspark_groundshaker_surface_maps.test.ts \
  tests/terrorspark_groundshaker_surface_shading.test.ts

# 2. Goblin Rocket Sled. This branch is BASED on it, so its code is already
#    live in src/. Copied anyway so the reference set is complete and so a
#    future rebase cannot silently remove what the handoff points at.
mount_ref goblin-rocket-sled feature/goblin-rocket-sled goblin_rocket_sled \
  src/render/goblin_rocket_sled_fx.ts \
  src/render/goblin_rocket_sled_fx_core.ts \
  src/game/mount_engine_state.ts \
  tests/goblin_rocket_sled_fx_core.test.ts \
  tests/mount_engine_state.test.ts \
  scripts/assets/goblin_rocket_sled

# 3. Viridian Valestrider (the avian). Registry wiring only, no dedicated
#    module, which is why this one is excerpts and a spec file.
mount_ref viridian-valestrider-avian feature/avian-mount avian_strider \
  scripts/assets/specs/avian_strider.json

# 4. Rickshaw. A rig authored for a runtime system to drive later.
mount_ref rickshaw feature/rickshaw-mount rickshaw_mount \
  src/render/rickshaw_mount.ts \
  tests/rickshaw_mount.test.ts \
  tests/rickshaw_mount_asset.test.ts \
  scripts/assets/rickshaw_mount \
  scripts/assets/specs/rickshaw_mount.json

# 5. Wooden toy train. Asset scripts only; it was never wired into
#    MOUNT_VISUAL_SPECS, so there is nothing to excerpt.
mount_ref wooden-toy-train feature/wooden-toy-train wooden_toy_train \
  scripts/assets/wooden_toy_train

# 6. Dachshund. No branch by that name exists in this repo. What was borrowed
#    is method, not code. See reference/README.md.

echo
echo "reference/ rebuilt:"
du -sh "$OUT"
