import type { ItemDef, PlayerClass } from '../../types';

// Archetype groups, mirrors the pattern in content/items.ts so class-locked
// delve rewards admit the whole archetype (warrior/paladin/shaman etc.).
const WAR: PlayerClass[] = ['warrior', 'paladin', 'shaman'];
const MAG: PlayerClass[] = ['mage', 'priest', 'warlock', 'druid'];
const ROG: PlayerClass[] = ['rogue', 'hunter'];

// ---------------------------------------------------------------------------
// Delve items, Collapsed Reliquary loot & Marks vendor stock
// ---------------------------------------------------------------------------
//
// Tuned to sit a clear notch ABOVE the silver-vendor armor of the same tier so
// running the delve is worth it. Smith Haldren's commons (levels 3-7) are the
// baseline: chainmail vest 60 armor / leather jerkin 40 / cloth robe 22 / wool
// trousers 24, all plain white with no stats. Each delve piece below is the
// uncommon-or-rare upgrade in that slot: more armor PLUS stat bonuses, and a
// higher sellValue than the common it replaces (greens are worth more silver
// than the whites they outclass). Marks prices live in shop.ts.
// ---------------------------------------------------------------------------

export const DELVE_ITEMS: Record<string, ItemDef> = {
  // --- uncommon (green) drops ---
  reliquary_plate_chest: {
    id: 'reliquary_plate_chest',
    name: 'Reliquary Guard Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 90, sta: 2, str: 1 },
    sellValue: 240,
    requiredClass: WAR,
  },
  reliquary_leather_chest: {
    id: 'reliquary_leather_chest',
    name: 'Dustwarden Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 55, agi: 2, sta: 1 },
    sellValue: 215,
    requiredClass: ROG,
  },
  reliquary_cloth_chest: {
    id: 'reliquary_cloth_chest',
    name: 'Shroud of the Reliquary',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 30, int: 2, spi: 1 },
    sellValue: 205,
    requiredClass: MAG,
  },
  reliquary_legs: {
    id: 'reliquary_legs',
    name: 'Vaultbound Legwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'uncommon',
    stats: { armor: 48, sta: 2 },
    sellValue: 195,
  },
  reliquary_helm: {
    id: 'reliquary_helm',
    name: 'Ossuary Watch Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'uncommon',
    stats: { armor: 48, sta: 2, str: 1 },
    sellValue: 220,
    requiredClass: WAR,
  },
  reliquary_shoulder: {
    id: 'reliquary_shoulder',
    name: 'Crumbled Spaulders',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'uncommon',
    stats: { armor: 36, sta: 2 },
    sellValue: 175,
  },
  reliquary_gloves_rog: {
    id: 'reliquary_gloves_rog',
    name: 'Bonewarden Grips',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'uncommon',
    stats: { armor: 36, agi: 2, sta: 1 },
    sellValue: 190,
    requiredClass: ROG,
  },
  // --- rare (blue) signature drops, Heroic-gated ---
  deacon_reliquary_helm: {
    id: 'deacon_reliquary_helm',
    name: "Deacon's Reliquary Helm",
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'rare',
    stats: { armor: 105, sta: 4, str: 3 },
    sellValue: 540,
    requiredClass: WAR,
  },
  varric_shadow_cowl: {
    id: 'varric_shadow_cowl',
    name: "Vandric's Shadow Cowl",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'rare',
    stats: { armor: 42, int: 4, spi: 3 },
    sellValue: 540,
    requiredClass: MAG,
  },
  // --- The Drowned Litany (Mirefen Marsh delve) ---
  siltguard_helm: {
    id: 'siltguard_helm',
    name: 'Siltguard Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'uncommon',
    stats: { armor: 52, sta: 2, str: 1 },
    sellValue: 230,
    requiredClass: WAR,
  },
  bulwark_rusted_pauldrons: {
    id: 'bulwark_rusted_pauldrons',
    name: 'Bulwark-Rusted Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'uncommon',
    stats: { armor: 40, sta: 2 },
    sellValue: 210,
    requiredClass: WAR,
  },
  nhalias_bell_maul: {
    id: 'nhalias_bell_maul',
    name: "Nhalia's Bell-Maul",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 38, max: 58, speed: 3.5 },
    stats: { str: 3, sta: 2 },
    sellValue: 560,
    requiredClass: WAR,
  },
  reedstalker_jerkin: {
    id: 'reedstalker_jerkin',
    name: 'Reedstalker Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 58, agi: 2, sta: 1 },
    sellValue: 225,
    requiredClass: ROG,
  },
  mirejaw_fang_knife: {
    id: 'mirejaw_fang_knife',
    name: 'Mirejaw Fang-Knife',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 14, max: 22, speed: 1.8, dagger: true },
    stats: { agi: 2 },
    sellValue: 200,
    requiredClass: ROG,
  },
  widow_silk_hood: {
    id: 'widow_silk_hood',
    name: 'Widow-Silk Hood',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'rare',
    stats: { armor: 36, agi: 3, sta: 2 },
    sellValue: 520,
    requiredClass: ROG,
  },
  cantors_drowned_sash: {
    id: 'cantors_drowned_sash',
    name: "Cantor's Drowned Sash",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'waist',
    quality: 'uncommon',
    stats: { armor: 18, int: 2, spi: 1 },
    sellValue: 205,
    requiredClass: MAG,
  },
  corpse_candle_focus: {
    id: 'corpse_candle_focus',
    name: 'Corpse-Candle Focus',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 9, max: 15, speed: 2.0 },
    stats: { int: 2, spi: 2 },
    sellValue: 195,
    requiredClass: MAG,
  },
  nhalias_litany_rod: {
    id: 'nhalias_litany_rod',
    name: "Nhalia's Litany Rod",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 18, max: 30, speed: 3.2 },
    stats: { int: 4, spi: 2 },
    sellValue: 550,
    requiredClass: MAG,
  },
  // --- epic (purple) prestige drops, bountiful-only 12% from the Drowned Reliquary Rite ---
  blackwater_vanguard_chest: {
    id: 'blackwater_vanguard_chest',
    name: 'Blackwater Vanguard Chestguard',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    stats: { armor: 220, str: 9, sta: 8 },
    sellValue: 5000,
    requiredClass: WAR,
  },
  siltstep_leggings: {
    id: 'siltstep_leggings',
    name: 'Siltstep Leggings',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    stats: { armor: 130, agi: 9, sta: 7 },
    sellValue: 5000,
    requiredClass: ROG,
  },
  sunken_reliquary_hood: {
    id: 'sunken_reliquary_hood',
    name: 'Sunken Reliquary Hood',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    stats: { armor: 75, int: 10, sta: 7 },
    sellValue: 5000,
    requiredClass: MAG,
  },
  // --- The Drowned Litany Marks vendor stock (Brother Halven), distinct from the
  // finale-rite drops above: a straight Marks-for-gear buy to prep for the level
  // 14-20 zone beyond the marsh. Prices live in shop.ts. ---
  litany_legs: {
    id: 'litany_legs',
    name: 'Silt-Walker Greaves',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'uncommon',
    stats: { armor: 58, sta: 3 },
    sellValue: 235,
  },
  litany_shoulder: {
    id: 'litany_shoulder',
    name: 'Blackwater Drift Mantle',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'uncommon',
    stats: { armor: 44, sta: 3 },
    sellValue: 215,
  },
  litany_gloves_rog: {
    id: 'litany_gloves_rog',
    name: 'Reed-Bound Handwraps',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'uncommon',
    stats: { armor: 44, agi: 2, sta: 2 },
    sellValue: 225,
    requiredClass: ROG,
  },
  litany_plate_chest: {
    id: 'litany_plate_chest',
    name: 'Sump-Warden Cuirass',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 108, sta: 3, str: 2 },
    sellValue: 290,
    requiredClass: WAR,
  },
  litany_leather_chest: {
    id: 'litany_leather_chest',
    name: 'Silt-Deep Vestment',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 66, agi: 3, sta: 2 },
    sellValue: 265,
    requiredClass: ROG,
  },
  litany_cloth_chest: {
    id: 'litany_cloth_chest',
    name: 'Choir-Drowned Raiment',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 36, int: 3, spi: 2 },
    sellValue: 250,
    requiredClass: MAG,
  },
  litany_helm: {
    id: 'litany_helm',
    name: "Reliquant's Drowned Cowl",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'uncommon',
    stats: { armor: 32, int: 3, spi: 2 },
    sellValue: 255,
    requiredClass: MAG,
  },
  // --- rare (blue) signature vendor gear, Heroic-gated ---
  sister_nhalia_choir_plate: {
    id: 'sister_nhalia_choir_plate',
    name: "Sister Nhalia's Choir-Forged Plate",
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'rare',
    stats: { armor: 150, str: 5, sta: 4 },
    sellValue: 650,
    requiredClass: WAR,
  },
  drowned_choir_fang: {
    id: 'drowned_choir_fang',
    name: 'Drowned Choir-Fang',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 20, max: 32, speed: 1.7, dagger: true },
    stats: { agi: 4, sta: 3 },
    sellValue: 620,
    requiredClass: ROG,
  },
};
