import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { runInNewContext } from 'node:vm';
import { transformSync } from 'esbuild';
import * as fs from 'fs';
import path from 'path';
import { describe, expect, it } from 'vitest';
// @ts-expect-error - shared zero-dep JS hash helper (no .d.ts). The scanner uses the
// SAME module, so re-deriving hashes here is an independent check of the registry
// rather than a copy of the scanner's own arithmetic.
import { contentHash, placeholdersOf } from '../scripts/i18n_hash.mjs';
import { RETIRED_KEY_SET, RETIRED_REASON } from '../scripts/i18n_retired_keys.mjs';
import { DICT as adminDICT } from '../src/admin/i18n';
import { en, supportedLanguages } from '../src/ui/i18n';
import { DICT as serverDICT } from '../src/ui/server_i18n';
import { DICT as simDICT, simDictProvidedKeys } from '../src/ui/sim_i18n';
import { assertDeterministic } from './helpers/i18n_determinism';

// src/ui/i18n.status.json is the generated per-key per-locale status
// registry (scripts/i18n_scan.mjs, regenerated in pretest). This suite is the
// registry-in-sync + reproducibility net: the registry must cover the whole key
// universe, every enHash must independently re-derive from the English source,
// the pending set must be empty while everything is dense, blocked rows must be
// load-bearing (no silent over-allow), the hash must move when the English text
// or its placeholder set changes, and the artifact must regenerate byte-identically.

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const registryRel = 'src/ui/i18n.status.json';
// status.json is gitignored and regenerated by pretest / the CI i18n:gen step, so it
// is always present under `npm test`. Point at the fix rather than a raw ENOENT if
// this file is run directly on a tree where the registry was never generated.
const registryPath = path.join(root, registryRel);
if (!fs.existsSync(registryPath))
  throw new Error(
    'src/ui/i18n.status.json is missing - run `npm run i18n:gen` (pretest does this for `npm test`).',
  );
const registry: any = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
// The audit summary (counts + per-locale rollup + universeHash, no per-key bodies)
// emitted alongside the gitignored full registry by the same scanner run; it is
// likewise gitignored and regenerated by pretest / the CI i18n:gen step.
const summaryRel = 'src/ui/i18n.status.summary.json';
const summary: any = JSON.parse(fs.readFileSync(path.join(root, summaryRel), 'utf8'));
const NON_EN = supportedLanguages.filter((l) => l !== 'en');

// Two-tier gate: the release tier runs with I18N_RELEASE_TIER=1 (see
// .github/workflows/ci.yml). An empty-`pending` set is a RELEASE guarantee, not a
// PR one - an English-only PR legitimately leaves keys pending - so that assertion
// runs release-only. Registry-in-sync (universe coverage, enHash re-derivation,
// reproducibility) stays at the PR tier.
const RELEASE_TIER = process.env.I18N_RELEASE_TIER === '1';

// Same object-vs-leaf rule as scripts/i18n_flatten.mjs (recurse PLAIN objects;
// arrays and non-objects are leaves), so the universe we expect matches the one
// the scanner walked.
function flatten(node: any, prefix = '', out: Record<string, string> = {}): Record<string, string> {
  for (const k of Object.keys(node)) {
    const v = node[k];
    const p = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === 'object' && !Array.isArray(v)) flatten(v, p, out);
    else out[p] = v as string;
  }
  return out;
}

// The English source value for every key in the universe, keyed by the registry's
// "<scope>:<key>" composite. Built straight from the imported source objects.
function expectedUniverse(): Map<string, string> {
  const m = new Map<string, string>();
  for (const [k, v] of Object.entries(flatten(en as any))) m.set(`main:${k}`, v);
  for (const [k, v] of Object.entries(simDICT.en)) m.set(`sim:${k}`, v as string);
  for (const [k, v] of Object.entries(serverDICT.en)) m.set(`server:${k}`, v as string);
  for (const [k, v] of Object.entries(adminDICT.en)) m.set(`admin:${k}`, v as string);
  return m;
}

const keyEntries = (): [string, any][] => Object.entries(registry.keys);

describe('i18n status registry: universe coverage', () => {
  it('has exactly one row per source key (en leaves + sim/server/admin DICT keys)', () => {
    const expected = expectedUniverse();
    const regKeys = new Set(Object.keys(registry.keys));
    const missing = [...expected.keys()].filter((k) => !regKeys.has(k));
    expect(missing.length, `registry is missing rows for: ${missing.slice(0, 10).join(', ')}`).toBe(
      0,
    );
    const extra = [...regKeys].filter((k) => !expected.has(k));
    expect(
      extra.length,
      `registry has rows with no source key: ${extra.slice(0, 10).join(', ')}`,
    ).toBe(0);
    expect(registry.counts.keys).toBe(expected.size);
  });

  it('tracks exactly supportedLanguages minus en, in order', () => {
    expect(registry.locales).toEqual(NON_EN);
    for (const [, entry] of keyEntries()) {
      expect(Object.keys(entry.locales)).toEqual(NON_EN);
    }
  });
});

describe('i18n status registry: enHash re-derivation (independent)', () => {
  it('each enHash == contentHash(englishText, sortedPlaceholders) recomputed from source', () => {
    // Accumulate violations and assert ONCE: a per-row expect() over the ~5k-key
    // universe costs seconds of matcher overhead and trips the default per-test
    // timeout on a loaded runner, for identical semantics.
    const expected = expectedUniverse();
    const violations: string[] = [];
    for (const [ck, enVal] of expected) {
      const row = registry.keys[ck];
      if (row.enHash !== contentHash(enVal, placeholdersOf(enVal)))
        violations.push(`${ck} enHash mismatch`);
      if (JSON.stringify(row.placeholders) !== JSON.stringify(placeholdersOf(enVal)))
        violations.push(`${ck} placeholders`);
    }
    expect(violations).toEqual([]);
  });
});

describe('i18n status registry: states', () => {
  // RELEASE-TIER ONLY. A `pending` key must never reach a cut release;
  // the release gate asserts the set is empty. At the PR tier a pending key is
  // LEGAL (English-only PRs), so this is skipped there. Release preparation must
  // resolve every pending row before this check can pass.
  it.runIf(RELEASE_TIER)(
    'the pending set is empty (release tier: no untranslated key may ship)',
    () => {
      expect(registry.counts.pending).toBe(0);
      let pending = 0;
      for (const [, entry] of keyEntries())
        for (const row of Object.values<any>(entry.locales)) if (row.state === 'pending') pending++;
      expect(pending).toBe(0);
    },
  );

  // Teeth for the release-tier gate above. That gate reads the real, dense registry
  // (pending=0 today), so on its own it cannot prove the assertion is non-vacuous.
  // Mirror the manual injection as a COMMITTED check: flip one translated row to
  // pending in a clone and confirm BOTH quantities the gate measures (counts.pending
  // and a fresh re-tally of pending rows) become non-zero - i.e. a pending key WOULD
  // trip the gate. Runs at both tiers so the teeth can never silently rot.
  it('the pending===0 gate is non-vacuous (a synthetic pending row trips both measured quantities)', () => {
    const clone = JSON.parse(JSON.stringify(registry));
    let flipped = false;
    for (const entry of Object.values<any>(clone.keys)) {
      for (const row of Object.values<any>(entry.locales))
        if (row.state === 'translated') {
          row.state = 'pending';
          flipped = true;
          break;
        }
      if (flipped) break;
    }
    expect(flipped, 'fixture sanity: at least one translated row must exist to flip').toBe(true);
    clone.counts.pending += 1;
    // Both conditions the release-tier gate asserts to be 0 are now non-zero:
    expect(clone.counts.pending).not.toBe(0);
    let pending = 0;
    for (const entry of Object.values<any>(clone.keys))
      for (const row of Object.values<any>(entry.locales)) if (row.state === 'pending') pending++;
    expect(pending).toBeGreaterThan(0);
  });

  it('counts are internally consistent and match a fresh re-tally', () => {
    const { keys, rows, translated, pending, blocked, blockedSource } = registry.counts;
    expect(rows).toBe(keys * NON_EN.length);
    expect(translated + pending + blocked).toBe(rows);
    expect(blockedSource).toBe(registry.blockedSource.length);
    let t = 0,
      p = 0,
      b = 0;
    for (const [, entry] of keyEntries())
      for (const row of Object.values<any>(entry.locales)) {
        if (row.state === 'translated') t++;
        else if (row.state === 'pending') p++;
        else if (row.state === 'blocked') b++;
      }
    expect([t, p, b]).toEqual([translated, pending, blocked]);
  });

  it('every translated row is fresh (srcHash === enHash) and attributed (by human|agent)', () => {
    // Accumulate violations and assert ONCE: this walks ~100k locale rows, and a
    // per-row expect() pair (~200k matcher calls) took ~6s, past the default 5s
    // per-test budget on a loaded runner (the flake seen in full-suite runs).
    // Plain JS checks keep it in milliseconds with identical semantics.
    const violations: string[] = [];
    for (const [ck, entry] of keyEntries())
      for (const [loc, row] of Object.entries<any>(entry.locales)) {
        if (row.state !== 'translated') continue;
        if (row.srcHash !== entry.enHash) violations.push(`${ck} ${loc} stale srcHash`);
        if (row.by !== 'human' && row.by !== 'agent') violations.push(`${ck} ${loc} unattributed`);
      }
    expect(violations).toEqual([]);
  });

  it('sim-scope rows report per-locale SOURCE presence, never the assembled English spread', () => {
    // The sim DICT is dense by construction (baseEnTable is spread under every
    // locale), so a scan of the assembled table marked every sim key translated
    // everywhere and the release fill could never see a sim-scope row
    // (Masterwrought Phase 19F, qr-19-sim-scope-pending-is-unreachable). The
    // scanner now reads simDictProvidedKeys, the union of a locale's own source
    // blocks. Both directions are pinned against the LIVE sources rather than
    // against the scanner's own arithmetic: a key no source block of a locale
    // carries reads pending, a key the block carries reads translated, and the
    // English dialect (en_CA, whose base is en) reads translated for every key.
    // Source presence remains authoritative after the release fill makes
    // every locale complete. The independent literal-row witness below catches
    // an export that accidentally claims fallback rows as locale-owned rows.
    const langs = NON_EN.filter((l) => l !== 'en_CA');
    let pendingSeen = 0;
    let carriedSeen = 0;
    const violations: string[] = [];
    for (const [ck, entry] of keyEntries()) {
      if (!ck.startsWith('sim:')) continue;
      const key = ck.slice('sim:'.length);
      for (const lang of langs) {
        const row = entry.locales[lang];
        if (row.state === 'blocked') continue;
        const carried = simDictProvidedKeys(lang).has(key);
        const want = carried ? 'translated' : 'pending';
        if (row.state !== want) violations.push(`${ck} ${lang}: ${row.state}, source says ${want}`);
        if (carried) carriedSeen++;
        else pendingSeen++;
      }
      if (entry.locales.en_CA.state !== 'translated')
        violations.push(`${ck} en_CA: ${entry.locales.en_CA.state}, the English dialect inherits`);
    }
    expect(violations).toEqual([]);
    expect(carriedSeen, 'the sim scope has filled rows today').toBeGreaterThan(0);
    // Runtime dictionaries remain dense even if a future source row is missing.
    const dense = simDICT as unknown as Record<string, Record<string, string>>;
    const denseCount = langs.reduce(
      (n, lang) => n + Object.keys(dense.en).filter((k) => Boolean(dense[lang][k])).length,
      0,
    );
    expect(denseCount).toBe(Object.keys(simDICT.en).length * langs.length);
    expect(carriedSeen + pendingSeen).toBeLessThanOrEqual(denseCount);
  });

  // The two arms below anchor simDictProvidedKeys on something OTHER than
  // itself (19F review round: the arm above derives its expectation from the
  // export the scanner reads, so a regression confined to the export's body
  // leaves both in agreement). Source text is the independent witness: the
  // sim module is data-as-code, and its locale rows are literal `'key':` lines.
  const simSource = fs.readFileSync(path.join(root, 'src/ui/sim_i18n.ts'), 'utf8');
  const newLocalesSource = fs.readFileSync(
    path.join(root, 'src/ui/sim_i18n.newlocales.ts'),
    'utf8',
  );
  const stripComments = (src: string) =>
    src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^[ \t]*\/\/.*$/gm, '');

  it('simDictProvidedKeys enumerates exactly the sources the DICT literal spreads', () => {
    // A sixth per-locale table spread into DICT and forgotten here would read
    // pending for every key it carries (the fill asked to redo translated
    // rows); a table dropped from DICT but kept here would read translated
    // while the runtime serves the English spread (the original D148 bug).
    const src = stripComments(simSource);
    const dictStart = src.indexOf('export const DICT');
    const dictEnd = src.indexOf(
      ') as Record<SupportedLanguage, Record<SimMessageKey, string>>;',
      dictStart,
    );
    expect(dictStart).toBeGreaterThan(-1);
    expect(dictEnd).toBeGreaterThan(dictStart);
    const dictLiteral = src.slice(dictStart, dictEnd);
    const spread = [...dictLiteral.matchAll(/\.\.\.([A-Za-z0-9_]+)\[lang\]/g)]
      .map((m) => m[1])
      .filter((name) => name !== 'baseEnTable')
      .sort();
    const exportStart = src.indexOf('export function simDictProvidedKeys');
    const exportEnd = src.indexOf('\n}\n', exportStart);
    expect(exportStart).toBeGreaterThan(-1);
    const exportBody = src.slice(exportStart, exportEnd);
    const tables = [...exportBody.matchAll(/([A-Za-z0-9_]+)\[lang\]/g)]
      .map((m) => m[1])
      .filter((name) => name !== 'ARENA_QUEUE_AUTO_LEAVE_1V1')
      .sort();
    expect(spread.length, 'the DICT literal spreads per-locale tables').toBeGreaterThanOrEqual(4);
    expect(tables).toEqual(spread);
    // The one non-spread source, the arena literal, is in both.
    expect(dictLiteral).toContain("'log.arenaQueueAutoLeave1v1': ARENA_QUEUE_AUTO_LEAVE_1V1[lang]");
    expect(exportBody).toContain('ARENA_QUEUE_AUTO_LEAVE_1V1[lang]');
    expect(exportBody).toContain("provided.add('log.arenaQueueAutoLeave1v1')");
  });

  it('keeps an omitted or blank source row absent even when runtime fallback is dense', () => {
    // Exercise the actual provider body against a sparse fixture. This stays
    // decisive after every shipping locale has been filled, when the live
    // source and dense runtime tables legitimately contain the same keys.
    const start = simSource.indexOf('export function simDictProvidedKeys');
    const end = simSource.indexOf('\n}\n', start) + 2;
    expect(start).toBeGreaterThan(-1);
    expect(end).toBeGreaterThan(start);
    const code = transformSync(simSource.slice(start, end), {
      loader: 'ts',
      format: 'cjs',
    }).code;
    const context = {
      exports: {},
      module: { exports: {} as { simDictProvidedKeys: (lang: string) => Set<string> } },
      BASE_DICT: { cs_CZ: { owned: 'Překlad', blank: '   ' } },
      PET_DICT: { cs_CZ: { pet: 'Společník' } },
      RAID_BOSS_DIALOGUE_DICT: {},
      IGNIVAR_DICT: {},
      ARENA_QUEUE_AUTO_LEAVE_1V1: {},
      DICT: { cs_CZ: { owned: 'Překlad', blank: 'English', omitted: 'English' } },
    };
    runInNewContext(code, context);
    expect([...context.module.exports.simDictProvidedKeys('cs_CZ')].sort()).toEqual([
      'owned',
      'pet',
    ]);
    expect([...context.module.exports.simDictProvidedKeys('da_DK')]).toEqual([]);
  });

  it('every provided sim row is a literal row of some locale block (source-text anchor)', () => {
    // For each DICT key, the number of locales whose provided set carries it
    // must equal the number of literal `'key':` rows in the two sim modules
    // minus the English table's own row. A fallback that grants a locale the
    // whole DICT, or a spread of BASE_NEW into every locale, over-provides
    // rows no block spells and reds here; a duplicated row inside one block
    // reds too (JS keeps the last, and the fill must see it). The arena
    // literal is excluded (its rows are a per-locale string table, not keyed
    // rows). Independent of the export's own arithmetic by construction.
    const text = stripComments(simSource) + '\n' + stripComments(newLocalesSource);
    const rowCount = new Map<string, number>();
    for (const m of text.matchAll(/'([A-Za-z0-9_.]+)':/g))
      rowCount.set(m[1], (rowCount.get(m[1]) ?? 0) + 1);
    const enStart = text.indexOf('const baseEnTable = {');
    const enEnd = text.indexOf('} as const;', enStart);
    expect(enStart).toBeGreaterThan(-1);
    expect(enEnd).toBeGreaterThan(enStart);
    const enRows = new Set(
      [...text.slice(enStart, enEnd).matchAll(/'([A-Za-z0-9_.]+)':/g)].map((m) => m[1]),
    );
    expect(enRows.size).toBeGreaterThan(500);
    expect(enRows.size).toBeLessThan(Object.keys(simDICT.en).length);
    // The pet tables are per-language consts ALIASED across locales (es and
    // es_ES share PET_DICT_ES) and typed dense, so a pet key's literal rows
    // never equal its provider count; presence there cannot vary and the
    // spread-list arm above covers the table. Skip those keys here.
    const petStart = text.indexOf('const PET_DICT_EN');
    const petEnd = text.indexOf('\n};', petStart);
    expect(petStart).toBeGreaterThan(-1);
    const petKeys = new Set(
      [...text.slice(petStart, petEnd).matchAll(/'([A-Za-z0-9_.]+)':/g)].map((m) => m[1]),
    );
    expect(petKeys.size).toBeGreaterThan(20);
    const providedBy = new Map<string, Set<string>>();
    for (const lang of supportedLanguages) providedBy.set(lang, new Set(simDictProvidedKeys(lang)));
    const violations: string[] = [];
    let checked = 0;
    for (const key of Object.keys(simDICT.en)) {
      if (key === 'log.arenaQueueAutoLeave1v1' || petKeys.has(key)) continue;
      const providers = supportedLanguages.filter((lang) => providedBy.get(lang)!.has(key)).length;
      const literalRows = (rowCount.get(key) ?? 0) - (enRows.has(key) ? 1 : 0);
      if (providers !== literalRows)
        violations.push(
          `${key}: ${providers} locales provide it, ${literalRows} locale rows spell it`,
        );
      checked++;
    }
    expect(violations).toEqual([]);
    expect(checked).toBeGreaterThan(700);
    // A completed locale may now provide the whole table. Source rows must
    // still never invent a key absent from the authoritative English table.
    for (const [lang, keys] of providedBy) {
      expect(
        [...keys].filter((key) => !(key in simDICT.en)),
        `${lang} unknown keys`,
      ).toEqual([]);
    }
  });
});

describe('i18n status registry: blocked rows are load-bearing (no over-allow)', () => {
  const dicts: Record<string, any> = { server: serverDICT, admin: adminDICT };

  it('every blocked server/admin row genuinely copies English (value === en) and has a reason', () => {
    for (const [ck, entry] of keyEntries()) {
      const ci = ck.indexOf(':');
      const scope = ck.slice(0, ci);
      const key = ck.slice(ci + 1);
      if (scope !== 'server' && scope !== 'admin') continue;
      for (const [loc, row] of Object.entries<any>(entry.locales)) {
        if (row.state !== 'blocked') continue;
        expect(
          typeof row.reason === 'string' && row.reason.trim().length > 0,
          `${ck} ${loc} blocked w/o reason`,
        ).toBe(true);
        const dict = dicts[scope];
        // A cognate is, by definition, a translation that equals English. If this
        // ever fails the seed has rotted: the value got translated, so the row
        // should be translated, not blocked (silent over-allow).
        expect(dict[loc]?.[key], `${ck} ${loc} is blocked but no longer copies English`).toBe(
          dict.en[key],
        );
      }
    }
  });

  it('main/sim blocked rows exist ONLY for retired main keys, with the retired reason', () => {
    // Phase 14 widened the main scope's blocked rows to exactly the RETIRED
    // keys (scripts/i18n_retired_keys.mjs): a key no page renders is never a
    // fill work item, so its unprovided rows are blocked-with-reason instead
    // of pending. Everything else in main, and ALL of sim, still carries
    // none: the over-allow hazard this pin exists for is unchanged.
    // Same accumulate-then-assert-once shape as the freshness walk above.
    const violations: string[] = [];
    for (const [ck, entry] of keyEntries()) {
      const ci = ck.indexOf(':');
      const scope = ck.slice(0, ci);
      const key = ck.slice(ci + 1);
      if (scope === 'server' || scope === 'admin') continue;
      for (const row of Object.values<any>(entry.locales)) {
        if (row.state !== 'blocked') continue;
        if (scope !== 'main' || !RETIRED_KEY_SET.has(key))
          violations.push(`${ck} unexpected blocked row in scope ${scope}`);
        else if (row.reason !== RETIRED_REASON)
          violations.push(`${ck} retired blocked row without the retired reason`);
      }
    }
    expect(violations).toEqual([]);
  });

  it('no retired key carries a pending row anywhere (the Phase 14 exclusion), non-vacuously', () => {
    // The exclusion's decisive arm: the release fill pass walks pending, so a
    // retired key with a pending row would put never-rendered prose on the
    // fill worklist. Non-vacuity: at least one retired key really has
    // unprovided rows (the gatherDeeds.farming outlier the exclusion was cut
    // for), so this cannot pass by every retired key being fully filled.
    let retiredBlocked = 0;
    for (const [ck, entry] of keyEntries()) {
      const ci = ck.indexOf(':');
      if (ck.slice(0, ci) !== 'main' || !RETIRED_KEY_SET.has(ck.slice(ci + 1))) continue;
      for (const row of Object.values<any>(entry.locales)) {
        expect(row.state, `${ck} retired key must never be pending`).not.toBe('pending');
        if (row.state === 'blocked') retiredBlocked++;
      }
    }
    expect(retiredBlocked).toBeGreaterThan(0);
    // The marker string the ledger reads, pinned to its literal ONCE here so
    // the reason comparison above is never a self-comparison against the
    // same constant the generator writes (the wire-name pin rule).
    expect(RETIRED_REASON).toBe(
      'Retired key: kept only for its reviewed overlay rows and the release-fill ledger; no page renders it (tests/guide_key_coverage.test.ts RETIRED_KEYS), so it is never a fill work item.',
    );
  });

  it('the runtime pending set excludes retired keys too (build/registry lockstep)', async () => {
    // The build's pending.ts and the registry are computed by two scripts kept
    // in lockstep; the retired exclusion must hold in BOTH or the runtime
    // English-fill accounting and the release ledger disagree.
    const { pending } = await import('../src/ui/i18n.resolved.generated/pending');
    const langs = Object.keys(pending);
    expect(langs).toEqual(NON_EN);
    // Shipping locales can be fully translated. Exercise the actual builder
    // against an omitted live successor and its retired predecessor instead:
    // deleting the retired filter or emptying all pending sets must both fail.
    const buildSource = fs.readFileSync(path.join(root, 'scripts/i18n_build.mjs'), 'utf8');
    const start = buildSource.indexOf('const isPresent =');
    const end = buildSource.indexOf('\n}\n', start) + 2;
    expect(start).toBeGreaterThan(-1);
    expect(end).toBeGreaterThan(start);
    const fixturePending = runInNewContext(
      `${buildSource.slice(start, end)}; computePending(englishFixture, { cs_CZ: {} })`,
      {
        flatten,
        LOCALES: ['en', 'cs_CZ', 'en_CA'],
        DIALECT_BASE: { en_CA: 'en' },
        RETIRED_KEY_SET,
        englishFixture: {
          'guide.profPages.gatherDeeds.farming': 'Retired farming copy',
          'guide.profPages.gatherDeeds.farmingSown': 'Live farming copy',
        },
      },
    );
    expect(fixturePending.cs_CZ).toEqual(['guide.profPages.gatherDeeds.farmingSown']);
    expect(fixturePending.en_CA).toEqual([]);
    for (const [lang, keys] of Object.entries(pending)) {
      for (const key of keys) {
        expect(RETIRED_KEY_SET.has(key), `${lang} runtime-pending retired key ${key}`).toBe(false);
      }
    }
  });

  it('every blockedSource entry is a unique sim-channel string with a reason', () => {
    const texts: string[] = registry.blockedSource.map((b: any) => b.text);
    expect(new Set(texts).size).toBe(texts.length);
    for (const b of registry.blockedSource) {
      expect(b.channel).toBe('sim');
      expect(typeof b.reason === 'string' && b.reason.length > 0).toBe(true);
    }
  });
});

describe('i18n status registry: hash sensitivity (srcHash includes the placeholder set)', () => {
  it('changing the English text moves the hash', () => {
    expect(contentHash('You have {n} gold.')).not.toBe(contentHash('You have {n} silver.'));
  });
  it('renaming a placeholder moves the hash', () => {
    expect(contentHash('Hello {name}')).not.toBe(contentHash('Hello {playerName}'));
  });
  it('the declared placeholder set feeds the hash independently of the text, and is order-independent', () => {
    expect(contentHash('X', ['a'])).not.toBe(contentHash('X', ['b']));
    expect(contentHash('X', ['a', 'b'])).toBe(contentHash('X', ['b', 'a']));
  });
});

describe('i18n status registry: determinism (status.json is gitignored - no committed bytes to diff)', () => {
  // src/ui/i18n.status.json is build/test-only (~4.7 MB) and gitignored, so the old
  // committed-bytes `git ls-files` + `git diff --exit-code` freshness check no longer
  // applies (pretest / the CI i18n:gen step regenerate it before any test reads it).
  // Reproducibility is instead proven by double-generating into two PERTURBED-env temp
  // dirs (different TZ / LC_ALL / temp-path) and asserting byte-identity. A
  // non-deterministic scanner makes this throw. The summary is likewise gitignored and
  // covered by the same double-generation check (both files are in outFiles below).
  // Double-generates by spawning the scanner (cold Node + esbuild bundle of the TS
  // source) TWICE, so the default 5s per-test budget is too tight on a loaded CI
  // runner (a single cold scan is already ~1-3s there). Give it a generous timeout;
  // the assertion is about byte-identity, not speed.
  it('regenerates status.json + the summary byte-identically across two perturbed-env runs', () => {
    expect(() =>
      assertDeterministic({
        script: path.join(root, 'scripts/i18n_scan.mjs'),
        outFiles: ['i18n.status.json', 'i18n.status.summary.json'],
      }),
    ).not.toThrow();
  }, 30_000);
});

describe('i18n status summary: audit rollup cross-checks the full registry', () => {
  it('keeps the audit summary out of version control (gitignored, still generated)', () => {
    // Re-committing the summary would resurrect the guaranteed pairwise merge
    // conflict the degit change removed; its audit trail lives in the CI job
    // summary instead. `--error-unmatch` throws only for an untracked path.
    expect(() =>
      execFileSync('git', ['ls-files', '--error-unmatch', '--', summaryRel], {
        cwd: root,
        encoding: 'utf8',
      }),
    ).toThrow();
  });

  it('summary counts equal the full registry counts, and locales/scopes mirror it', () => {
    expect(summary.counts).toEqual(registry.counts);
    expect(summary.locales).toEqual(registry.locales);
    expect(summary.scopes).toEqual(registry.scopes);
  });

  it('the per-locale rollup tallies to the registry totals and to keys-per-locale', () => {
    expect(Object.keys(summary.perLocale)).toEqual(NON_EN);
    let t = 0,
      p = 0,
      b = 0;
    for (const lang of NON_EN) {
      const row = summary.perLocale[lang];
      // Every key has exactly one state per locale, so the three states sum to `keys`.
      expect(row.translated + row.pending + row.blocked, `${lang} rollup != key count`).toBe(
        registry.counts.keys,
      );
      t += row.translated;
      p += row.pending;
      b += row.blocked;
    }
    expect([t, p, b]).toEqual([
      registry.counts.translated,
      registry.counts.pending,
      registry.counts.blocked,
    ]);
  });

  it('the universeHash re-derives independently from the full registry', () => {
    // Same canonical form the scanner hashes: "<composite><enHash><placeholders>"
    // per key, in registry (emit) order, joined by newlines.
    const SEP = String.fromCharCode(0x1f);
    const derived = createHash('sha256')
      .update(
        Object.entries(registry.keys)
          .map(
            ([ck, e]: [string, any]) => `${ck}${SEP}${e.enHash}${SEP}${e.placeholders.join(',')}`,
          )
          .join('\n'),
        'utf8',
      )
      .digest('hex');
    expect(summary.universeHash).toBe(derived);
  });
});
