// GENERATED by scripts/build_map_backgrounds.mjs; do not edit by hand.
// Re-bake with `npm run assets:mapbg` after any world-generation change
// (tests/map_bg_baked.test.ts guards freshness). Plates live in public/map_bg/.

export const BAKED_MAP_BG = {
  seed: 20061,
  pxPerYd: 1.3333333333333333,
  hashRows: 16,
  zones: {
  "eastbrook_vale": {
    "w": 480,
    "h": 480,
    "rowHash": "b9a4df2b"
  },
  "mirefen_marsh": {
    "w": 480,
    "h": 480,
    "rowHash": "0576b60c"
  },
  "thornpeak_heights": {
    "w": 480,
    "h": 480,
    "rowHash": "64f3ed37"
  },
  "veiled_hollow": {
    "w": 720,
    "h": 720,
    "rowHash": "5f01ee31"
  },
  "drakelands": {
    "w": 640,
    "h": 800,
    "rowHash": "0296af91"
  },
  "frostveil": {
    "w": 693,
    "h": 693,
    "rowHash": "b7e55216"
  },
  "amberfall": {
    "w": 613,
    "h": 746,
    "rowHash": "4c562364"
  },
  "willowfen": {
    "w": 587,
    "h": 694,
    "rowHash": "b497d16e"
  },
  "nightbloom": {
    "w": 613,
    "h": 746,
    "rowHash": "624a4c22"
  },
  "wraithwood": {
    "w": 613,
    "h": 746,
    "rowHash": "fe751ecf"
  },
  "palmreach": {
    "w": 613,
    "h": 746,
    "rowHash": "227a8eb0"
  },
  "evergarden": {
    "w": 613,
    "h": 746,
    "rowHash": "dd3f0bb5"
  },
  "galecrest": {
    "w": 587,
    "h": 694,
    "rowHash": "9e0f3e3c"
  },
  "farshore_isle": {
    "w": 480,
    "h": 480,
    "rowHash": "f593fe3c"
  },
  "proving_shore": {
    "w": 480,
    "h": 480,
    "rowHash": "cf87eb8d"
  },
  "world_strip": {
    "w": 140,
    "h": 337,
    "rowHash": "952fd0be"
  }
},
} as const;
