// Generates src/editor/asset_catalog.generated.ts: a flat catalogue of every GLB
// model under public/models, grouped by category, for the map editor's asset
// palette. Re-run after adding models: `node scripts/gen_asset_catalog.mjs`.
//
// This is a GENERATED file (do not hand-edit the output). It only enumerates what
// exists on disk; how each asset is instantiated for play-test is resolved by the
// editor's asset loader against the engine, not here.

import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isFoliageFieldCopyCatalogId } from './assets/foliage_bark_decimation.mjs';

const root = fileURLToPath(new URL('..', import.meta.url));
const modelsDir = join(root, 'public', 'models');
const outFile = join(root, 'src', 'editor', 'asset_catalog.generated.ts');

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) out.push(...walk(full));
    else if (/\.(glb|gltf)$/i.test(name)) out.push(full);
  }
  return out;
}

// "models/props/market_stand_1.glb" -> { category: 'props', id: 'props/market_stand_1' }
function toEntry(full) {
  const rel = relative(join(root, 'public'), full).split('\\').join('/');
  const noExt = rel.replace(/\.(glb|gltf)$/i, '');
  const parts = noExt.split('/'); // ['models', '<category>', ...rest]
  const category = parts[1] ?? 'misc';
  const id = parts.slice(1).join('/'); // category-qualified, stable, unique
  const leaf = parts[parts.length - 1];
  const label = leaf
    .replace(/[_-]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .trim();
  return { id, category, label, path: `/${rel}` };
}

// The world foliage field's decimated-bark copies
// (scripts/assets/decimate_foliage_bark.mjs) are not placeable: an authored
// map places the full-detail original, at any scale.
const entries = walk(modelsDir)
  .map(toEntry)
  .filter((e) => !isFoliageFieldCopyCatalogId(e.id))
  .sort((a, b) => a.id.localeCompare(b.id));

const byCat = {};
for (const e of entries) {
  byCat[e.category] ??= [];
  byCat[e.category].push(e.id);
}

const header = `// GENERATED by scripts/gen_asset_catalog.mjs - do not edit by hand.
// ${entries.length} placeable GLB assets across ${Object.keys(byCat).length} categories.

export interface AssetEntry {
  /** Category-qualified stable id, e.g. "props/well". */
  id: string;
  /** Top-level model folder, e.g. "props", "foliage", "dungeon". */
  category: string;
  /** Human label derived from the file name. */
  label: string;
  /** Public URL of the GLB, e.g. "/models/props/well.glb". */
  path: string;
}
`;

const body =
  `export const ASSET_CATALOG: readonly AssetEntry[] = ${JSON.stringify(entries, null, 2)};\n\n` +
  `export const ASSET_CATEGORIES: readonly string[] = ${JSON.stringify(Object.keys(byCat).sort(), null, 2)};\n\n` +
  `const BY_ID = new Map(ASSET_CATALOG.map((a) => [a.id, a]));\n` +
  `export function assetById(id: string): AssetEntry | undefined {\n  return BY_ID.get(id);\n}\n`;

writeFileSync(outFile, `${header}\n${body}`);
console.log(
  `Wrote ${outFile} with ${entries.length} assets across ${Object.keys(byCat).length} categories.`,
);
for (const [cat, ids] of Object.entries(byCat).sort()) console.log(`  ${cat}: ${ids.length}`);
