// Release-fill worklist generator.
//
// A DATA-ONLY, no-LLM, no-network tool the maintainer runs before a release to
// turn the registry's `pending` slice into a per-language fill delta. It reads
// the generated registry (src/ui/i18n.status.json - gitignored, regenerated by
// pretest / `npm run i18n:gen`), the nested `en` source, the
// flat overlays, the three matcher DICTs, and the locked-terms glossary
// (scripts/i18n_glossary.json), and writes one batch per language under
// docs/i18n-scaling/worklist/ (gitignored - a generated artifact, never
// committed). It performs NO translation: it produces the delta a human or a
// separate model run consumes.
//
// Each auto-fillable entry is { scope, key, english, placeholders, siblings }:
//   - scope/key  the registry composite (`main` = en leaves; sim/server/admin =
//                the matcher DICTs). main keys are filled in the matching
//                src/ui/i18n.locales/<lang>.ts overlay; DICT keys in their DICT.
//   - english    the resolved English source string.
//   - placeholders  the `{name}` tokens it contains (via the SAME helper the
//                scanner uses, scripts/i18n_hash.mjs) so a filled value can be
//                placeholder-parity-checked.
//   - siblings   a few neighbouring keys' English values for translation context.
//
// PROSE is blocked-by-default (RFC 9.5): quest narratives, class/ability/item/
// mob/npc/zone/dungeon names + class lore + SEO marketing go in a SEPARATE
// `humanRequired` section and are NEVER placed in `autoFillable`. Anything not
// positively recognised as mechanical UI chrome also defaults to humanRequired.
// A bot consuming a batch can only ever reach `autoFillable`. (CJK talent names,
// the third named blocked category, live in src/ui/talent_i18n.ts - a separate
// function-valued channel that is NOT a registry key, so it is structurally
// unreachable by this tool; nothing to segregate here.)
//
// Determinism (load-bearing): output is a PURE function of the registry + source
// + glossary. Languages iterate in the registry's locale order; entries sort by
// (scope rank, key); glossary terms by (category order, key). Re-running on an
// unchanged repo is a zero-write no-op (content-hash cached via the manifest's
// `inputHash`); even without the cache the bytes would be identical.
//
// Zero runtime deps; bundles the TS source with esbuild (same pattern as
// scripts/i18n_scan.mjs / i18n_build.mjs). No Date.now / Math.random / network.
//
// Usage:
//   node scripts/i18n_fill_worklist.mjs            all 13 non-en locales
//   node scripts/i18n_fill_worklist.mjs --lang de_DE,fr_FR   a subset

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import * as esbuild from 'esbuild';
import { flatten } from './i18n_flatten.mjs';
import { contentHash, placeholdersOf } from './i18n_hash.mjs';

const root = process.cwd();
const REGISTRY_PATH = path.join(root, 'src/ui/i18n.status.json');
const GLOSSARY_PATH = path.join(root, 'scripts/i18n_glossary.json');
const OUT_DIR = path.join(root, 'docs/i18n-scaling/worklist');

// Bump if the emitted batch/manifest shape changes (invalidates the cache).
const FORMAT_VERSION = 1;
const MAX_SIBLINGS = 6;

// Mirror of scripts/i18n_scan.mjs / i18n_build.mjs. Dialect locales resolve a key
// they omit through their base, then English. Kept in lockstep with the
// scanner by hand; the worklist round-trip test would surface a divergence.
const DIALECT_BASE = { es_ES: 'es', fr_CA: 'fr_FR', en_CA: 'en' };
const SCOPE_RANK = { main: 0, sim: 1, server: 2, admin: 3 };

const isPresent = (v) => typeof v === 'string' && v.trim().length > 0;

// ---------------------------------------------------------------------------
// Classification policy: blocked-by-default (RFC 9.5).
// ---------------------------------------------------------------------------
// PROSE (human-required, NEVER auto-filled): all content proper nouns + narrative.
const PROSE_MAIN_PREFIXES = [
  'entities.', // quest narratives + ability/item/mob/npc/zone/dungeon names & lore
  'classes.', // the 9 class names (and their aria wrappers)
  'classDetails.lore.', // class lore narrative
  'seo.', // marketing copy + the embedded brand name
];
// MECHANICAL UI CHROME (a bot may auto-fill): short functional labels/messages.
// `classDetails.` is chrome EXCEPT `classDetails.lore.` (caught as prose first).
const CHROME_MAIN_PREFIXES = [
  'a11y.',
  'abilityUi.',
  'auth.',
  'character.',
  'classDetails.',
  'controls.',
  'deleteCharacter.',
  'download.',
  'entryGuard.',
  'errors.',
  'footer.',
  'game.',
  'highscores.',
  'hud.',
  'hudChrome.',
  'itemUi.',
  'loading.',
  'meta.',
  'mobilePreflight.',
  'mode.',
  'nav.',
  'questUi.',
  'realm.',
  'realmTypes.',
  'serverUnavailable.',
  'stats.',
];
// DICT scopes (sim/server/admin) are system / operator UI chrome, with one
// carve-out: the sim scope also carries boss dialogue and lore lines
// (dialogue.*, lore.*), which are narrative and route to humanRequired like
// the main scope's prose (Masterwrought Phase 19F: since the registry reads
// per-locale source presence, sim rows reach this tool). The admin dashboard
// is in scope (operators are users); the cognate backstops there are already
// `blocked` (not `pending`), so they never reach this tool.
const CHROME_DICT_SCOPES = new Set(['sim', 'server', 'admin']);
const PROSE_SIM_PREFIXES = ['dialogue.', 'lore.'];

function isProse(scope, key) {
  if (scope === 'sim') return PROSE_SIM_PREFIXES.some((p) => key.startsWith(p));
  if (scope !== 'main') return false;
  return PROSE_MAIN_PREFIXES.some((p) => key.startsWith(p));
}
function isChrome(scope, key) {
  if (CHROME_DICT_SCOPES.has(scope)) return true;
  if (scope === 'main') return CHROME_MAIN_PREFIXES.some((p) => key.startsWith(p));
  return false;
}

// Returns { fillable, reason }. Order matters: prose is checked BEFORE chrome so
// `classDetails.lore.*` cannot slip in via the `classDetails.` chrome prefix, and
// anything unrecognised defaults to human-required (blocked-by-default).
export function classify(scope, key) {
  if (isProse(scope, key)) {
    return {
      fillable: false,
      reason: 'prose: human-required (content proper noun / narrative; never auto-filled)',
    };
  }
  if (isChrome(scope, key)) return { fillable: true, reason: null };
  return {
    fillable: false,
    reason:
      'unclassified: human-required (blocked-by-default; add the namespace to CHROME_*_PREFIXES once confirmed mechanical chrome)',
  };
}

// ---------------------------------------------------------------------------
// Pure helpers (importable by tests; no I/O, no esbuild).
// ---------------------------------------------------------------------------

// `*` matches exactly one dotted segment; everything else is literal.
export function patternToRegExp(pattern) {
  const body = pattern
    .split('.')
    .map((seg) => (seg === '*' ? '[^.]+' : seg.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')))
    .join('\\.');
  return new RegExp(`^${body}$`);
}

// Up to MAX_SIBLINGS neighbouring keys (excluding `key`) that share `key`'s
// parent namespace; if the parent is a lone child, widen to the grandparent.
// A contiguous window centred on the key's sorted position keeps it deterministic.
export function siblingKeys(key, scopeKeysSorted, max = MAX_SIBLINGS) {
  const prefixes = [];
  const lastDot = key.lastIndexOf('.');
  if (lastDot >= 0) {
    prefixes.push(key.slice(0, lastDot + 1));
    const gpDot = key.slice(0, lastDot).lastIndexOf('.');
    if (gpDot >= 0) prefixes.push(key.slice(0, gpDot + 1));
  }
  for (const prefix of prefixes) {
    const family = scopeKeysSorted.filter((k) => k === key || k.startsWith(prefix));
    if (family.length <= 1) continue;
    const idx = family.indexOf(key);
    let start = Math.max(0, idx - Math.floor(max / 2));
    const end = Math.min(family.length, start + max + 1);
    start = Math.max(0, end - (max + 1));
    return family
      .slice(start, end)
      .filter((k) => k !== key)
      .slice(0, max);
  }
  return [];
}

// Established localized value for a (main-scope) key: own overlay, else dialect
// base overlay, else English. Mirrors scripts/i18n_build.mjs resolution.
function resolveLocaleValue(lang, key, enFlat, overlays) {
  const own = overlays[lang];
  if (own && isPresent(own[key])) return own[key];
  const base = DIALECT_BASE[lang];
  if (base && base !== 'en') {
    const b = overlays[base];
    if (b && isPresent(b[key])) return b[key];
  }
  return enFlat[key];
}

// Expand the glossary's key patterns against the en leaf set into a flat,
// deterministically-ordered term list (category order, then key).
export function expandGlossaryTerms(glossarySrc, enKeysSorted) {
  const terms = [];
  const cats = glossarySrc.categories || {};
  for (const category of Object.keys(cats)) {
    const patterns = cats[category].keyPatterns || [];
    const matched = new Set();
    for (const pat of patterns) {
      const re = patternToRegExp(pat);
      for (const k of enKeysSorted) if (re.test(k)) matched.add(k);
    }
    for (const key of [...matched].sort()) terms.push({ category, key });
  }
  return terms;
}

function sortEntries(a, b) {
  return SCOPE_RANK[a.scope] - SCOPE_RANK[b.scope] || (a.key < b.key ? -1 : a.key > b.key ? 1 : 0);
}

// Belt-and-suspenders stopping-rule enforcement: a prose key must never appear in
// autoFillable. classify() already guarantees this (prose is blocked-by-default);
// this re-check throws if a future classification bug ever lets one through.
// Exported so a test can prove the throw bites independently of the (correct)
// classifier - constructing an autoFillable list with a prose key must throw.
export function assertAutoFillableHasNoProse(autoFillable) {
  for (const e of autoFillable) {
    if (isProse(e.scope, e.key)) {
      throw new Error(
        `i18n:worklist: prose key leaked into autoFillable (${e.scope}:${e.key}); classification is unsound`,
      );
    }
  }
}

// Pure assembly core (importable by tests; no fs, no esbuild, no process state).
// Given the loaded registry + flattened en + DICT English + overlays + glossary,
// produce the exact file entries, manifest, and inputHash that main() serializes.
// Extracted so a fixture-driven test can prove (1) the output is byte-stable /
// deterministic (same inputs -> identical fileEntries + inputHash; a changed
// English value moves the hash) and (2) a pending prose key routes to humanRequired
// and never to autoFillable - without running the CLI or esbuild.
export function buildWorklistOutputs({
  registry,
  enFlat,
  dictEn,
  overlays,
  glossarySrc,
  targetLocales,
  scope,
}) {
  // English source for a registry composite, by scope (mirrors main()).
  const englishOf = (s, key) => (s === 'main' ? enFlat[key] : dictEn[s] && dictEn[s][key]);
  // Sorted key universe per scope, for sibling lookup (mirrors main()).
  const scopeKeysSorted = {
    main: Object.keys(enFlat).sort(),
    sim: Object.keys(dictEn.sim).sort(),
    server: Object.keys(dictEn.server).sort(),
    admin: Object.keys(dictEn.admin).sort(),
  };

  // Glossary terms (shared across every batch): expand patterns, attach English.
  const glossaryTerms = expandGlossaryTerms(glossarySrc, scopeKeysSorted.main).map((t) => ({
    category: t.category,
    key: t.key,
    english: enFlat[t.key],
  }));
  const glossaryVerbatim = glossarySrc.verbatim || [];

  // Build per-language batches.
  const batchObjs = new Map(); // lang -> batch object (or null if no pending)
  const perLanguage = {};
  let totalAuto = 0;
  let totalHuman = 0;
  for (const lang of targetLocales) {
    const autoFillable = [];
    const humanRequired = [];
    for (const [composite, row] of Object.entries(registry.keys)) {
      if (row.locales[lang] && row.locales[lang].state === 'pending') {
        const s = row.scope;
        const key = composite.slice(s.length + 1);
        const english = englishOf(s, key);
        const placeholders = placeholdersOf(english);
        const { fillable, reason } = classify(s, key);
        if (fillable) {
          const siblings = siblingKeys(key, scopeKeysSorted[s]).map((sk) => ({
            key: sk,
            english: englishOf(s, sk),
          }));
          autoFillable.push({ scope: s, key, english, placeholders, siblings });
        } else {
          humanRequired.push({ scope: s, key, english, placeholders, reason });
        }
      }
    }
    autoFillable.sort(sortEntries);
    humanRequired.sort(sortEntries);
    perLanguage[lang] = { autoFillable: autoFillable.length, humanRequired: humanRequired.length };
    totalAuto += autoFillable.length;
    totalHuman += humanRequired.length;

    // Belt-and-suspenders enforcement of the stopping rule: no prose in autoFillable.
    assertAutoFillableHasNoProse(autoFillable);

    if (autoFillable.length === 0 && humanRequired.length === 0) {
      batchObjs.set(lang, null);
      continue;
    }
    // Resolve each glossary term's established localized form for THIS language.
    const glossaryForLang = glossaryTerms.map((t) => ({
      category: t.category,
      key: t.key,
      english: t.english,
      localized: resolveLocaleValue(lang, t.key, enFlat, overlays),
    }));
    batchObjs.set(lang, {
      _doc:
        `Release-fill worklist for "${lang}". GENERATED by scripts/i18n_fill_worklist.mjs ` +
        `(npm run i18n:worklist) - do not hand-edit; regenerate. Fill each autoFillable ` +
        `entry into src/ui/i18n.locales/${lang}.ts (scope=main), ` +
        `src/admin/i18n.locales/${lang}.ts (scope=admin), or the matching DICT ` +
        `(scope=sim/server), preserving every placeholder; route humanRequired ` +
        `entries to a human translator (never auto-fill). Then run npm run i18n:scan.`,
      formatVersion: FORMAT_VERSION,
      language: lang,
      registryHashAlgo: registry.hashAlgo,
      counts: { autoFillable: autoFillable.length, humanRequired: humanRequired.length },
      glossary: { verbatim: glossaryVerbatim, terms: glossaryForLang },
      autoFillable,
      humanRequired,
    });
  }

  // Assemble the output file set (excluding inputHash, which is computed over it).
  const langsWithWork = targetLocales.filter((l) => batchObjs.get(l) !== null);
  const fileEntries = []; // [relName, contentObj]
  for (const lang of langsWithWork) fileEntries.push([`${lang}.json`, batchObjs.get(lang)]);

  const manifestBase = {
    _doc:
      'GENERATED by scripts/i18n_fill_worklist.mjs (npm run i18n:worklist) - do not hand-edit. ' +
      'This directory is gitignored: the worklist is a regenerable release-fill artifact, not committed. ' +
      'Per-language batches ship the locked-terms glossary (scripts/i18n_glossary.json) and split pending ' +
      'keys into autoFillable (mechanical UI chrome) and humanRequired (prose: blocked-by-default).',
    formatVersion: FORMAT_VERSION,
    generator: 'scripts/i18n_fill_worklist.mjs',
    registryHashAlgo: registry.hashAlgo,
    scope,
    totals: {
      languages: targetLocales.length,
      languagesWithWork: langsWithWork.length,
      pending: totalAuto + totalHuman,
      autoFillable: totalAuto,
      humanRequired: totalHuman,
    },
    perLanguage,
  };

  // inputHash: sha256 over the canonical serialization of every batch + the
  // manifest-without-its-own-hash + the format version. Pure function of inputs.
  const canonical = JSON.stringify({
    formatVersion: FORMAT_VERSION,
    manifest: manifestBase,
    batches: fileEntries.map(([name, obj]) => [name, obj]),
  });
  const inputHash = createHash('sha256').update(canonical, 'utf8').digest('hex').slice(0, 16);
  const manifest = { ...manifestBase, inputHash };

  return {
    fileEntries,
    manifest,
    inputHash,
    totalAuto,
    totalHuman,
    perLanguage,
    langsWithWork,
    batchObjs,
  };
}

// ---------------------------------------------------------------------------
// Source loading (mirrors scripts/i18n_scan.mjs loadSources; esbuild -> data URL).
// ---------------------------------------------------------------------------
function sourceModule(lang) {
  return lang === 'en' ? './src/ui/i18n.catalog' : `./src/ui/i18n.locales/${lang}`;
}

async function loadSources(nonEn) {
  const lines = [];
  lines.push(`export { en } from '${sourceModule('en')}';`);
  for (const lang of nonEn) lines.push(`export { ${lang} } from '${sourceModule(lang)}';`);
  lines.push("export { DICT as serverDICT } from './src/ui/server_i18n';");
  lines.push("export { DICT as simDICT } from './src/ui/sim_i18n';");
  // Admin reads its SPARSE source en base (mirrors scripts/i18n_scan.mjs), not the
  // dense runtime/resolved table - the worklist only needs the English source.
  lines.push("export { en as adminEn } from './src/admin/i18n.en';");
  const build = await esbuild.build({
    stdin: {
      contents: lines.join('\n'),
      resolveDir: root,
      sourcefile: 'i18n-worklist-entry.ts',
      loader: 'ts',
    },
    bundle: true,
    platform: 'node',
    format: 'esm',
    write: false,
    logLevel: 'silent',
  });
  const dataUrl = `data:text/javascript;base64,${Buffer.from(build.outputFiles[0].text).toString('base64')}`;
  const mod = await import(dataUrl);
  const overlays = {};
  for (const lang of nonEn) overlays[lang] = mod[lang];
  return {
    en: mod.en,
    overlays,
    serverDICT: mod.serverDICT,
    simDICT: mod.simDICT,
    adminEn: mod.adminEn,
  };
}

// ---------------------------------------------------------------------------
// File output with content-hash cache (no-op on an unchanged repo).
// ---------------------------------------------------------------------------
function writeOutputs(outputs) {
  const existing = existsSync(OUT_DIR)
    ? readdirSync(OUT_DIR)
        .filter((f) => f.endsWith('.json'))
        .map((f) => path.join(OUT_DIR, f))
    : [];
  const targets = new Set(outputs.keys());
  const allPresentAndEqual = [...outputs].every(
    ([p, c]) => existsSync(p) && readFileSync(p, 'utf8') === c,
  );
  const noStale = existing.every((p) => targets.has(p));
  if (allPresentAndEqual && noStale) return { wrote: 0, deleted: 0, hit: true };

  mkdirSync(OUT_DIR, { recursive: true });
  let wrote = 0;
  for (const [p, c] of outputs) {
    if (!existsSync(p) || readFileSync(p, 'utf8') !== c) {
      writeFileSync(p, c);
      wrote++;
    }
  }
  let deleted = 0;
  for (const p of existing) {
    if (!targets.has(p)) {
      rmSync(p);
      deleted++;
    }
  }
  return { wrote, deleted, hit: false };
}

function parseArgs(argv) {
  let langFilter = null;
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--lang') langFilter = argv[++i];
    else if (argv[i].startsWith('--lang=')) langFilter = argv[i].slice('--lang='.length);
  }
  return {
    langFilter: langFilter
      ? langFilter
          .split(',')
          .map((s) => s.trim())
          .filter(Boolean)
      : null,
  };
}

// ---------------------------------------------------------------------------
async function main() {
  const { langFilter } = parseArgs(process.argv.slice(2));

  const registry = JSON.parse(readFileSync(REGISTRY_PATH, 'utf8'));
  const glossarySrc = JSON.parse(readFileSync(GLOSSARY_PATH, 'utf8'));
  const allLocales = registry.locales; // 13 non-en, registry order

  if (langFilter) {
    const unknown = langFilter.filter((l) => !allLocales.includes(l));
    if (unknown.length) {
      console.error(
        `i18n:worklist: unknown locale(s): ${unknown.join(', ')}. Known: ${allLocales.join(', ')}`,
      );
      process.exit(1);
    }
  }
  const targetLocales = langFilter ? allLocales.filter((l) => langFilter.includes(l)) : allLocales;

  const { en, overlays, serverDICT, simDICT, adminEn } = await loadSources(allLocales);
  const enFlat = flatten(en);
  const dictEn = { sim: simDICT.en, server: serverDICT.en, admin: adminEn };

  // English source for a registry composite, by scope (used by the staleness guard).
  const englishOf = (scope, key) =>
    scope === 'main' ? enFlat[key] : dictEn[scope] && dictEn[scope][key];

  // Staleness guard: the worklist must reflect a FRESH registry. Verify every
  // registry key still resolves to source with the recorded enHash, and that no
  // source key is missing from the registry. If anything drifted, refuse to run
  // (a stale registry would mislabel which keys are pending). The user re-scans.
  const stale = [];
  for (const [composite, row] of Object.entries(registry.keys)) {
    const key = composite.slice(row.scope.length + 1);
    const eng = englishOf(row.scope, key);
    if (!isPresent(eng)) {
      stale.push(`${composite} (no source string; renamed/removed in source?)`);
      continue;
    }
    if (contentHash(eng, placeholdersOf(eng)) !== row.enHash) {
      stale.push(`${composite} (enHash drifted; English changed since the last scan)`);
    }
  }
  for (const k of Object.keys(enFlat))
    if (!registry.keys[`main:${k}`]) stale.push(`main:${k} (in en, absent from registry)`);
  for (const scope of ['sim', 'server', 'admin']) {
    for (const k of Object.keys(dictEn[scope]))
      if (!registry.keys[`${scope}:${k}`])
        stale.push(`${scope}:${k} (in DICT, absent from registry)`);
  }
  if (stale.length) {
    console.error(
      `i18n:worklist: the registry (src/ui/i18n.status.json) is STALE relative to source ` +
        `(${stale.length} drift(s)). Run \`npm run i18n:scan\` first, then re-run the worklist.\n` +
        stale
          .slice(0, 10)
          .map((s) => `  - ${s}`)
          .join('\n') +
        (stale.length > 10 ? `\n  ... and ${stale.length - 10} more` : ''),
    );
    process.exit(1);
  }

  // Assemble every batch + manifest + inputHash from the loaded data (pure; no I/O).
  const scope = langFilter ? { lang: targetLocales } : 'all-locales';
  const { fileEntries, manifest, inputHash, totalAuto, totalHuman, langsWithWork } =
    buildWorklistOutputs({
      registry,
      enFlat,
      dictEn,
      overlays,
      glossarySrc,
      targetLocales,
      scope,
    });

  const outputs = new Map();
  outputs.set(path.join(OUT_DIR, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
  for (const [name, obj] of fileEntries)
    outputs.set(path.join(OUT_DIR, name), JSON.stringify(obj, null, 2) + '\n');

  const { wrote, deleted, hit } = writeOutputs(outputs);
  const rel = path.relative(root, OUT_DIR);
  if (hit) {
    console.log(
      `i18n:worklist: no pending changes (cache hit ${inputHash}); wrote nothing. ` +
        `pending=${totalAuto + totalHuman} (auto=${totalAuto} human=${totalHuman}) across ${targetLocales.length} locale(s).`,
    );
  } else if (totalAuto + totalHuman === 0) {
    console.log(
      `i18n:worklist: 0 pending translations across ${targetLocales.length} locale(s); ${rel}/manifest.json written (no batches). [${inputHash}]`,
    );
  } else {
    console.log(
      `i18n:worklist: ${totalAuto + totalHuman} pending (auto=${totalAuto} human=${totalHuman}) ` +
        `in ${langsWithWork.length}/${targetLocales.length} locale(s) -> ${rel}/ ` +
        `(wrote ${wrote}, removed ${deleted} stale) [${inputHash}]`,
    );
  }
}

// Run only when invoked as a CLI (so tests can import the pure helpers above).
const invokedDirectly = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (invokedDirectly) await main();
