// Build the i18n status registry src/ui/i18n.status.json.
//
// A no-LLM, no-network scanner that records, per key per locale, whether a real
// translation exists. It walks the full key universe - every `en` leaf, plus the
// matcher DICT keys (sim_i18n + server_i18n) and the admin keys (read sparsely
// from the admin en base + overlays) - and for
// each (key, locale) emits one of three states:
//
//   translated  the locale provides a real translation. Stores `srcHash` (a hash
//               of the English source text + its sorted placeholder set) and a
//               `by` field (human | agent).
//   blocked     a deliberate English backstop, carrying a required human reason.
//               Seeded from the two hand-maintained allow-lists that used to live
//               in tests/localization_fixes.test.ts (scripts/i18n_blocked_seed.mjs).
//   pending     untranslated, or stale (the recorded English source drifted from
//               the current one). Non-empty for the game, admin and sim scopes:
//               a locale that omits an overlay key, or whose sim_i18n source
//               block omits a matcher key, is pending - the resolved table (or
//               the sim DICT's English spread) fills it for non-release;
//               release is gated. The server scope's tables are authored dense.
//
// Determinism / reproducibility (the load-bearing property): the registry is a
// PURE function of the current source files plus the static seeds - it does NOT
// read its own previous output. Key ordering is fixed (scope rank, then key),
// locale ordering is fixed (the LOCALES list), and the hash is deterministic
// (scripts/i18n_hash.mjs). Two runs on the same inputs are byte-identical. The full
// i18n.status.json is gitignored (build/test-only, ~4.7 MB; regenerated by pretest
// and the CI i18n:gen step), so its reproducibility is checked by the
// assertDeterministic double-generation gate (tests/helpers/i18n_determinism.ts)
// rather than a committed-bytes `git diff`. The i18n.status.summary.json (counts +
// per-locale rollup + universeHash, no per-key bodies) is likewise generated and
// gitignored; CI posts its counts to the job summary as the audit trail.
//
// On staleness: because srcHash is recomputed from the current English each run,
// it always equals the per-key enHash for now, so the translated/stale
// distinction is dormant (no key is stale while everything is dense and `en` is
// unchanged). The srcHash + enHash fields are recorded now so the staleness
// comparison (srcHash !== enHash -> pending) becomes live once
// sparse overlays and the fill pipeline persist translation-time hashes.
//
// Zero runtime deps; bundles the TS source with esbuild (same pattern as
// scripts/i18n_build.mjs / i18n_resolved_hash.mjs). No Date.now / Math.random.
//
// Usage:
//   node scripts/i18n_scan.mjs   (re)generate src/ui/i18n.status.json + i18n.status.summary.json
//   I18N_OUT_DIR=... node scripts/i18n_scan.mjs   emit both into a custom directory

import { createHash } from 'node:crypto';
import { mkdirSync, renameSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import * as esbuild from 'esbuild';
import { COPIED_ALLOW_IDS, V07_SLASH } from './i18n_blocked_seed.mjs';
import { flatten } from './i18n_flatten.mjs';
import { contentHash, PLACEHOLDER_RE, placeholdersOf } from './i18n_hash.mjs';
import { RETIRED_KEY_SET, RETIRED_REASON } from './i18n_retired_keys.mjs';

const root = process.cwd();
// I18N_OUT_DIR overrides the destination DIRECTORY for both emitted files (used by
// the determinism gate in tests/helpers/i18n_determinism.ts to double-generate into
// throwaway temp dirs without touching the committed artifacts); mirrors the same
// override in scripts/i18n_build.mjs / i18n_admin_build.mjs. The default keeps the
// committed src/ui location. Both the full status.json and the small summary alongside
// it are gitignored (regenerated by pretest / the CI i18n:gen step).
const OUT_DIR = process.env.I18N_OUT_DIR
  ? path.resolve(root, process.env.I18N_OUT_DIR)
  : path.join(root, 'src/ui');
const OUT_PATH = path.join(OUT_DIR, 'i18n.status.json');
const SUMMARY_PATH = path.join(OUT_DIR, 'i18n.status.summary.json');

// Write-then-rename so no concurrent reader ever observes a half-written
// artifact: the test suite regenerates these files into the real tree while
// parallel workers run `git status` porcelain assertions, and a direct
// multi-megabyte writeFileSync leaves a mid-write window where a tracked,
// otherwise byte-identical file reads as modified. Same-directory rename is
// atomic on POSIX.
function atomicWriteFileSync(filePath, contents) {
  const tmpPath = `${filePath}.tmp`;
  writeFileSync(tmpPath, contents);
  renameSync(tmpPath, filePath);
}

// The authoritative ordered locale set (mirrors scripts/i18n_build.mjs). `en` is
// the nested base; the rest are flat dotted-key overlays. The registry tracks the
// 13 NON-`en` locales per key (`en` is the authoritative source, never "pending").
const LOCALES = [
  'en',
  'es',
  'es_ES',
  'fr_FR',
  'fr_CA',
  'en_CA',
  'it_IT',
  'de_DE',
  'zh_CN',
  'zh_TW',
  'ko_KR',
  'ja_JP',
  'pt_BR',
  'ru_RU',
  'cs_CZ',
  'nl_NL',
  'pl_PL',
  'id_ID',
  'tr_TR',
  'sv_SE',
  'vi_VN',
  'da_DK',
];
const NON_EN = LOCALES.filter((l) => l !== 'en');

// Dialect locales resolve through a base locale: a key the dialect
// overlay omits falls through to the base overlay, then to English. So a dialect
// "provides" a key if its own overlay OR its base chain provides it. en_CA's base
// is `en` itself, so it provides every key (an English dialect intentionally
// shows English where it does not diverge). Mirror of i18n_build's DIALECT_BASE.
const DIALECT_BASE = { es_ES: 'es', fr_CA: 'fr_FR', en_CA: 'en' };

// The four key namespaces. `main` = the resolved-table en leaves; `sim`/`server`
// = the client matcher DICTs (sim_i18n / server_i18n); `admin` = the admin DICT.
// Each registry key is prefixed `<scope>:<dotted.key>`; the rank fixes emit order.
const SCOPE_RANK = { main: 0, sim: 1, server: 2, admin: 3 };

// A human-meaningful reason per cognate (blocked rows require one). Keyed by the
// stable part of the id so the seed stays short; falls back to a generic cognate
// note for the long tail of accepted borrowings.
function cognateReason(_scope, _locale, key) {
  if (key === 'who.statusCombat')
    return "'combat' is a real word in this locale and is identical to English.";
  if (key === 'who.statusOnline')
    return "'online' is the accepted borrowed term in this locale; identical to English.";
  if (key === 'detail.lengthHours')
    return "Numeric duration format ('{count} h') is identical across locales.";
  if (key === 'app.title') return 'Admin brand title is not translated.';
  if (key === 'class.paladin')
    return "'Paladin' is the canonical class name in this locale (cognate).";
  if (key === 'chatMod.status')
    return "'Status' is the accepted term in this locale and is identical to English (matches detail.status).";
  if (key === 'chatFilter.escalationTitle')
    return "'Escalation' is a borrowed term already used across this locale's admin strings.";
  if (key === 'accounts.badgeStreamer' || key === 'detail.streamerLabel')
    return "'Streamer' is the borrowed term this locale actually uses for the role; the native calque is not what an operator would say.";
  return 'Accepted cognate or borrowed term that is legitimately identical to English.';
}

// Reason attached to every blockedSource (v0.7 slash-command) entry.
const V07_SLASH_REASON =
  'v0.7 in-game slash-command / diagnostic surface; ships English as a documented backstop pending a dedicated localization pass (follow-up).';

function sourceModule(lang) {
  return lang === 'en' ? './src/ui/i18n.catalog' : `./src/ui/i18n.locales/${lang}`;
}

// Bundle the source locale objects + the matcher DICTs + the admin source via a
// tiny stub and import the result. Same esbuild-to-data-URL pattern as
// i18n_build.mjs; none of this touches the generated registry, so there is no
// self-dependency. The admin scope reads the SPARSE source (i18n.en + the flat
// overlays), NOT the dense resolved table or the runtime src/admin/i18n.ts, so an
// admin key a locale omits naturally yields `pending` exactly like a main key.
async function loadSources() {
  const lines = [];
  lines.push(`export { en } from '${sourceModule('en')}';`);
  for (const lang of NON_EN) lines.push(`export { ${lang} } from '${sourceModule(lang)}';`);
  lines.push("export { DICT as serverDICT } from './src/ui/server_i18n';");
  lines.push("export { DICT as simDICT, simDictProvidedKeys } from './src/ui/sim_i18n';");
  lines.push("export { en as adminEn } from './src/admin/i18n.en';");
  for (const lang of NON_EN)
    lines.push(`export { ${lang} as admin_${lang} } from './src/admin/i18n.locales/${lang}';`);
  const build = await esbuild.build({
    stdin: {
      contents: lines.join('\n'),
      resolveDir: root,
      sourcefile: 'i18n-scan-entry.ts',
      loader: 'ts',
    },
    bundle: true,
    platform: 'node',
    format: 'esm',
    write: false,
    logLevel: 'silent',
  });
  const dataUrl = `data:text/javascript;base64,${Buffer.from(build.outputFiles[0].text).toString('base64')}`;
  const mod = await import(dataUrl);
  const overlays = {};
  for (const lang of NON_EN) overlays[lang] = mod[lang];
  const adminOverlays = {};
  for (const lang of NON_EN) adminOverlays[lang] = mod[`admin_${lang}`];
  return {
    en: mod.en,
    overlays,
    serverDICT: mod.serverDICT,
    simDICT: mod.simDICT,
    simDictProvidedKeys: mod.simDictProvidedKeys,
    adminEn: mod.adminEn,
    adminOverlays,
  };
}

const isPresent = (v) => typeof v === 'string' && v.trim().length > 0;

async function main() {
  const { en, overlays, serverDICT, simDICT, simDictProvidedKeys, adminEn, adminOverlays } =
    await loadSources();
  const enFlat = flatten(en); // dotted key -> English string

  // Per-key per-locale blocked seed: "scope:key" -> Map(locale -> reason).
  const blockedRows = new Map();
  for (const id of COPIED_ALLOW_IDS) {
    const [scope, locale, key] = id.split('::');
    const ck = `${scope}:${key}`;
    if (!blockedRows.has(ck)) blockedRows.set(ck, new Map());
    blockedRows.get(ck).set(locale, cognateReason(scope, locale, key));
  }

  // For the main scope, precompute the set of keys each locale "provides"
  // (dialect-aware), so a future sparse overlay naturally yields `pending`.
  const providedByLang = {};
  for (const lang of NON_EN) {
    const provided = new Set();
    const own = overlays[lang] || {};
    for (const k of Object.keys(own)) if (isPresent(own[k])) provided.add(k);
    const base = DIALECT_BASE[lang];
    if (base === 'en') {
      // English dialect: inherits every English leaf where it does not diverge.
      for (const k of Object.keys(enFlat)) provided.add(k);
    } else if (base) {
      const baseOverlay = overlays[base] || {};
      for (const k of Object.keys(baseOverlay)) if (isPresent(baseOverlay[k])) provided.add(k);
    }
    providedByLang[lang] = provided;
  }

  const keyEntries = [];

  // main scope: en leaves. The only blocked rows here are the RETIRED keys
  // (scripts/i18n_retired_keys.mjs): a key no page renders is never a fill
  // work item, so its unprovided locale rows carry the retired reason instead
  // of `pending` (a provided row stays `translated`: the reviewed prose is
  // real and kept). Cognate blocked rows still live in server/admin only.
  for (const key of Object.keys(enFlat)) {
    const enVal = enFlat[key];
    const ph = placeholdersOf(enVal);
    const enHash = contentHash(enVal, ph);
    const locales = {};
    for (const lang of NON_EN) {
      locales[lang] = providedByLang[lang].has(key)
        ? { state: 'translated', srcHash: enHash, by: 'human' }
        : RETIRED_KEY_SET.has(key)
          ? { state: 'blocked', reason: RETIRED_REASON }
          : { state: 'pending' };
    }
    keyEntries.push({
      composite: `main:${key}`,
      scope: 'main',
      key,
      enHash,
      placeholders: ph,
      locales,
    });
  }

  // DICT scopes: sim / server. Each is a DENSE flat Record<locale, Record<key,string>>,
  // but the two are dense for different reasons, and the difference decides what
  // "present" means. server_i18n's locale tables are AUTHORED dense (every locale
  // block spells every key), so presence in the assembled DICT is presence in
  // the source. sim_i18n's DICT is dense BY CONSTRUCTION: baseEnTable is spread
  // under every locale before the locale's own block, so a key the block never
  // filled still reads as present, in English. Reading the assembled sim DICT
  // therefore marked every sim key translated in every locale and the release
  // fill could never see a sim-scope row (Masterwrought Phase 19F, ruling
  // qr-19-sim-scope-pending-is-unreachable). The sim scope now reads the
  // per-locale SOURCE presence that src/ui/sim_i18n.ts exports as
  // simDictProvidedKeys, with the same English-dialect rule the main and admin
  // scopes apply (en_CA's base is en, so it provides every key); es_ES and
  // fr_CA carry their OWN sim blocks (the sim DICT has no dialect inheritance),
  // so they are read as themselves. `providedFor(lang)` returns the source set
  // for a scope that needs it; a scope without one keeps the assembled read.
  const addDictScope = (scope, dict, providedFor) => {
    for (const key of Object.keys(dict.en)) {
      const enVal = dict.en[key];
      const ph = placeholdersOf(enVal);
      const enHash = contentHash(enVal, ph);
      const blockedForKey = blockedRows.get(`${scope}:${key}`);
      const locales = {};
      for (const lang of NON_EN) {
        const reason = blockedForKey?.get(lang);
        if (reason !== undefined) {
          locales[lang] = { state: 'blocked', reason };
        } else {
          const present = providedFor
            ? DIALECT_BASE[lang] === 'en' || providedFor(lang).has(key)
            : isPresent(dict[lang]?.[key]);
          locales[lang] = present
            ? { state: 'translated', srcHash: enHash, by: 'human' }
            : { state: 'pending' };
        }
      }
      keyEntries.push({
        composite: `${scope}:${key}`,
        scope,
        key,
        enHash,
        placeholders: ph,
        locales,
      });
    }
  };
  const simProvided = new Map();
  addDictScope('sim', simDICT, (lang) => {
    let set = simProvided.get(lang);
    if (!set) {
      set = simDictProvidedKeys(lang);
      simProvided.set(lang, set);
    }
    return set;
  });
  addDictScope('server', serverDICT);

  // admin scope: a flat en base + SPARSE flat overlays. Unlike sim/server
  // it is dialect-aware and sparse-capable: a locale "provides" a key via its own
  // overlay or (for a dialect) its base chain, exactly like the main scope's
  // providedByLang - so an omitted admin key naturally yields `pending`. The blocked
  // seed still takes precedence (the admin cognate backstops).
  const addSparseScope = (scope, enMap, scopeOverlays) => {
    const enKeys = Object.keys(enMap);
    const provided = {};
    for (const lang of NON_EN) {
      const set = new Set();
      const own = scopeOverlays[lang] || {};
      for (const k of Object.keys(own)) if (isPresent(own[k])) set.add(k);
      const base = DIALECT_BASE[lang];
      if (base === 'en') {
        for (const k of enKeys) set.add(k); // English dialect inherits every key
      } else if (base) {
        const baseOverlay = scopeOverlays[base] || {};
        for (const k of Object.keys(baseOverlay)) if (isPresent(baseOverlay[k])) set.add(k);
      }
      provided[lang] = set;
    }
    for (const key of enKeys) {
      const enVal = enMap[key];
      const ph = placeholdersOf(enVal);
      const enHash = contentHash(enVal, ph);
      const blockedForKey = blockedRows.get(`${scope}:${key}`);
      const locales = {};
      for (const lang of NON_EN) {
        const reason = blockedForKey?.get(lang);
        if (reason !== undefined) {
          locales[lang] = { state: 'blocked', reason };
        } else {
          locales[lang] = provided[lang].has(key)
            ? { state: 'translated', srcHash: enHash, by: 'human' }
            : { state: 'pending' };
        }
      }
      keyEntries.push({
        composite: `${scope}:${key}`,
        scope,
        key,
        enHash,
        placeholders: ph,
        locales,
      });
    }
  };
  addSparseScope('admin', adminEn, adminOverlays);

  // Deterministic ordering: by scope rank, then by key path (codepoint order).
  keyEntries.sort(
    (a, b) =>
      SCOPE_RANK[a.scope] - SCOPE_RANK[b.scope] || (a.key < b.key ? -1 : a.key > b.key ? 1 : 0),
  );

  // Sanity: a blocked seed entry that points at a key not in the universe means
  // the seed has rotted (the DICT key was renamed/removed). Fail loud.
  const universe = new Set(keyEntries.map((e) => e.composite));
  for (const ck of blockedRows.keys()) {
    if (!universe.has(ck)) {
      throw new Error(
        `i18n scan: blocked seed key "${ck}" is not in the key universe (stale seed?)`,
      );
    }
  }

  let translated = 0,
    pending = 0,
    blocked = 0;
  for (const e of keyEntries) {
    for (const lang of NON_EN) {
      const s = e.locales[lang].state;
      if (s === 'translated') translated++;
      else if (s === 'pending') pending++;
      else if (s === 'blocked') blocked++;
    }
  }

  const blockedSource = V07_SLASH.slice()
    .sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
    .map((text) => ({ channel: 'sim', reason: V07_SLASH_REASON, text }));

  const registry = {
    _generated:
      'GENERATED by scripts/i18n_scan.mjs - do not edit by hand. Regenerate: npm run i18n:scan',
    version: 1,
    hashAlgo: 'sha256(enText + U+001F + sortedPlaceholders.join(U+001F)).slice(0,16)',
    placeholderRegex: PLACEHOLDER_RE.source,
    scopes: Object.keys(SCOPE_RANK),
    locales: NON_EN,
    counts: {
      keys: keyEntries.length,
      rows: keyEntries.length * NON_EN.length,
      translated,
      pending,
      blocked,
      blockedSource: blockedSource.length,
    },
    keys: {},
    blockedSource,
  };
  for (const e of keyEntries) {
    registry.keys[e.composite] = {
      scope: e.scope,
      enHash: e.enHash,
      placeholders: e.placeholders,
      locales: e.locales,
    };
  }

  const text = `${JSON.stringify(registry, null, 2)}\n`;
  mkdirSync(OUT_DIR, { recursive: true });
  atomicWriteFileSync(OUT_PATH, text);

  // A small audit summary alongside the (gitignored) full registry: the headline
  // counts, a per-locale state rollup, and a hash over the whole key universe
  // (composite + enHash + placeholders, in emit order). No per-key bodies, no
  // timestamps - a pure function of source, so it regenerates byte-identically and
  // is covered by the determinism gate. Gitignored like the full registry; CI posts
  // its counts to the job summary as the audit trail.
  const SEP = String.fromCharCode(0x1f);
  const universeHash = createHash('sha256')
    .update(
      keyEntries
        .map((e) => `${e.composite}${SEP}${e.enHash}${SEP}${e.placeholders.join(',')}`)
        .join('\n'),
      'utf8',
    )
    .digest('hex');
  const perLocale = {};
  for (const lang of NON_EN) perLocale[lang] = { translated: 0, pending: 0, blocked: 0 };
  for (const e of keyEntries) {
    for (const lang of NON_EN) perLocale[lang][e.locales[lang].state]++;
  }
  const summary = {
    _generated:
      'GENERATED by scripts/i18n_scan.mjs - do not edit by hand. Regenerate: npm run i18n:scan',
    version: 1,
    universeHash,
    scopes: Object.keys(SCOPE_RANK),
    locales: NON_EN,
    counts: registry.counts,
    perLocale,
  };
  const summaryText = `${JSON.stringify(summary, null, 2)}\n`;
  atomicWriteFileSync(SUMMARY_PATH, summaryText);

  console.log(
    `generated ${path.relative(root, OUT_PATH)} ` +
      `(${keyEntries.length} keys x ${NON_EN.length} locales; ` +
      `translated=${translated} blocked=${blocked} pending=${pending}; ` +
      `blockedSource=${blockedSource.length}; ${Buffer.byteLength(text, 'utf8')} bytes) ` +
      `+ ${path.relative(root, SUMMARY_PATH)} (${Buffer.byteLength(summaryText, 'utf8')} bytes)`,
  );
}

await main();
