// Crucible of the Last Spring raid loot: the item level 35 epic tier.
// Reviewed item-by-item in docs/prd/ignivar-raid-loot-items.md (numbers there
// and here come from one generator, so what was reviewed is what shipped) with
// the design rationale in docs/prd/ignivar-raid-loot.md.
//
// Item level: every gear piece here reads item level 35 = source 26 + the
// epic quality bump 6 + the raid bonus 3. The source index registers every id
// at IGNIVAR_RAID_LOOT_SOURCE_LEVEL with the raid flag (see item_level.ts):
// the boss mobs are level 20, so without the explicit registration the
// mob-loot block would price the drops at their kill level instead of the
// raid tier the plan sets. Stat lines are budget-exact per item_budget.ts
// (35 x slot mult x 0.7, largest-remainder normalized), pinned by
// tests/ignivar_loot.test.ts.
//
// Ratings ladder step (docs/prd/ignivar-raid-loot.md): armor pieces carry a
// 60-point primary and a 25-point secondary rating; jewelry, shields, and
// held offhands carry a single 25. Hit appears exactly where the plan's Hit
// program says: the elective waists at 60 and the physical neck/ring plus
// the spell-damage ring at 25.
//
// The five-piece sets are class-locked and carry `set:` tags; their
// ITEM_SETS entries (the 2/4-piece engine bonuses of
// docs/prd/ignivar-set-bonus-final.md) land in the follow-up change, and an
// unregistered set id folds to nothing everywhere by design.
//
// Sigils: 15 redemption tokens (5 tier slots x 3 balanced-mixed class
// groups, one mail + one leather + one cloth class each). Kind 'tool' and
// soulbound like heroic_mark, but deliberately NOT noDiscard: unlike the
// universal mark, a sigil is class-locked, and the loot path does not gate
// need/greed or FFA pickup on class, so a wrong-class looter must be able
// to destroy the token or it wedges a bag slot forever (soulbound blocks
// trade, mail, market, and sale). One sigil buys any one matching-slot set
// piece for the holder's class at the Crucible Quartermaster
// (CRUCIBLE_VENDOR_STOCK).

import type { ItemDef, NpcDef } from '../types';
import { CRUCIBLE_PATTERN_VENDOR_STOCK } from './crucible_collections';

// Source level the whole Ignivar raid loot table reads as in the item-level
// index: level-20 content two tiers above the five-man heroics, so epics land
// at item level 35 (26 + epic 6 + raid 3).
export const IGNIVAR_RAID_LOOT_SOURCE_LEVEL = 26;

// The 29 five-piece tier sets (145 pieces), redeemed from sigils.
export const IGNIVAR_SET_ITEMS: Record<string, ItemDef> = {
  // ---- Slagbreaker Battlegear ----
  slagbreaker_helmet: {
    id: 'slagbreaker_helmet',
    name: 'Slagbreaker Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 325, str: 14, sta: 7 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['warrior'],
    set: 'slagbreaker',
  },
  slagbreaker_shoulder: {
    id: 'slagbreaker_shoulder',
    name: 'Slagbreaker Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 290, str: 12, sta: 6 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['warrior'],
    set: 'slagbreaker',
  },
  slagbreaker_chest: {
    id: 'slagbreaker_chest',
    name: 'Slagbreaker Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 380, str: 17, sta: 8 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['warrior'],
    set: 'slagbreaker',
  },
  slagbreaker_gloves: {
    id: 'slagbreaker_gloves',
    name: 'Slagbreaker Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 270, str: 11, sta: 6 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['warrior'],
    set: 'slagbreaker',
  },
  slagbreaker_legs: {
    id: 'slagbreaker_legs',
    name: 'Slagbreaker Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 345, str: 15, sta: 7 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['warrior'],
    set: 'slagbreaker',
  },
  // ---- Emberfury Harness ----
  emberfury_helmet: {
    id: 'emberfury_helmet',
    name: 'Emberfury Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 325, str: 14, sta: 7 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['warrior'],
    set: 'emberfury',
  },
  emberfury_shoulder: {
    id: 'emberfury_shoulder',
    name: 'Emberfury Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 290, str: 12, sta: 6 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['warrior'],
    set: 'emberfury',
  },
  emberfury_chest: {
    id: 'emberfury_chest',
    name: 'Emberfury Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 380, str: 17, sta: 8 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['warrior'],
    set: 'emberfury',
  },
  emberfury_gloves: {
    id: 'emberfury_gloves',
    name: 'Emberfury Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 270, str: 11, sta: 6 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['warrior'],
    set: 'emberfury',
  },
  emberfury_legs: {
    id: 'emberfury_legs',
    name: 'Emberfury Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 345, str: 15, sta: 7 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['warrior'],
    set: 'emberfury',
  },
  // ---- Forgewall Aegis ----
  forgewall_helmet: {
    id: 'forgewall_helmet',
    name: 'Forgewall Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 325, str: 10, sta: 11 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['warrior'],
    set: 'forgewall',
  },
  forgewall_shoulder: {
    id: 'forgewall_shoulder',
    name: 'Forgewall Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 290, str: 8, sta: 10 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['warrior'],
    set: 'forgewall',
  },
  forgewall_chest: {
    id: 'forgewall_chest',
    name: 'Forgewall Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 380, str: 11, sta: 14 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['warrior'],
    set: 'forgewall',
  },
  forgewall_gloves: {
    id: 'forgewall_gloves',
    name: 'Forgewall Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 270, str: 8, sta: 9 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['warrior'],
    set: 'forgewall',
  },
  forgewall_legs: {
    id: 'forgewall_legs',
    name: 'Forgewall Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 345, str: 10, sta: 12 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['warrior'],
    set: 'forgewall',
  },
  // ---- Dawnforged Vestments ----
  dawnforged_helmet: {
    id: 'dawnforged_helmet',
    name: 'Dawnforged Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 325, int: 11, spi: 10 },
    healPower: 14,
    hasteRating: 60,
    critRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['paladin'],
    set: 'dawnforged',
  },
  dawnforged_shoulder: {
    id: 'dawnforged_shoulder',
    name: 'Dawnforged Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 290, int: 9, spi: 9 },
    healPower: 10,
    hasteRating: 60,
    critRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['paladin'],
    set: 'dawnforged',
  },
  dawnforged_chest: {
    id: 'dawnforged_chest',
    name: 'Dawnforged Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 380, int: 13, spi: 12 },
    healPower: 16,
    hasteRating: 60,
    critRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['paladin'],
    set: 'dawnforged',
  },
  dawnforged_gloves: {
    id: 'dawnforged_gloves',
    name: 'Dawnforged Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 270, int: 9, spi: 8 },
    healPower: 10,
    hasteRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['paladin'],
    set: 'dawnforged',
  },
  dawnforged_legs: {
    id: 'dawnforged_legs',
    name: 'Dawnforged Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 345, int: 11, spi: 11 },
    healPower: 14,
    hasteRating: 60,
    critRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['paladin'],
    set: 'dawnforged',
  },
  // ---- Oathpyre Bastion ----
  oathpyre_helmet: {
    id: 'oathpyre_helmet',
    name: 'Oathpyre Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 325, str: 10, sta: 11 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['paladin'],
    set: 'oathpyre',
  },
  oathpyre_shoulder: {
    id: 'oathpyre_shoulder',
    name: 'Oathpyre Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 290, str: 8, sta: 10 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['paladin'],
    set: 'oathpyre',
  },
  oathpyre_chest: {
    id: 'oathpyre_chest',
    name: 'Oathpyre Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 380, str: 11, sta: 14 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['paladin'],
    set: 'oathpyre',
  },
  oathpyre_gloves: {
    id: 'oathpyre_gloves',
    name: 'Oathpyre Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 270, str: 8, sta: 9 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['paladin'],
    set: 'oathpyre',
  },
  oathpyre_legs: {
    id: 'oathpyre_legs',
    name: 'Oathpyre Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 345, str: 10, sta: 12 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['paladin'],
    set: 'oathpyre',
  },
  // ---- Zealfire Warplate ----
  zealfire_helmet: {
    id: 'zealfire_helmet',
    name: 'Zealfire Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 325, str: 14, sta: 7 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['paladin'],
    set: 'zealfire',
  },
  zealfire_shoulder: {
    id: 'zealfire_shoulder',
    name: 'Zealfire Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 290, str: 12, sta: 6 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['paladin'],
    set: 'zealfire',
  },
  zealfire_chest: {
    id: 'zealfire_chest',
    name: 'Zealfire Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 380, str: 17, sta: 8 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['paladin'],
    set: 'zealfire',
  },
  zealfire_gloves: {
    id: 'zealfire_gloves',
    name: 'Zealfire Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 270, str: 11, sta: 6 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['paladin'],
    set: 'zealfire',
  },
  zealfire_legs: {
    id: 'zealfire_legs',
    name: 'Zealfire Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 345, str: 15, sta: 7 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['paladin'],
    set: 'zealfire',
  },
  // ---- Packlord's Emberhide ----
  packlord_emberhide_helmet: {
    id: 'packlord_emberhide_helmet',
    name: "Packlord's Cowl",
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 185, agi: 14, sta: 7 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['hunter'],
    set: 'packlord_emberhide',
  },
  packlord_emberhide_shoulder: {
    id: 'packlord_emberhide_shoulder',
    name: "Packlord's Spaulders",
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 165, agi: 12, sta: 6 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['hunter'],
    set: 'packlord_emberhide',
  },
  packlord_emberhide_chest: {
    id: 'packlord_emberhide_chest',
    name: "Packlord's Tunic",
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 215, agi: 17, sta: 8 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['hunter'],
    set: 'packlord_emberhide',
  },
  packlord_emberhide_gloves: {
    id: 'packlord_emberhide_gloves',
    name: "Packlord's Grips",
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 150, agi: 11, sta: 6 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['hunter'],
    set: 'packlord_emberhide',
  },
  packlord_emberhide_legs: {
    id: 'packlord_emberhide_legs',
    name: "Packlord's Breeches",
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 195, agi: 15, sta: 7 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['hunter'],
    set: 'packlord_emberhide',
  },
  // ---- Coldsight Trackers ----
  coldsight_trackers_helmet: {
    id: 'coldsight_trackers_helmet',
    name: 'Coldsight Cowl',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 185, agi: 14, sta: 7 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['hunter'],
    set: 'coldsight_trackers',
  },
  coldsight_trackers_shoulder: {
    id: 'coldsight_trackers_shoulder',
    name: 'Coldsight Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 165, agi: 12, sta: 6 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['hunter'],
    set: 'coldsight_trackers',
  },
  coldsight_trackers_chest: {
    id: 'coldsight_trackers_chest',
    name: 'Coldsight Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 215, agi: 17, sta: 8 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['hunter'],
    set: 'coldsight_trackers',
  },
  coldsight_trackers_gloves: {
    id: 'coldsight_trackers_gloves',
    name: 'Coldsight Grips',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 150, agi: 11, sta: 6 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['hunter'],
    set: 'coldsight_trackers',
  },
  coldsight_trackers_legs: {
    id: 'coldsight_trackers_legs',
    name: 'Coldsight Breeches',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 195, agi: 15, sta: 7 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['hunter'],
    set: 'coldsight_trackers',
  },
  // ---- Slagsnare Trappings ----
  slagsnare_helmet: {
    id: 'slagsnare_helmet',
    name: 'Slagsnare Cowl',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 185, agi: 14, sta: 7 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['hunter'],
    set: 'slagsnare',
  },
  slagsnare_shoulder: {
    id: 'slagsnare_shoulder',
    name: 'Slagsnare Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 165, agi: 12, sta: 6 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['hunter'],
    set: 'slagsnare',
  },
  slagsnare_chest: {
    id: 'slagsnare_chest',
    name: 'Slagsnare Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 215, agi: 17, sta: 8 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['hunter'],
    set: 'slagsnare',
  },
  slagsnare_gloves: {
    id: 'slagsnare_gloves',
    name: 'Slagsnare Grips',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 150, agi: 11, sta: 6 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['hunter'],
    set: 'slagsnare',
  },
  slagsnare_legs: {
    id: 'slagsnare_legs',
    name: 'Slagsnare Breeches',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 195, agi: 15, sta: 7 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['hunter'],
    set: 'slagsnare',
  },
  // ---- Cinderfang Shroud ----
  cinderfang_helmet: {
    id: 'cinderfang_helmet',
    name: 'Cinderfang Cowl',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 185, agi: 14, sta: 7 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['rogue'],
    set: 'cinderfang',
  },
  cinderfang_shoulder: {
    id: 'cinderfang_shoulder',
    name: 'Cinderfang Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 165, agi: 12, sta: 6 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['rogue'],
    set: 'cinderfang',
  },
  cinderfang_chest: {
    id: 'cinderfang_chest',
    name: 'Cinderfang Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 215, agi: 17, sta: 8 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['rogue'],
    set: 'cinderfang',
  },
  cinderfang_gloves: {
    id: 'cinderfang_gloves',
    name: 'Cinderfang Grips',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 150, agi: 11, sta: 6 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['rogue'],
    set: 'cinderfang',
  },
  cinderfang_legs: {
    id: 'cinderfang_legs',
    name: 'Cinderfang Breeches',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 195, agi: 15, sta: 7 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['rogue'],
    set: 'cinderfang',
  },
  // ---- Smolderstrike Leathers ----
  smolderstrike_helmet: {
    id: 'smolderstrike_helmet',
    name: 'Smolderstrike Cowl',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 185, agi: 14, sta: 7 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['rogue'],
    set: 'smolderstrike',
  },
  smolderstrike_shoulder: {
    id: 'smolderstrike_shoulder',
    name: 'Smolderstrike Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 165, agi: 12, sta: 6 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['rogue'],
    set: 'smolderstrike',
  },
  smolderstrike_chest: {
    id: 'smolderstrike_chest',
    name: 'Smolderstrike Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 215, agi: 17, sta: 8 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['rogue'],
    set: 'smolderstrike',
  },
  smolderstrike_gloves: {
    id: 'smolderstrike_gloves',
    name: 'Smolderstrike Grips',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 150, agi: 11, sta: 6 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['rogue'],
    set: 'smolderstrike',
  },
  smolderstrike_legs: {
    id: 'smolderstrike_legs',
    name: 'Smolderstrike Breeches',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 195, agi: 15, sta: 7 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['rogue'],
    set: 'smolderstrike',
  },
  // ---- Ashveil Garb ----
  ashveil_helmet: {
    id: 'ashveil_helmet',
    name: 'Ashveil Cowl',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 185, agi: 14, sta: 7 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['rogue'],
    set: 'ashveil',
  },
  ashveil_shoulder: {
    id: 'ashveil_shoulder',
    name: 'Ashveil Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 165, agi: 12, sta: 6 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['rogue'],
    set: 'ashveil',
  },
  ashveil_chest: {
    id: 'ashveil_chest',
    name: 'Ashveil Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 215, agi: 17, sta: 8 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['rogue'],
    set: 'ashveil',
  },
  ashveil_gloves: {
    id: 'ashveil_gloves',
    name: 'Ashveil Grips',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 150, agi: 11, sta: 6 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['rogue'],
    set: 'ashveil',
  },
  ashveil_legs: {
    id: 'ashveil_legs',
    name: 'Ashveil Breeches',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 195, agi: 15, sta: 7 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['rogue'],
    set: 'ashveil',
  },
  // ---- Creed of Embers Vestments ----
  emberscreed_helmet: {
    id: 'emberscreed_helmet',
    name: 'Creed of Embers Hood',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 90, int: 11, spi: 10 },
    healPower: 14,
    hasteRating: 60,
    critRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['priest'],
    set: 'emberscreed',
  },
  emberscreed_shoulder: {
    id: 'emberscreed_shoulder',
    name: 'Creed of Embers Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 80, int: 9, spi: 9 },
    healPower: 10,
    hasteRating: 60,
    critRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['priest'],
    set: 'emberscreed',
  },
  emberscreed_chest: {
    id: 'emberscreed_chest',
    name: 'Creed of Embers Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 105, int: 13, spi: 12 },
    healPower: 16,
    hasteRating: 60,
    critRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['priest'],
    set: 'emberscreed',
  },
  emberscreed_gloves: {
    id: 'emberscreed_gloves',
    name: 'Creed of Embers Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 75, int: 9, spi: 8 },
    healPower: 10,
    hasteRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['priest'],
    set: 'emberscreed',
  },
  emberscreed_legs: {
    id: 'emberscreed_legs',
    name: 'Creed of Embers Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 11, spi: 11 },
    healPower: 14,
    hasteRating: 60,
    critRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['priest'],
    set: 'emberscreed',
  },
  // ---- Benison Dawnweave ----
  benison_dawnweave_helmet: {
    id: 'benison_dawnweave_helmet',
    name: 'Dawnweave Hood',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 90, int: 11, spi: 10 },
    healPower: 14,
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['priest'],
    set: 'benison_dawnweave',
  },
  benison_dawnweave_shoulder: {
    id: 'benison_dawnweave_shoulder',
    name: 'Dawnweave Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 80, int: 9, spi: 9 },
    healPower: 10,
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['priest'],
    set: 'benison_dawnweave',
  },
  benison_dawnweave_chest: {
    id: 'benison_dawnweave_chest',
    name: 'Dawnweave Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 105, int: 13, spi: 12 },
    healPower: 16,
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['priest'],
    set: 'benison_dawnweave',
  },
  benison_dawnweave_gloves: {
    id: 'benison_dawnweave_gloves',
    name: 'Dawnweave Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 75, int: 9, spi: 8 },
    healPower: 10,
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['priest'],
    set: 'benison_dawnweave',
  },
  benison_dawnweave_legs: {
    id: 'benison_dawnweave_legs',
    name: 'Dawnweave Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 11, spi: 11 },
    healPower: 14,
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['priest'],
    set: 'benison_dawnweave',
  },
  // ---- Vesperash Shroud ----
  vesperash_helmet: {
    id: 'vesperash_helmet',
    name: 'Vesperash Hood',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 90, int: 14, spi: 7 },
    spellPower: 7,
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['priest'],
    set: 'vesperash',
  },
  vesperash_shoulder: {
    id: 'vesperash_shoulder',
    name: 'Vesperash Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 80, int: 12, spi: 6 },
    spellPower: 5,
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['priest'],
    set: 'vesperash',
  },
  vesperash_chest: {
    id: 'vesperash_chest',
    name: 'Vesperash Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 105, int: 17, spi: 8 },
    spellPower: 8,
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['priest'],
    set: 'vesperash',
  },
  vesperash_gloves: {
    id: 'vesperash_gloves',
    name: 'Vesperash Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 75, int: 11, spi: 6 },
    spellPower: 5,
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['priest'],
    set: 'vesperash',
  },
  vesperash_legs: {
    id: 'vesperash_legs',
    name: 'Vesperash Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 15, spi: 7 },
    spellPower: 7,
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['priest'],
    set: 'vesperash',
  },
  // ---- Stormkindled Regalia ----
  stormkindled_helmet: {
    id: 'stormkindled_helmet',
    name: 'Stormkindled Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 325, int: 14, spi: 7 },
    spellPower: 7,
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'stormkindled',
  },
  stormkindled_shoulder: {
    id: 'stormkindled_shoulder',
    name: 'Stormkindled Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 290, int: 12, spi: 6 },
    spellPower: 5,
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'stormkindled',
  },
  stormkindled_chest: {
    id: 'stormkindled_chest',
    name: 'Stormkindled Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 380, int: 17, spi: 8 },
    spellPower: 8,
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'stormkindled',
  },
  stormkindled_gloves: {
    id: 'stormkindled_gloves',
    name: 'Stormkindled Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 270, int: 11, spi: 6 },
    spellPower: 5,
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'stormkindled',
  },
  stormkindled_legs: {
    id: 'stormkindled_legs',
    name: 'Stormkindled Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 345, int: 15, spi: 7 },
    spellPower: 7,
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'stormkindled',
  },
  // ---- Warspirit Emberscale ----
  warspirit_emberscale_helmet: {
    id: 'warspirit_emberscale_helmet',
    name: 'Emberscale Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 325, str: 14, sta: 7 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'warspirit_emberscale',
  },
  warspirit_emberscale_shoulder: {
    id: 'warspirit_emberscale_shoulder',
    name: 'Emberscale Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 290, str: 12, sta: 6 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'warspirit_emberscale',
  },
  warspirit_emberscale_chest: {
    id: 'warspirit_emberscale_chest',
    name: 'Emberscale Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 380, str: 17, sta: 8 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'warspirit_emberscale',
  },
  warspirit_emberscale_gloves: {
    id: 'warspirit_emberscale_gloves',
    name: 'Emberscale Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 270, str: 11, sta: 6 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'warspirit_emberscale',
  },
  warspirit_emberscale_legs: {
    id: 'warspirit_emberscale_legs',
    name: 'Emberscale Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 345, str: 15, sta: 7 },
    hasteRating: 60,
    critRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'warspirit_emberscale',
  },
  // ---- Stonehearth Bastion ----
  stonehearth_helmet: {
    id: 'stonehearth_helmet',
    name: 'Stonehearth Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 325, str: 10, sta: 11 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'stonehearth',
  },
  stonehearth_shoulder: {
    id: 'stonehearth_shoulder',
    name: 'Stonehearth Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 290, str: 8, sta: 10 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'stonehearth',
  },
  stonehearth_chest: {
    id: 'stonehearth_chest',
    name: 'Stonehearth Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 380, str: 11, sta: 14 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'stonehearth',
  },
  stonehearth_gloves: {
    id: 'stonehearth_gloves',
    name: 'Stonehearth Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 270, str: 8, sta: 9 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'stonehearth',
  },
  stonehearth_legs: {
    id: 'stonehearth_legs',
    name: 'Stonehearth Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 345, str: 10, sta: 12 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'stonehearth',
  },
  // ---- Springmender Scale ----
  springmender_helmet: {
    id: 'springmender_helmet',
    name: 'Springmender Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 325, int: 11, spi: 10 },
    healPower: 14,
    hasteRating: 60,
    critRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'springmender',
  },
  springmender_shoulder: {
    id: 'springmender_shoulder',
    name: 'Springmender Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 290, int: 9, spi: 9 },
    healPower: 10,
    hasteRating: 60,
    critRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'springmender',
  },
  springmender_chest: {
    id: 'springmender_chest',
    name: 'Springmender Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 380, int: 13, spi: 12 },
    healPower: 16,
    hasteRating: 60,
    critRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'springmender',
  },
  springmender_gloves: {
    id: 'springmender_gloves',
    name: 'Springmender Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 270, int: 9, spi: 8 },
    healPower: 10,
    hasteRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'springmender',
  },
  springmender_legs: {
    id: 'springmender_legs',
    name: 'Springmender Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 345, int: 11, spi: 11 },
    healPower: 14,
    hasteRating: 60,
    critRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['shaman'],
    set: 'springmender',
  },
  // ---- Aetherweave Vestments ----
  chronoweave_helmet: {
    id: 'chronoweave_helmet',
    name: 'Aetherweave Hood',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 90, int: 11, spi: 10 },
    healPower: 14,
    hasteRating: 60,
    critRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['mage'],
    set: 'chronoweave',
  },
  chronoweave_shoulder: {
    id: 'chronoweave_shoulder',
    name: 'Aetherweave Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 80, int: 9, spi: 9 },
    healPower: 10,
    hasteRating: 60,
    critRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['mage'],
    set: 'chronoweave',
  },
  chronoweave_chest: {
    id: 'chronoweave_chest',
    name: 'Aetherweave Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 105, int: 13, spi: 12 },
    healPower: 16,
    hasteRating: 60,
    critRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['mage'],
    set: 'chronoweave',
  },
  chronoweave_gloves: {
    id: 'chronoweave_gloves',
    name: 'Aetherweave Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 75, int: 9, spi: 8 },
    healPower: 10,
    hasteRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['mage'],
    set: 'chronoweave',
  },
  chronoweave_legs: {
    id: 'chronoweave_legs',
    name: 'Aetherweave Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 11, spi: 11 },
    healPower: 14,
    hasteRating: 60,
    critRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['mage'],
    set: 'chronoweave',
  },
  // ---- Pyroclast Regalia ----
  pyroclast_helmet: {
    id: 'pyroclast_helmet',
    name: 'Pyroclast Hood',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 90, int: 14, spi: 7 },
    spellPower: 7,
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['mage'],
    set: 'pyroclast',
  },
  pyroclast_shoulder: {
    id: 'pyroclast_shoulder',
    name: 'Pyroclast Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 80, int: 12, spi: 6 },
    spellPower: 5,
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['mage'],
    set: 'pyroclast',
  },
  pyroclast_chest: {
    id: 'pyroclast_chest',
    name: 'Pyroclast Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 105, int: 17, spi: 8 },
    spellPower: 8,
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['mage'],
    set: 'pyroclast',
  },
  pyroclast_gloves: {
    id: 'pyroclast_gloves',
    name: 'Pyroclast Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 75, int: 11, spi: 6 },
    spellPower: 5,
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['mage'],
    set: 'pyroclast',
  },
  pyroclast_legs: {
    id: 'pyroclast_legs',
    name: 'Pyroclast Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 15, spi: 7 },
    spellPower: 7,
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['mage'],
    set: 'pyroclast',
  },
  // ---- Frostquench Weave ----
  frostquench_helmet: {
    id: 'frostquench_helmet',
    name: 'Frostquench Hood',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 90, int: 14, spi: 7 },
    spellPower: 7,
    hasteRating: 60,
    critRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['mage'],
    set: 'frostquench',
  },
  frostquench_shoulder: {
    id: 'frostquench_shoulder',
    name: 'Frostquench Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 80, int: 12, spi: 6 },
    spellPower: 5,
    hasteRating: 60,
    critRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['mage'],
    set: 'frostquench',
  },
  frostquench_chest: {
    id: 'frostquench_chest',
    name: 'Frostquench Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 105, int: 17, spi: 8 },
    spellPower: 8,
    hasteRating: 60,
    critRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['mage'],
    set: 'frostquench',
  },
  frostquench_gloves: {
    id: 'frostquench_gloves',
    name: 'Frostquench Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 75, int: 11, spi: 6 },
    spellPower: 5,
    hasteRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['mage'],
    set: 'frostquench',
  },
  frostquench_legs: {
    id: 'frostquench_legs',
    name: 'Frostquench Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 15, spi: 7 },
    spellPower: 7,
    hasteRating: 60,
    critRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['mage'],
    set: 'frostquench',
  },
  // ---- Hexthread Shroud ----
  hexthread_helmet: {
    id: 'hexthread_helmet',
    name: 'Hexthread Hood',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 90, int: 14, spi: 7 },
    spellPower: 7,
    hasteRating: 60,
    critRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['warlock'],
    set: 'hexthread',
  },
  hexthread_shoulder: {
    id: 'hexthread_shoulder',
    name: 'Hexthread Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 80, int: 12, spi: 6 },
    spellPower: 5,
    hasteRating: 60,
    critRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['warlock'],
    set: 'hexthread',
  },
  hexthread_chest: {
    id: 'hexthread_chest',
    name: 'Hexthread Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 105, int: 17, spi: 8 },
    spellPower: 8,
    hasteRating: 60,
    critRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['warlock'],
    set: 'hexthread',
  },
  hexthread_gloves: {
    id: 'hexthread_gloves',
    name: 'Hexthread Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 75, int: 11, spi: 6 },
    spellPower: 5,
    hasteRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['warlock'],
    set: 'hexthread',
  },
  hexthread_legs: {
    id: 'hexthread_legs',
    name: 'Hexthread Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 15, spi: 7 },
    spellPower: 7,
    hasteRating: 60,
    critRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['warlock'],
    set: 'hexthread',
  },
  // ---- Gravebrand Regalia ----
  gravebrand_helmet: {
    id: 'gravebrand_helmet',
    name: 'Gravebrand Hood',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 90, int: 14, spi: 7 },
    spellPower: 7,
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['warlock'],
    set: 'gravebrand',
  },
  gravebrand_shoulder: {
    id: 'gravebrand_shoulder',
    name: 'Gravebrand Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 80, int: 12, spi: 6 },
    spellPower: 5,
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['warlock'],
    set: 'gravebrand',
  },
  gravebrand_chest: {
    id: 'gravebrand_chest',
    name: 'Gravebrand Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 105, int: 17, spi: 8 },
    spellPower: 8,
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['warlock'],
    set: 'gravebrand',
  },
  gravebrand_gloves: {
    id: 'gravebrand_gloves',
    name: 'Gravebrand Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 75, int: 11, spi: 6 },
    spellPower: 5,
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['warlock'],
    set: 'gravebrand',
  },
  gravebrand_legs: {
    id: 'gravebrand_legs',
    name: 'Gravebrand Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 15, spi: 7 },
    spellPower: 7,
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['warlock'],
    set: 'gravebrand',
  },
  // ---- Ruincaller Vestments ----
  ruincaller_helmet: {
    id: 'ruincaller_helmet',
    name: 'Ruincaller Hood',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 90, int: 14, spi: 7 },
    spellPower: 7,
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['warlock'],
    set: 'ruincaller',
  },
  ruincaller_shoulder: {
    id: 'ruincaller_shoulder',
    name: 'Ruincaller Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 80, int: 12, spi: 6 },
    spellPower: 5,
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['warlock'],
    set: 'ruincaller',
  },
  ruincaller_chest: {
    id: 'ruincaller_chest',
    name: 'Ruincaller Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 105, int: 17, spi: 8 },
    spellPower: 8,
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['warlock'],
    set: 'ruincaller',
  },
  ruincaller_gloves: {
    id: 'ruincaller_gloves',
    name: 'Ruincaller Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 75, int: 11, spi: 6 },
    spellPower: 5,
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['warlock'],
    set: 'ruincaller',
  },
  ruincaller_legs: {
    id: 'ruincaller_legs',
    name: 'Ruincaller Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 15, spi: 7 },
    spellPower: 7,
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['warlock'],
    set: 'ruincaller',
  },
  // ---- Moonscorch Raiment ----
  moonscorch_helmet: {
    id: 'moonscorch_helmet',
    name: 'Moonscorch Cowl',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 185, int: 14, spi: 7 },
    spellPower: 7,
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'moonscorch',
  },
  moonscorch_shoulder: {
    id: 'moonscorch_shoulder',
    name: 'Moonscorch Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 165, int: 12, spi: 6 },
    spellPower: 5,
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'moonscorch',
  },
  moonscorch_chest: {
    id: 'moonscorch_chest',
    name: 'Moonscorch Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 215, int: 17, spi: 8 },
    spellPower: 8,
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'moonscorch',
  },
  moonscorch_gloves: {
    id: 'moonscorch_gloves',
    name: 'Moonscorch Grips',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 150, int: 11, spi: 6 },
    spellPower: 5,
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'moonscorch',
  },
  moonscorch_legs: {
    id: 'moonscorch_legs',
    name: 'Moonscorch Breeches',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 195, int: 15, spi: 7 },
    spellPower: 7,
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'moonscorch',
  },
  // ---- Wildfang Emberhide ----
  wildfang_emberhide_helmet: {
    id: 'wildfang_emberhide_helmet',
    name: 'Wildfang Cowl',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 185, str: 14, sta: 7 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'wildfang_emberhide',
  },
  wildfang_emberhide_shoulder: {
    id: 'wildfang_emberhide_shoulder',
    name: 'Wildfang Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 165, str: 12, sta: 6 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'wildfang_emberhide',
  },
  wildfang_emberhide_chest: {
    id: 'wildfang_emberhide_chest',
    name: 'Wildfang Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 215, str: 17, sta: 8 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'wildfang_emberhide',
  },
  wildfang_emberhide_gloves: {
    id: 'wildfang_emberhide_gloves',
    name: 'Wildfang Grips',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 150, str: 11, sta: 6 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'wildfang_emberhide',
  },
  wildfang_emberhide_legs: {
    id: 'wildfang_emberhide_legs',
    name: 'Wildfang Breeches',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 195, str: 15, sta: 7 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'wildfang_emberhide',
  },
  // ---- Cinderbark Ward ----
  cinderbark_helmet: {
    id: 'cinderbark_helmet',
    name: 'Cinderbark Cowl',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 185, str: 5, agi: 5, sta: 11 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'cinderbark',
  },
  cinderbark_shoulder: {
    id: 'cinderbark_shoulder',
    name: 'Cinderbark Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 165, str: 4, agi: 4, sta: 10 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'cinderbark',
  },
  cinderbark_chest: {
    id: 'cinderbark_chest',
    name: 'Cinderbark Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 215, str: 6, agi: 5, sta: 14 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'cinderbark',
  },
  cinderbark_gloves: {
    id: 'cinderbark_gloves',
    name: 'Cinderbark Grips',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 150, str: 4, agi: 4, sta: 9 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'cinderbark',
  },
  cinderbark_legs: {
    id: 'cinderbark_legs',
    name: 'Cinderbark Breeches',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 195, str: 5, agi: 5, sta: 12 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'cinderbark',
  },
  // ---- Grovespring Raiment ----
  grovespring_helmet: {
    id: 'grovespring_helmet',
    name: 'Grovespring Cowl',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 185, int: 11, spi: 10 },
    healPower: 14,
    hasteRating: 60,
    critRating: 25,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'grovespring',
  },
  grovespring_shoulder: {
    id: 'grovespring_shoulder',
    name: 'Grovespring Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 165, int: 9, spi: 9 },
    healPower: 10,
    hasteRating: 60,
    critRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'grovespring',
  },
  grovespring_chest: {
    id: 'grovespring_chest',
    name: 'Grovespring Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 215, int: 13, spi: 12 },
    healPower: 16,
    hasteRating: 60,
    critRating: 25,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'grovespring',
  },
  grovespring_gloves: {
    id: 'grovespring_gloves',
    name: 'Grovespring Grips',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 150, int: 9, spi: 8 },
    healPower: 10,
    hasteRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'grovespring',
  },
  grovespring_legs: {
    id: 'grovespring_legs',
    name: 'Grovespring Breeches',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 195, int: 11, spi: 11 },
    healPower: 14,
    hasteRating: 60,
    critRating: 25,
    sellValue: 15000,
    soulbound: true,
    requiredClass: ['druid'],
    set: 'grovespring',
  },
};

// The 15 redemption sigils (slot x class group).
export const IGNIVAR_SIGIL_ITEMS: Record<string, ItemDef> = {
  sigil_anvil_helmet: {
    id: 'sigil_anvil_helmet',
    name: 'Helm Sigil of the Anvil',
    kind: 'tool',
    quality: 'epic',
    stackSize: 20,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior', 'druid', 'mage'],
  },
  sigil_ember_helmet: {
    id: 'sigil_ember_helmet',
    name: 'Helm Sigil of the Ember',
    kind: 'tool',
    quality: 'epic',
    stackSize: 20,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin', 'hunter', 'priest'],
  },
  sigil_tempest_helmet: {
    id: 'sigil_tempest_helmet',
    name: 'Helm Sigil of the Tempest',
    kind: 'tool',
    quality: 'epic',
    stackSize: 20,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman', 'rogue', 'warlock'],
  },
  sigil_anvil_shoulder: {
    id: 'sigil_anvil_shoulder',
    name: 'Mantle Sigil of the Anvil',
    kind: 'tool',
    quality: 'epic',
    stackSize: 20,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior', 'druid', 'mage'],
  },
  sigil_ember_shoulder: {
    id: 'sigil_ember_shoulder',
    name: 'Mantle Sigil of the Ember',
    kind: 'tool',
    quality: 'epic',
    stackSize: 20,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin', 'hunter', 'priest'],
  },
  sigil_tempest_shoulder: {
    id: 'sigil_tempest_shoulder',
    name: 'Mantle Sigil of the Tempest',
    kind: 'tool',
    quality: 'epic',
    stackSize: 20,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman', 'rogue', 'warlock'],
  },
  sigil_anvil_chest: {
    id: 'sigil_anvil_chest',
    name: 'Robe Sigil of the Anvil',
    kind: 'tool',
    quality: 'epic',
    stackSize: 20,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior', 'druid', 'mage'],
  },
  sigil_ember_chest: {
    id: 'sigil_ember_chest',
    name: 'Robe Sigil of the Ember',
    kind: 'tool',
    quality: 'epic',
    stackSize: 20,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin', 'hunter', 'priest'],
  },
  sigil_tempest_chest: {
    id: 'sigil_tempest_chest',
    name: 'Robe Sigil of the Tempest',
    kind: 'tool',
    quality: 'epic',
    stackSize: 20,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman', 'rogue', 'warlock'],
  },
  sigil_anvil_gloves: {
    id: 'sigil_anvil_gloves',
    name: 'Grip Sigil of the Anvil',
    kind: 'tool',
    quality: 'epic',
    stackSize: 20,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior', 'druid', 'mage'],
  },
  sigil_ember_gloves: {
    id: 'sigil_ember_gloves',
    name: 'Grip Sigil of the Ember',
    kind: 'tool',
    quality: 'epic',
    stackSize: 20,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin', 'hunter', 'priest'],
  },
  sigil_tempest_gloves: {
    id: 'sigil_tempest_gloves',
    name: 'Grip Sigil of the Tempest',
    kind: 'tool',
    quality: 'epic',
    stackSize: 20,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman', 'rogue', 'warlock'],
  },
  sigil_anvil_legs: {
    id: 'sigil_anvil_legs',
    name: 'Legging Sigil of the Anvil',
    kind: 'tool',
    quality: 'epic',
    stackSize: 20,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior', 'druid', 'mage'],
  },
  sigil_ember_legs: {
    id: 'sigil_ember_legs',
    name: 'Legging Sigil of the Ember',
    kind: 'tool',
    quality: 'epic',
    stackSize: 20,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin', 'hunter', 'priest'],
  },
  sigil_tempest_legs: {
    id: 'sigil_tempest_legs',
    name: 'Legging Sigil of the Tempest',
    kind: 'tool',
    quality: 'epic',
    stackSize: 20,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman', 'rogue', 'warlock'],
  },
};

// Off-set waist and feet: one pair per armor variant (20 pieces).
export const IGNIVAR_OFFSET_ITEMS: Record<string, ItemDef> = {
  // ---- Cloth spell damage ----
  cord_of_the_last_flame: {
    id: 'cord_of_the_last_flame',
    name: 'Cord of the Last Flame',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 75, int: 11, spi: 6 },
    spellPower: 4,
    hitRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['mage', 'priest', 'warlock'],
  },
  cindersoaked_slippers: {
    id: 'cindersoaked_slippers',
    name: 'Cindersoaked Slippers',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 70, int: 11, spi: 5 },
    spellPower: 4,
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['mage', 'priest', 'warlock'],
  },
  // ---- Cloth healing ----
  springbinder_sash: {
    id: 'springbinder_sash',
    name: 'Springbinder Sash',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 75, int: 9, spi: 8 },
    healPower: 8,
    hasteRating: 25,
    hitRating: 60,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['mage', 'priest'],
  },
  steps_of_quiet_water: {
    id: 'steps_of_quiet_water',
    name: 'Steps of Quiet Water',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 70, int: 8, spi: 8 },
    healPower: 8,
    hasteRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['mage', 'priest'],
  },
  // ---- Leather tanking ----
  cinderbark_cinch: {
    id: 'cinderbark_cinch',
    name: 'Cinderbark Cinch',
    kind: 'armor',
    armorType: 'leather',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 150, agi: 8, sta: 9 },
    hitRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['druid'],
  },
  ashenbark_treads: {
    id: 'ashenbark_treads',
    name: 'Ashenbark Treads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 145, agi: 7, sta: 9 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['druid'],
  },
  // ---- Leather dps ----
  slagstalker_belt: {
    id: 'slagstalker_belt',
    name: 'Slagstalker Belt',
    kind: 'armor',
    armorType: 'leather',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 150, agi: 11, sta: 6 },
    hitRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['rogue', 'hunter', 'druid'],
  },
  ashrunner_boots: {
    id: 'ashrunner_boots',
    name: 'Ashrunner Boots',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 145, agi: 11, sta: 5 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['rogue', 'hunter', 'druid'],
  },
  // ---- Leather spell damage ----
  moonscorch_waistwrap: {
    id: 'moonscorch_waistwrap',
    name: 'Moonscorch Waistwrap',
    kind: 'armor',
    armorType: 'leather',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 150, int: 11, spi: 6 },
    spellPower: 4,
    hitRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['druid'],
  },
  scorchgrove_striders: {
    id: 'scorchgrove_striders',
    name: 'Scorchgrove Striders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 145, int: 11, spi: 5 },
    spellPower: 4,
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['druid'],
  },
  // ---- Leather healing ----
  grovetender_belt: {
    id: 'grovetender_belt',
    name: 'Grovetender Belt',
    kind: 'armor',
    armorType: 'leather',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 150, int: 9, spi: 8 },
    healPower: 8,
    hasteRating: 25,
    hitRating: 60,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['druid'],
  },
  dewfall_moccasins: {
    id: 'dewfall_moccasins',
    name: 'Dewfall Moccasins',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 145, int: 8, spi: 8 },
    healPower: 8,
    hasteRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['druid'],
  },
  // ---- Mail tanking ----
  forgewall_girdle: {
    id: 'forgewall_girdle',
    name: 'Forgewall Girdle',
    kind: 'armor',
    armorType: 'mail',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 270, str: 8, sta: 9 },
    hitRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['warrior', 'paladin', 'shaman'],
  },
  anvilstance_sabatons: {
    id: 'anvilstance_sabatons',
    name: 'Anvilstance Sabatons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 255, str: 7, sta: 9 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['warrior', 'paladin', 'shaman'],
  },
  // ---- Mail dps ----
  warforged_waistguard: {
    id: 'warforged_waistguard',
    name: 'Warforged Waistguard',
    kind: 'armor',
    armorType: 'mail',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 270, str: 11, sta: 6 },
    hitRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['warrior', 'paladin', 'shaman'],
  },
  furnace_march_greaves: {
    id: 'furnace_march_greaves',
    name: 'Furnace March Greaves',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 255, str: 11, sta: 5 },
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['warrior', 'paladin', 'shaman'],
  },
  // ---- Mail spell damage ----
  stormkindled_chain: {
    id: 'stormkindled_chain',
    name: 'Stormkindled Chain',
    kind: 'armor',
    armorType: 'mail',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 270, int: 11, spi: 6 },
    spellPower: 4,
    hitRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['shaman'],
  },
  thundershock_treads: {
    id: 'thundershock_treads',
    name: 'Thundershock Treads',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 255, int: 11, spi: 5 },
    spellPower: 4,
    critRating: 60,
    hasteRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['shaman'],
  },
  // ---- Mail healing ----
  tidebinder_links: {
    id: 'tidebinder_links',
    name: 'Tidebinder Links',
    kind: 'armor',
    armorType: 'mail',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 270, int: 9, spi: 8 },
    healPower: 8,
    hasteRating: 25,
    hitRating: 60,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['paladin', 'shaman'],
  },
  springwarden_sabatons: {
    id: 'springwarden_sabatons',
    name: 'Springwarden Sabatons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 255, int: 8, spi: 8 },
    healPower: 8,
    hasteRating: 60,
    critRating: 25,
    sellValue: 10000,
    soulbound: true,
    requiredClass: ['paladin', 'shaman'],
  },
};

// Class-open jewelry: four necks (Ignivar) and four rings (Varkhul).
export const IGNIVAR_JEWELRY_ITEMS: Record<string, ItemDef> = {
  // ---- tank ----
  pendant_of_the_first_tempering: {
    id: 'pendant_of_the_first_tempering',
    name: 'Pendant of the First Tempering',
    kind: 'armor',
    slot: 'neck',
    quality: 'epic',
    requiredLevel: 20,
    stats: { str: 7, sta: 9 },
    critRating: 25,
    sellValue: 8000,
    soulbound: true,
  },
  // ---- physical dps ----
  ignivars_ember_choker: {
    id: 'ignivars_ember_choker',
    name: "Ignivar's Ember Choker",
    kind: 'armor',
    slot: 'neck',
    quality: 'epic',
    requiredLevel: 20,
    stats: { str: 8, agi: 8 },
    hitRating: 25,
    sellValue: 8000,
    soulbound: true,
  },
  // ---- spell damage ----
  locket_of_the_last_flame: {
    id: 'locket_of_the_last_flame',
    name: 'Locket of the Last Flame',
    kind: 'armor',
    slot: 'neck',
    quality: 'epic',
    requiredLevel: 20,
    stats: { int: 11, spi: 5 },
    spellPower: 4,
    critRating: 25,
    sellValue: 8000,
    soulbound: true,
  },
  // ---- healing ----
  heartspring_amulet: {
    id: 'heartspring_amulet',
    name: 'Heartspring Amulet',
    kind: 'armor',
    slot: 'neck',
    quality: 'epic',
    requiredLevel: 20,
    stats: { int: 8, spi: 8 },
    healPower: 8,
    hasteRating: 25,
    sellValue: 8000,
    soulbound: true,
  },
  // ---- tank ----
  seal_of_the_forgewall: {
    id: 'seal_of_the_forgewall',
    name: 'Seal of the Forgewall',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { str: 7, sta: 8 },
    hitRating: 25,
    sellValue: 8000,
    soulbound: true,
  },
  // ---- physical dps ----
  band_of_marked_strikes: {
    id: 'band_of_marked_strikes',
    name: 'Band of Marked Strikes',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { str: 8, agi: 7 },
    hitRating: 25,
    sellValue: 8000,
    soulbound: true,
  },
  // ---- spell damage ----
  circle_of_cinders: {
    id: 'circle_of_cinders',
    name: 'Circle of Cinders',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { int: 10, spi: 5 },
    spellPower: 4,
    hitRating: 25,
    sellValue: 8000,
    soulbound: true,
  },
  // ---- healing ----
  loop_of_quiet_springs: {
    id: 'loop_of_quiet_springs',
    name: 'Loop of Quiet Springs',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { int: 8, spi: 7 },
    healPower: 8,
    hitRating: 25,
    sellValue: 8000,
    soulbound: true,
  },
};

// Shields and held offhands (Heroic Varkhul chase pieces).
export const IGNIVAR_HELD_ITEMS: Record<string, ItemDef> = {
  bulwark_of_the_inner_crucible: {
    id: 'bulwark_of_the_inner_crucible',
    name: 'Bulwark of the Inner Crucible',
    kind: 'armor',
    armorType: 'mail',
    slot: 'offhand',
    shield: true,
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 760, str: 8, sta: 10 },
    blockValue: 30,
    critRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['warrior', 'paladin', 'shaman'],
  },
  ember_wardens_barrier: {
    id: 'ember_wardens_barrier',
    name: "Ember Warden's Barrier",
    kind: 'armor',
    armorType: 'mail',
    slot: 'offhand',
    shield: true,
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 760, int: 9, spi: 9 },
    blockValue: 22,
    healPower: 18,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['paladin', 'shaman'],
  },
  orb_of_the_last_spring: {
    id: 'orb_of_the_last_spring',
    name: 'Orb of the Last Spring',
    kind: 'held_offhand',
    slot: 'offhand',
    quality: 'epic',
    requiredLevel: 20,
    stats: { int: 9, spi: 9 },
    healPower: 28,
    hasteRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['priest', 'mage', 'druid', 'paladin', 'shaman'],
  },
  cinder_of_the_first_design: {
    id: 'cinder_of_the_first_design',
    name: 'Cinder of the First Design',
    kind: 'held_offhand',
    slot: 'offhand',
    quality: 'epic',
    requiredLevel: 20,
    stats: { int: 12, spi: 6 },
    spellPower: 14,
    critRating: 25,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['mage', 'priest', 'warlock', 'druid'],
  },
};

// The 10 raid weapons: one-hand dps rides weaponDpsBudget(35) = 17.2 with a
// plus-or-minus 20 percent spread around average = dps x speed; two-handers
// carry the TWOHAND_DPS_MULT premium (19.8) and the 33-point stat line
// (25 x TWOHAND_STAT_MULT). Class locks name the three archetype sets
// equipment_rules enforces. Hit sits exactly where the plan's weapon
// program says: the Kris, the Cleaver, and the Wand.
export const IGNIVAR_WEAPON_ITEMS: Record<string, ItemDef> = {
  forgefathers_warhammer: {
    id: 'forgefathers_warhammer',
    name: "Forgefather's Warhammer",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 36, max: 54, speed: 2.6 },
    stats: { str: 17, sta: 8 },
    critRating: 70,
    hitRating: 30,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['warrior', 'rogue', 'hunter', 'shaman', 'paladin'],
  },
  cinderfang_kris: {
    id: 'cinderfang_kris',
    name: 'Cinderfang Kris',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 25, max: 37, speed: 1.8, dagger: true },
    stats: { agi: 17, sta: 8 },
    critRating: 70,
    hitRating: 30,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['rogue', 'hunter'],
  },
  slagrender_cleaver: {
    id: 'slagrender_cleaver',
    name: 'Slagrender Cleaver',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 33, max: 50, speed: 2.4 },
    stats: { str: 9, agi: 9, sta: 7 },
    critRating: 70,
    hitRating: 30,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['warrior', 'rogue', 'hunter', 'shaman', 'paladin'],
  },
  anvilguard_blade: {
    id: 'anvilguard_blade',
    name: 'Anvilguard Blade',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 36, max: 54, speed: 2.6 },
    stats: { str: 11, sta: 14 },
    critRating: 70,
    hitRating: 30,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['warrior', 'rogue', 'hunter', 'shaman', 'paladin'],
  },
  heart_of_the_end_greatblade: {
    id: 'heart_of_the_end_greatblade',
    name: 'Heart of the End Greatblade',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 55, max: 83, speed: 3.5 },
    stats: { str: 22, sta: 11 },
    critRating: 70,
    hitRating: 30,
    sellValue: 16000,
    soulbound: true,
    // No rogue: the equipment boundary hard-blocks rogues from two-handers,
    // and requiredClass must list exactly who canEquipItem admits
    // (tests/equipment_proficiency.test.ts).
    requiredClass: ['warrior', 'hunter', 'shaman', 'paladin'],
  },
  staff_of_the_last_spring: {
    id: 'staff_of_the_last_spring',
    name: 'Staff of the Last Spring',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 51, max: 76, speed: 3.2 },
    stats: { int: 17, spi: 16 },
    healPower: 68,
    hasteRating: 70,
    hitRating: 30,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['mage', 'priest', 'warlock', 'shaman', 'paladin', 'druid'],
  },
  forgefire_spire: {
    id: 'forgefire_spire',
    name: 'Forgefire Spire',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 51, max: 76, speed: 3.2 },
    stats: { int: 22, spi: 11 },
    spellPower: 34,
    critRating: 70,
    hitRating: 30,
    sellValue: 16000,
    soulbound: true,
    requiredClass: ['mage', 'priest', 'warlock', 'shaman', 'paladin', 'druid'],
  },
  springtouched_crozier: {
    id: 'springtouched_crozier',
    name: 'Springtouched Crozier',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 33, max: 50, speed: 2.4 },
    stats: { int: 13, spi: 12 },
    healPower: 40,
    hasteRating: 70,
    hitRating: 30,
    sellValue: 14000,
    soulbound: true,
    requiredClass: ['mage', 'priest', 'warlock', 'shaman', 'paladin', 'druid'],
  },
  wand_of_quenched_sparks: {
    id: 'wand_of_quenched_sparks',
    name: 'Wand of Quenched Sparks',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 21, max: 31, speed: 1.5 },
    stats: { int: 17, spi: 8 },
    spellPower: 20,
    critRating: 70,
    hitRating: 30,
    sellValue: 12000,
    soulbound: true,
    requiredClass: ['mage', 'priest', 'warlock', 'shaman', 'paladin', 'druid'],
  },
};

// The merged table data.ts spreads into ITEMS.
export const IGNIVAR_LOOT_ITEMS: Record<string, ItemDef> = {
  ...IGNIVAR_SET_ITEMS,
  ...IGNIVAR_SIGIL_ITEMS,
  ...IGNIVAR_OFFSET_ITEMS,
  ...IGNIVAR_JEWELRY_ITEMS,
  ...IGNIVAR_HELD_ITEMS,
  ...IGNIVAR_WEAPON_ITEMS,
};

// Every Ignivar loot id, for the item-level source registration and the
// art-pending icon ledger. Order follows the tables above.
export const IGNIVAR_LOOT_ITEM_IDS: readonly string[] = Object.keys(IGNIVAR_LOOT_ITEMS);

// The art-pending ledger: EMPTY since the Crucible art wave landed
// (crucible-set-icons-2026-08-29 in public/ui/items/mapping.json painted
// all 192 non-weapon pieces; the weapons shipped painted from the start).
// The machinery stays: ITEM_ART_PENDING (src/ui/icons.ts) serves the
// procedural icon for any id listed here, and the item-art audit CLI
// (scripts/item_art_audit.mjs) excludes it from the
// every-live-item-has-art sweep, so a future content wave can stage
// unpainted items the same way.
export const IGNIVAR_ART_PENDING_ITEM_IDS: readonly string[] = [];

// The Crucible Quartermaster's redemption stock: every set piece priced at
// exactly one sigil of its slot and class group. The buy path additionally
// validates the buyer's class against the piece's requiredClass, so one
// token serves its three classes and each class picks its spec's set.
export const CRUCIBLE_VENDOR_NPC_ID = 'crucible_quartermaster';

// Reserved so this overworld service NPC does not shift the sequential entity
// ids pinned by replay parity. The other reserved NPC singletons occupy
// 1_000_000_000 through 1_000_000_002.
export const CRUCIBLE_VENDOR_ENTITY_ID = 1_000_000_003;

/** Overworld entrance position, separate from the inert dynamic NPC definition.
 *
 *  The Forgefather's Isle keep door (IGNIVAR_KEEP_DOOR_POS, 503.05 / 2243.7) sits at
 *  the top of a walled stair passage up the keep's south face, on the summit flat
 *  at 18.85. The quartermaster stands on the LANDING COURT one flight below it
 *  (the stair band's level run at 15.34, x 500.6 to 506.1, z 2236 to 2238.5), at
 *  the west edge so the flight stays open, six yards from the door and outside its
 *  2 yd walk-in trigger. Both hosts spawn him there (src/sim/sim.ts, reserved id).
 *
 *  The earlier spot, 510.5 / 2242.5, is OUTSIDE the passage's west wall on the
 *  raw terrain shelf at 6.1, thirteen yards below the door with a wall between:
 *  reachable only by leaving the fortress, swimming round the isle and walking
 *  to the foot of the wall. tests/crucible_vendor_reach.test.ts walks the real
 *  motion kernel from the door and from the tier-three court to pin this. */
export const CRUCIBLE_VENDOR_ENTRANCE_POS = { x: 505.5, z: 2237.6 } as const;

export interface CrucibleVendorOffer {
  itemId: string;
  sigilId: string;
}

export const CRUCIBLE_VENDOR_STOCK: readonly CrucibleVendorOffer[] = [
  ...CRUCIBLE_PATTERN_VENDOR_STOCK,
  { itemId: 'slagbreaker_helmet', sigilId: 'sigil_anvil_helmet' },
  { itemId: 'slagbreaker_shoulder', sigilId: 'sigil_anvil_shoulder' },
  { itemId: 'slagbreaker_chest', sigilId: 'sigil_anvil_chest' },
  { itemId: 'slagbreaker_gloves', sigilId: 'sigil_anvil_gloves' },
  { itemId: 'slagbreaker_legs', sigilId: 'sigil_anvil_legs' },
  { itemId: 'emberfury_helmet', sigilId: 'sigil_anvil_helmet' },
  { itemId: 'emberfury_shoulder', sigilId: 'sigil_anvil_shoulder' },
  { itemId: 'emberfury_chest', sigilId: 'sigil_anvil_chest' },
  { itemId: 'emberfury_gloves', sigilId: 'sigil_anvil_gloves' },
  { itemId: 'emberfury_legs', sigilId: 'sigil_anvil_legs' },
  { itemId: 'forgewall_helmet', sigilId: 'sigil_anvil_helmet' },
  { itemId: 'forgewall_shoulder', sigilId: 'sigil_anvil_shoulder' },
  { itemId: 'forgewall_chest', sigilId: 'sigil_anvil_chest' },
  { itemId: 'forgewall_gloves', sigilId: 'sigil_anvil_gloves' },
  { itemId: 'forgewall_legs', sigilId: 'sigil_anvil_legs' },
  { itemId: 'dawnforged_helmet', sigilId: 'sigil_ember_helmet' },
  { itemId: 'dawnforged_shoulder', sigilId: 'sigil_ember_shoulder' },
  { itemId: 'dawnforged_chest', sigilId: 'sigil_ember_chest' },
  { itemId: 'dawnforged_gloves', sigilId: 'sigil_ember_gloves' },
  { itemId: 'dawnforged_legs', sigilId: 'sigil_ember_legs' },
  { itemId: 'oathpyre_helmet', sigilId: 'sigil_ember_helmet' },
  { itemId: 'oathpyre_shoulder', sigilId: 'sigil_ember_shoulder' },
  { itemId: 'oathpyre_chest', sigilId: 'sigil_ember_chest' },
  { itemId: 'oathpyre_gloves', sigilId: 'sigil_ember_gloves' },
  { itemId: 'oathpyre_legs', sigilId: 'sigil_ember_legs' },
  { itemId: 'zealfire_helmet', sigilId: 'sigil_ember_helmet' },
  { itemId: 'zealfire_shoulder', sigilId: 'sigil_ember_shoulder' },
  { itemId: 'zealfire_chest', sigilId: 'sigil_ember_chest' },
  { itemId: 'zealfire_gloves', sigilId: 'sigil_ember_gloves' },
  { itemId: 'zealfire_legs', sigilId: 'sigil_ember_legs' },
  { itemId: 'packlord_emberhide_helmet', sigilId: 'sigil_ember_helmet' },
  { itemId: 'packlord_emberhide_shoulder', sigilId: 'sigil_ember_shoulder' },
  { itemId: 'packlord_emberhide_chest', sigilId: 'sigil_ember_chest' },
  { itemId: 'packlord_emberhide_gloves', sigilId: 'sigil_ember_gloves' },
  { itemId: 'packlord_emberhide_legs', sigilId: 'sigil_ember_legs' },
  { itemId: 'coldsight_trackers_helmet', sigilId: 'sigil_ember_helmet' },
  { itemId: 'coldsight_trackers_shoulder', sigilId: 'sigil_ember_shoulder' },
  { itemId: 'coldsight_trackers_chest', sigilId: 'sigil_ember_chest' },
  { itemId: 'coldsight_trackers_gloves', sigilId: 'sigil_ember_gloves' },
  { itemId: 'coldsight_trackers_legs', sigilId: 'sigil_ember_legs' },
  { itemId: 'slagsnare_helmet', sigilId: 'sigil_ember_helmet' },
  { itemId: 'slagsnare_shoulder', sigilId: 'sigil_ember_shoulder' },
  { itemId: 'slagsnare_chest', sigilId: 'sigil_ember_chest' },
  { itemId: 'slagsnare_gloves', sigilId: 'sigil_ember_gloves' },
  { itemId: 'slagsnare_legs', sigilId: 'sigil_ember_legs' },
  { itemId: 'cinderfang_helmet', sigilId: 'sigil_tempest_helmet' },
  { itemId: 'cinderfang_shoulder', sigilId: 'sigil_tempest_shoulder' },
  { itemId: 'cinderfang_chest', sigilId: 'sigil_tempest_chest' },
  { itemId: 'cinderfang_gloves', sigilId: 'sigil_tempest_gloves' },
  { itemId: 'cinderfang_legs', sigilId: 'sigil_tempest_legs' },
  { itemId: 'smolderstrike_helmet', sigilId: 'sigil_tempest_helmet' },
  { itemId: 'smolderstrike_shoulder', sigilId: 'sigil_tempest_shoulder' },
  { itemId: 'smolderstrike_chest', sigilId: 'sigil_tempest_chest' },
  { itemId: 'smolderstrike_gloves', sigilId: 'sigil_tempest_gloves' },
  { itemId: 'smolderstrike_legs', sigilId: 'sigil_tempest_legs' },
  { itemId: 'ashveil_helmet', sigilId: 'sigil_tempest_helmet' },
  { itemId: 'ashveil_shoulder', sigilId: 'sigil_tempest_shoulder' },
  { itemId: 'ashveil_chest', sigilId: 'sigil_tempest_chest' },
  { itemId: 'ashveil_gloves', sigilId: 'sigil_tempest_gloves' },
  { itemId: 'ashveil_legs', sigilId: 'sigil_tempest_legs' },
  { itemId: 'emberscreed_helmet', sigilId: 'sigil_ember_helmet' },
  { itemId: 'emberscreed_shoulder', sigilId: 'sigil_ember_shoulder' },
  { itemId: 'emberscreed_chest', sigilId: 'sigil_ember_chest' },
  { itemId: 'emberscreed_gloves', sigilId: 'sigil_ember_gloves' },
  { itemId: 'emberscreed_legs', sigilId: 'sigil_ember_legs' },
  { itemId: 'benison_dawnweave_helmet', sigilId: 'sigil_ember_helmet' },
  { itemId: 'benison_dawnweave_shoulder', sigilId: 'sigil_ember_shoulder' },
  { itemId: 'benison_dawnweave_chest', sigilId: 'sigil_ember_chest' },
  { itemId: 'benison_dawnweave_gloves', sigilId: 'sigil_ember_gloves' },
  { itemId: 'benison_dawnweave_legs', sigilId: 'sigil_ember_legs' },
  { itemId: 'vesperash_helmet', sigilId: 'sigil_ember_helmet' },
  { itemId: 'vesperash_shoulder', sigilId: 'sigil_ember_shoulder' },
  { itemId: 'vesperash_chest', sigilId: 'sigil_ember_chest' },
  { itemId: 'vesperash_gloves', sigilId: 'sigil_ember_gloves' },
  { itemId: 'vesperash_legs', sigilId: 'sigil_ember_legs' },
  { itemId: 'stormkindled_helmet', sigilId: 'sigil_tempest_helmet' },
  { itemId: 'stormkindled_shoulder', sigilId: 'sigil_tempest_shoulder' },
  { itemId: 'stormkindled_chest', sigilId: 'sigil_tempest_chest' },
  { itemId: 'stormkindled_gloves', sigilId: 'sigil_tempest_gloves' },
  { itemId: 'stormkindled_legs', sigilId: 'sigil_tempest_legs' },
  { itemId: 'warspirit_emberscale_helmet', sigilId: 'sigil_tempest_helmet' },
  { itemId: 'warspirit_emberscale_shoulder', sigilId: 'sigil_tempest_shoulder' },
  { itemId: 'warspirit_emberscale_chest', sigilId: 'sigil_tempest_chest' },
  { itemId: 'warspirit_emberscale_gloves', sigilId: 'sigil_tempest_gloves' },
  { itemId: 'warspirit_emberscale_legs', sigilId: 'sigil_tempest_legs' },
  { itemId: 'stonehearth_helmet', sigilId: 'sigil_tempest_helmet' },
  { itemId: 'stonehearth_shoulder', sigilId: 'sigil_tempest_shoulder' },
  { itemId: 'stonehearth_chest', sigilId: 'sigil_tempest_chest' },
  { itemId: 'stonehearth_gloves', sigilId: 'sigil_tempest_gloves' },
  { itemId: 'stonehearth_legs', sigilId: 'sigil_tempest_legs' },
  { itemId: 'springmender_helmet', sigilId: 'sigil_tempest_helmet' },
  { itemId: 'springmender_shoulder', sigilId: 'sigil_tempest_shoulder' },
  { itemId: 'springmender_chest', sigilId: 'sigil_tempest_chest' },
  { itemId: 'springmender_gloves', sigilId: 'sigil_tempest_gloves' },
  { itemId: 'springmender_legs', sigilId: 'sigil_tempest_legs' },
  { itemId: 'chronoweave_helmet', sigilId: 'sigil_anvil_helmet' },
  { itemId: 'chronoweave_shoulder', sigilId: 'sigil_anvil_shoulder' },
  { itemId: 'chronoweave_chest', sigilId: 'sigil_anvil_chest' },
  { itemId: 'chronoweave_gloves', sigilId: 'sigil_anvil_gloves' },
  { itemId: 'chronoweave_legs', sigilId: 'sigil_anvil_legs' },
  { itemId: 'pyroclast_helmet', sigilId: 'sigil_anvil_helmet' },
  { itemId: 'pyroclast_shoulder', sigilId: 'sigil_anvil_shoulder' },
  { itemId: 'pyroclast_chest', sigilId: 'sigil_anvil_chest' },
  { itemId: 'pyroclast_gloves', sigilId: 'sigil_anvil_gloves' },
  { itemId: 'pyroclast_legs', sigilId: 'sigil_anvil_legs' },
  { itemId: 'frostquench_helmet', sigilId: 'sigil_anvil_helmet' },
  { itemId: 'frostquench_shoulder', sigilId: 'sigil_anvil_shoulder' },
  { itemId: 'frostquench_chest', sigilId: 'sigil_anvil_chest' },
  { itemId: 'frostquench_gloves', sigilId: 'sigil_anvil_gloves' },
  { itemId: 'frostquench_legs', sigilId: 'sigil_anvil_legs' },
  { itemId: 'hexthread_helmet', sigilId: 'sigil_tempest_helmet' },
  { itemId: 'hexthread_shoulder', sigilId: 'sigil_tempest_shoulder' },
  { itemId: 'hexthread_chest', sigilId: 'sigil_tempest_chest' },
  { itemId: 'hexthread_gloves', sigilId: 'sigil_tempest_gloves' },
  { itemId: 'hexthread_legs', sigilId: 'sigil_tempest_legs' },
  { itemId: 'gravebrand_helmet', sigilId: 'sigil_tempest_helmet' },
  { itemId: 'gravebrand_shoulder', sigilId: 'sigil_tempest_shoulder' },
  { itemId: 'gravebrand_chest', sigilId: 'sigil_tempest_chest' },
  { itemId: 'gravebrand_gloves', sigilId: 'sigil_tempest_gloves' },
  { itemId: 'gravebrand_legs', sigilId: 'sigil_tempest_legs' },
  { itemId: 'ruincaller_helmet', sigilId: 'sigil_tempest_helmet' },
  { itemId: 'ruincaller_shoulder', sigilId: 'sigil_tempest_shoulder' },
  { itemId: 'ruincaller_chest', sigilId: 'sigil_tempest_chest' },
  { itemId: 'ruincaller_gloves', sigilId: 'sigil_tempest_gloves' },
  { itemId: 'ruincaller_legs', sigilId: 'sigil_tempest_legs' },
  { itemId: 'moonscorch_helmet', sigilId: 'sigil_anvil_helmet' },
  { itemId: 'moonscorch_shoulder', sigilId: 'sigil_anvil_shoulder' },
  { itemId: 'moonscorch_chest', sigilId: 'sigil_anvil_chest' },
  { itemId: 'moonscorch_gloves', sigilId: 'sigil_anvil_gloves' },
  { itemId: 'moonscorch_legs', sigilId: 'sigil_anvil_legs' },
  { itemId: 'wildfang_emberhide_helmet', sigilId: 'sigil_anvil_helmet' },
  { itemId: 'wildfang_emberhide_shoulder', sigilId: 'sigil_anvil_shoulder' },
  { itemId: 'wildfang_emberhide_chest', sigilId: 'sigil_anvil_chest' },
  { itemId: 'wildfang_emberhide_gloves', sigilId: 'sigil_anvil_gloves' },
  { itemId: 'wildfang_emberhide_legs', sigilId: 'sigil_anvil_legs' },
  { itemId: 'cinderbark_helmet', sigilId: 'sigil_anvil_helmet' },
  { itemId: 'cinderbark_shoulder', sigilId: 'sigil_anvil_shoulder' },
  { itemId: 'cinderbark_chest', sigilId: 'sigil_anvil_chest' },
  { itemId: 'cinderbark_gloves', sigilId: 'sigil_anvil_gloves' },
  { itemId: 'cinderbark_legs', sigilId: 'sigil_anvil_legs' },
  { itemId: 'grovespring_helmet', sigilId: 'sigil_anvil_helmet' },
  { itemId: 'grovespring_shoulder', sigilId: 'sigil_anvil_shoulder' },
  { itemId: 'grovespring_chest', sigilId: 'sigil_anvil_chest' },
  { itemId: 'grovespring_gloves', sigilId: 'sigil_anvil_gloves' },
  { itemId: 'grovespring_legs', sigilId: 'sigil_anvil_legs' },
];

// The Crucible Quartermaster stands outside the Forgefather's Isle keep door,
// so raiders can redeem sigils without entering an instance. The crucibleVendor
// flag routes the dialog to the sigil shop.
export const IGNIVAR_VENDOR_NPCS: Record<string, NpcDef> = {
  [CRUCIBLE_VENDOR_NPC_ID]: {
    id: CRUCIBLE_VENDOR_NPC_ID,
    name: 'Quartermaster Bronn Emberward',
    title: 'Crucible Quartermaster',
    // Dynamic definitions remain inert so the generic placement collider veto
    // cannot suppress nearby raid-entrance structures or terrain edits.
    pos: { x: 0, z: 0 },
    facing: Math.PI,
    color: 0xb3702d,
    questIds: [],
    crucibleVendor: true,
    greeting:
      'The forge marks its own. Bring me a sigil from the Crucible and I will fit you for war.',
    dynamic: true,
  },
};
