// WARFARE gear, sold by BOTH honor quartermasters from this one canonical stock:
// FURY in Eastbrook Vale and Warmarshal Draven Kole in Highwatch. Every item is a
// level-20 epic sourced at WARFARE_SOURCE_LEVEL, so the item-level index reads it
// as item level 31 after the epic +6 quality bump: level with the heroic five-man
// and rift clear-time epics, which is the current farmable tier.
//
// Three authored fractions shape every piece. All three are named constants
// below so the tests pin the constant rather than a magic number:
//   - WARFARE_STAT_FRACTION of the slot's primary-stat budget on armor and
//     weapons, so a WARFARE piece stays visibly below a same-slot PvE epic.
//   - WARFARE_JEWELRY_STAT_FRACTION on neck and rings, which is what keeps a
//     WARFARE ring or amulet scoring below the Heroic Quartermaster's badge
//     jewelry, five item levels lower and carrying a combat rating per piece.
//     Badge jewelry is not the only other jewelry source: the rift epic ring
//     abysswrought_band is level with this tier and out-stats the WARFARE ring.
//   - WARFARE_RATING_FRACTION on every slot: the FULL slot budget again,
//     expressed as WARFARE Offense and Defense Rating.
// Armor mitigation and weapon DPS are the slot's inherent baseline rather than
// budget-derived, and both sit on the item-level-31 curve beside the same-slot,
// same-armor-type PvE epics.
//
// The rule this tier is built to, which replaces the older "never out-stats
// same-tier PvE gear": honor gear sits at the current five-man epic item level,
// carries a deliberate primary-stat discount against a same-slot PvE epic, and
// never reaches raid or legendary stat levels. Its advantage over PvE gear is
// expressed entirely in WARFARE, which is inert outside hostile
// player-versus-player combat. No WARFARE piece carries critRating, hitRating,
// or hasteRating and none ever will: every item-level-31 PvE epic carries one,
// which is what keeps a complete honor kit from being a shortcut past the
// heroic tier.
//
// The five armor families are also the five WARFARE item sets (see
// content/item_sets.ts), with 2, 4, and 7 piece tiers paid in WARFARE rating and
// PvP-gated effects only, so the sets contribute exactly nothing in PvE. Neck,
// rings, and weapons carry no set tag: they are shared across role profiles.
// The budget rule and the badge-comparison guard live in
// tests/pvp_honor_gear.test.ts; the tier arithmetic in
// tests/warfare_gear_tier.test.ts. Design doc: docs/design/warfare.md.

import { EASTBROOK_NPC_PLACEMENTS_BY_ID } from '../eastbrook_layout';
import type { ItemDef, NpcDef } from '../types';
import {
  SET_WARFARE_ASHSTALKER,
  SET_WARFARE_CINDERWEAVE,
  SET_WARFARE_FURYFORGED,
  SET_WARFARE_STORMBOUND,
  SET_WARFARE_THORNHIDE,
} from './item_sets';

export const FURY_NPC_ID = 'fury';
// Reserved so adding FURY does not shift the deterministic nextId sequence used
// by every existing world spawn and parity replay.
export const FURY_ENTITY_ID = 1_000_000_001;
// The content level FURY's stock reads as. item_level.buildSourceIndex registers
// every FURY_STOCK id here, so the epic quality bump (+6) puts the whole catalog
// at item level 31.
export const WARFARE_SOURCE_LEVEL = 25;

// Share of the slot's primary-stat budget an armor or weapon piece carries. The
// discount against a same-slot PvE epic (which carries the full budget) is the
// structural half of "honor gear is not a PvE shortcut"; the other half is that
// no WARFARE piece carries a combat rating.
export const WARFARE_STAT_FRACTION = 0.9;
// Jewelry is held lower on purpose. What it is calibrated against is the Heroic
// Quartermaster's badge jewelry, which sits at item level 26, five below this
// tier, and carries 25 of a combat rating per piece. At the armor fraction a
// WARFARE ring reaches 12 primary points against the badge ring's 11 and a WARFARE
// neck 13 against the badge neck's 12, which would overtake that lower tier on raw
// stats and break the guard in tests/pvp_honor_gear.test.ts. At this fraction the
// ring lands on 10 and the neck on 11. Badge jewelry is NOT the only other jewelry
// source: the rift epic ring abysswrought_band (content/rift/items.ts) is item
// level 31, level with this tier, and carries 13 primary points and 25 Haste
// Rating, so a ring above the WARFARE ring already exists and is farmable.
export const WARFARE_JEWELRY_STAT_FRACTION = 0.75;
// WARFARE Offense and Defense Rating per piece, as a share of the same slot
// budget: the full budget, on every slot, unchanged from the shipped rule. The
// base 11-slot kit therefore carries 182 of each rating (18.2 percent) and the
// seven-piece set tops it up to the cap rather than carrying it.
export const WARFARE_RATING_FRACTION = 1.0;

export const WARFARE_ITEMS: Record<string, ItemDef> = {
  // Furyforged Battlegear: Strength and Stamina mail.
  furyforged_warhelm: {
    id: 'furyforged_warhelm',
    set: SET_WARFARE_FURYFORGED,
    name: 'Furyforged Warhelm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 292, str: 6, sta: 10 },
    pvpOffenseRating: 18,
    pvpDefenseRating: 18,
    priceHonor: 900,
    sellValue: 0,
    soulbound: true,
  },
  furyforged_warspaulders: {
    id: 'furyforged_warspaulders',
    set: SET_WARFARE_FURYFORGED,
    name: 'Furyforged Warspaulders',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 240, str: 6, sta: 8 },
    pvpOffenseRating: 16,
    pvpDefenseRating: 16,
    priceHonor: 700,
    sellValue: 0,
    soulbound: true,
  },
  furyforged_warplate: {
    id: 'furyforged_warplate',
    set: SET_WARFARE_FURYFORGED,
    name: 'Furyforged Warplate',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 335, str: 8, sta: 12 },
    pvpOffenseRating: 22,
    pvpDefenseRating: 22,
    priceHonor: 1200,
    sellValue: 0,
    soulbound: true,
  },
  furyforged_girdle: {
    id: 'furyforged_girdle',
    set: SET_WARFARE_FURYFORGED,
    name: 'Furyforged Girdle',
    kind: 'armor',
    armorType: 'mail',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 224, str: 5, sta: 9 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 450,
    sellValue: 0,
    soulbound: true,
  },
  furyforged_legguards: {
    id: 'furyforged_legguards',
    set: SET_WARFARE_FURYFORGED,
    name: 'Furyforged Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 315, str: 8, sta: 10 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
  },
  furyforged_gauntlets: {
    id: 'furyforged_gauntlets',
    set: SET_WARFARE_FURYFORGED,
    name: 'Furyforged Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 224, str: 5, sta: 9 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 550,
    sellValue: 0,
    soulbound: true,
  },
  furyforged_sabatons: {
    id: 'furyforged_sabatons',
    set: SET_WARFARE_FURYFORGED,
    name: 'Furyforged Sabatons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 212, str: 7, sta: 6 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 550,
    sellValue: 0,
    soulbound: true,
  },

  // Stormbound Vestments: Intellect, Stamina, and Spirit mail.
  stormbound_crown: {
    id: 'stormbound_crown',
    set: SET_WARFARE_STORMBOUND,
    name: 'Stormbound Crown',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 292, int: 8, sta: 6, spi: 3 },
    pvpOffenseRating: 18,
    pvpDefenseRating: 18,
    priceHonor: 900,
    sellValue: 0,
    soulbound: true,
  },
  stormbound_spaulders: {
    id: 'stormbound_spaulders',
    set: SET_WARFARE_STORMBOUND,
    name: 'Stormbound Spaulders',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 240, int: 6, sta: 5, spi: 3 },
    pvpOffenseRating: 16,
    pvpDefenseRating: 16,
    priceHonor: 700,
    sellValue: 0,
    soulbound: true,
  },
  stormbound_hauberk: {
    id: 'stormbound_hauberk',
    set: SET_WARFARE_STORMBOUND,
    name: 'Stormbound Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 335, int: 10, sta: 7, spi: 3 },
    pvpOffenseRating: 22,
    pvpDefenseRating: 22,
    priceHonor: 1200,
    sellValue: 0,
    soulbound: true,
  },
  stormbound_waistguard: {
    id: 'stormbound_waistguard',
    set: SET_WARFARE_STORMBOUND,
    name: 'Stormbound Waistguard',
    kind: 'armor',
    armorType: 'mail',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 224, int: 5, sta: 5, spi: 4 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 450,
    sellValue: 0,
    soulbound: true,
  },
  stormbound_legmail: {
    id: 'stormbound_legmail',
    set: SET_WARFARE_STORMBOUND,
    name: 'Stormbound Legmail',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 315, int: 8, sta: 7, spi: 3 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
  },
  stormbound_handguards: {
    id: 'stormbound_handguards',
    set: SET_WARFARE_STORMBOUND,
    name: 'Stormbound Handguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 224, int: 5, sta: 5, spi: 4 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 550,
    sellValue: 0,
    soulbound: true,
  },
  stormbound_greaves: {
    id: 'stormbound_greaves',
    set: SET_WARFARE_STORMBOUND,
    name: 'Stormbound Greaves',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 212, int: 7, sta: 5, spi: 3 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 550,
    sellValue: 0,
    soulbound: true,
  },

  // Ashstalker Kit: Agility and Stamina leather.
  ashstalker_cowl: {
    id: 'ashstalker_cowl',
    set: SET_WARFARE_ASHSTALKER,
    name: 'Ashstalker Cowl',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 168, agi: 8, sta: 8 },
    pvpOffenseRating: 18,
    pvpDefenseRating: 18,
    priceHonor: 900,
    sellValue: 0,
    soulbound: true,
  },
  ashstalker_shoulderguards: {
    id: 'ashstalker_shoulderguards',
    set: SET_WARFARE_ASHSTALKER,
    name: 'Ashstalker Shoulderguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 148, agi: 6, sta: 8 },
    pvpOffenseRating: 16,
    pvpDefenseRating: 16,
    priceHonor: 700,
    sellValue: 0,
    soulbound: true,
  },
  ashstalker_harness: {
    id: 'ashstalker_harness',
    set: SET_WARFARE_ASHSTALKER,
    name: 'Ashstalker Harness',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 172, agi: 8, sta: 12 },
    pvpOffenseRating: 22,
    pvpDefenseRating: 22,
    priceHonor: 1200,
    sellValue: 0,
    soulbound: true,
  },
  ashstalker_waistband: {
    id: 'ashstalker_waistband',
    set: SET_WARFARE_ASHSTALKER,
    name: 'Ashstalker Waistband',
    kind: 'armor',
    armorType: 'leather',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 100, agi: 5, sta: 9 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 450,
    sellValue: 0,
    soulbound: true,
  },
  ashstalker_legguards: {
    id: 'ashstalker_legguards',
    set: SET_WARFARE_ASHSTALKER,
    name: 'Ashstalker Legguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 132, agi: 8, sta: 10 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
  },
  ashstalker_grips: {
    id: 'ashstalker_grips',
    set: SET_WARFARE_ASHSTALKER,
    name: 'Ashstalker Grips',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 104, agi: 5, sta: 9 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 550,
    sellValue: 0,
    soulbound: true,
  },
  ashstalker_treads: {
    id: 'ashstalker_treads',
    set: SET_WARFARE_ASHSTALKER,
    name: 'Ashstalker Treads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 96, agi: 7, sta: 6 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 550,
    sellValue: 0,
    soulbound: true,
  },

  // Cinderweave Regalia: Intellect, Stamina, and Spirit cloth.
  cinderweave_cowl: {
    id: 'cinderweave_cowl',
    set: SET_WARFARE_CINDERWEAVE,
    name: 'Cinderweave Cowl',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 76, int: 8, sta: 6, spi: 3 },
    pvpOffenseRating: 18,
    pvpDefenseRating: 18,
    priceHonor: 900,
    sellValue: 0,
    soulbound: true,
  },
  cinderweave_mantle: {
    id: 'cinderweave_mantle',
    set: SET_WARFARE_CINDERWEAVE,
    name: 'Cinderweave Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 56, int: 6, sta: 5, spi: 3 },
    pvpOffenseRating: 16,
    pvpDefenseRating: 16,
    priceHonor: 700,
    sellValue: 0,
    soulbound: true,
  },
  cinderweave_raiment: {
    id: 'cinderweave_raiment',
    set: SET_WARFARE_CINDERWEAVE,
    name: 'Cinderweave Raiment',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 90, int: 10, sta: 7, spi: 3 },
    pvpOffenseRating: 22,
    pvpDefenseRating: 22,
    priceHonor: 1200,
    sellValue: 0,
    soulbound: true,
  },
  cinderweave_cord: {
    id: 'cinderweave_cord',
    set: SET_WARFARE_CINDERWEAVE,
    name: 'Cinderweave Cord',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 48, int: 5, sta: 5, spi: 4 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 450,
    sellValue: 0,
    soulbound: true,
  },
  cinderweave_legwraps: {
    id: 'cinderweave_legwraps',
    set: SET_WARFARE_CINDERWEAVE,
    name: 'Cinderweave Legwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 8, sta: 7, spi: 3 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
  },
  cinderweave_handwraps: {
    id: 'cinderweave_handwraps',
    set: SET_WARFARE_CINDERWEAVE,
    name: 'Cinderweave Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 52, int: 5, sta: 5, spi: 4 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 550,
    sellValue: 0,
    soulbound: true,
  },
  cinderweave_slippers: {
    id: 'cinderweave_slippers',
    set: SET_WARFARE_CINDERWEAVE,
    name: 'Cinderweave Slippers',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 44, int: 7, sta: 5, spi: 3 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 550,
    sellValue: 0,
    soulbound: true,
  },

  // Thornhide Garb, the leather caster family. Added after review: a druid's
  // maximum armor weight is LEATHER (equipment_rules.ts LEATHER_CLASSES), and the
  // only int/spi families were Stormbound (mail, unwearable) and Cinderweave
  // (cloth, a full rank below what the class can wear), so a caster druid was
  // giving up an armor rank to a content gap rather than to a decision. The
  // 7-piece capstone made that worse rather than better: before the sets existed
  // a druid could mix cloth and leather freely, and the capstone turned that
  // hedge into a forfeit.
  //
  // Stat identity is Cinderweave's, slot for slot, because the caster budget is
  // the caster budget. Armor is Ashstalker's, slot for slot, because armor is a
  // function of weight and item level, not of stat identity. No requiredClass:
  // these gate on armorType like every other WARFARE piece, so a rogue may equip
  // them and get nothing useful, exactly as with Cinderweave today.
  thornhide_headdress: {
    id: 'thornhide_headdress',
    set: SET_WARFARE_THORNHIDE,
    name: 'Thornhide Headdress',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 168, int: 8, sta: 6, spi: 3 },
    pvpOffenseRating: 18,
    pvpDefenseRating: 18,
    priceHonor: 900,
    sellValue: 0,
    soulbound: true,
  },
  thornhide_mantle: {
    id: 'thornhide_mantle',
    set: SET_WARFARE_THORNHIDE,
    name: 'Thornhide Mantle',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 148, int: 6, sta: 5, spi: 3 },
    pvpOffenseRating: 16,
    pvpDefenseRating: 16,
    priceHonor: 700,
    sellValue: 0,
    soulbound: true,
  },
  thornhide_vestment: {
    id: 'thornhide_vestment',
    set: SET_WARFARE_THORNHIDE,
    name: 'Thornhide Vestment',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 172, int: 10, sta: 7, spi: 3 },
    pvpOffenseRating: 22,
    pvpDefenseRating: 22,
    priceHonor: 1200,
    sellValue: 0,
    soulbound: true,
  },
  thornhide_cinch: {
    id: 'thornhide_cinch',
    set: SET_WARFARE_THORNHIDE,
    name: 'Thornhide Cinch',
    kind: 'armor',
    armorType: 'leather',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 100, int: 5, sta: 5, spi: 4 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 450,
    sellValue: 0,
    soulbound: true,
  },
  thornhide_leggings: {
    id: 'thornhide_leggings',
    set: SET_WARFARE_THORNHIDE,
    name: 'Thornhide Leggings',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 132, int: 8, sta: 7, spi: 3 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
  },
  thornhide_gloves: {
    id: 'thornhide_gloves',
    set: SET_WARFARE_THORNHIDE,
    name: 'Thornhide Gloves',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 104, int: 5, sta: 5, spi: 4 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 550,
    sellValue: 0,
    soulbound: true,
  },
  thornhide_boots: {
    id: 'thornhide_boots',
    set: SET_WARFARE_THORNHIDE,
    name: 'Thornhide Boots',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 96, int: 7, sta: 5, spi: 3 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 550,
    sellValue: 0,
    soulbound: true,
  },

  // Necklaces: one Strength, one Agility, and one caster profile. Jewelry carries
  // no set tag (it is shared across role profiles) and rides the lower
  // WARFARE_JEWELRY_STAT_FRACTION.
  final_oath_medallion: {
    id: 'final_oath_medallion',
    name: 'Medallion of the Final Oath',
    kind: 'armor',
    slot: 'neck',
    quality: 'epic',
    requiredLevel: 20,
    stats: { str: 6, sta: 5 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 400,
    sellValue: 0,
    soulbound: true,
  },
  razorwind_torque: {
    id: 'razorwind_torque',
    name: 'Razorwind Torque',
    kind: 'armor',
    slot: 'neck',
    quality: 'epic',
    requiredLevel: 20,
    stats: { agi: 6, sta: 5 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 400,
    sellValue: 0,
    soulbound: true,
  },
  cinder_sigil_pendant: {
    id: 'cinder_sigil_pendant',
    name: 'Cinder-Sigil Pendant',
    kind: 'armor',
    slot: 'neck',
    quality: 'epic',
    requiredLevel: 20,
    stats: { int: 6, sta: 5, spi: 1 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 400,
    sellValue: 0,
    soulbound: true,
  },

  // Rings: two distinct choices for each role profile.
  iron_vow_band: {
    id: 'iron_vow_band',
    name: 'Iron Vow Band',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { str: 4, sta: 6 },
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 275,
    sellValue: 0,
    soulbound: true,
  },
  unbroken_circle: {
    id: 'unbroken_circle',
    name: 'The Unbroken Circle',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { str: 6, sta: 4 },
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 275,
    sellValue: 0,
    soulbound: true,
  },
  fleetblood_band: {
    id: 'fleetblood_band',
    name: 'Fleetblood Band',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { agi: 6, sta: 4 },
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 275,
    sellValue: 0,
    soulbound: true,
  },
  last_step_signet: {
    id: 'last_step_signet',
    name: 'Last-Step Signet',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { agi: 4, sta: 6 },
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 275,
    sellValue: 0,
    soulbound: true,
  },
  ashen_focus_ring: {
    id: 'ashen_focus_ring',
    name: 'Ashen Focus Ring',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { int: 6, sta: 4, spi: 1 },
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 275,
    sellValue: 0,
    soulbound: true,
  },
  spellbreakers_seal: {
    id: 'spellbreakers_seal',
    name: "Spellbreaker's Seal",
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    requiredLevel: 20,
    stats: { int: 4, sta: 4, spi: 3 },
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 275,
    sellValue: 0,
    soulbound: true,
  },

  // Main hands: Strength, Agility, and caster profiles on the ilvl-31 DPS curve.
  // Deliberately a contested slot rather than one this tier owns: an ilvl-31
  // honor weapon cannot out-scale an ilvl-33 raid epic or an ilvl-37 legendary
  // at any WARFARE budget, and it is not meant to.
  final_argument_greatblade: {
    id: 'final_argument_greatblade',
    name: 'Final Argument Greatblade',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 36, max: 53, speed: 2.8 },
    stats: { str: 8, sta: 12 },
    pvpOffenseRating: 22,
    pvpDefenseRating: 22,
    priceHonor: 1200,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior', 'paladin', 'shaman'],
  },
  first_blood_razor: {
    id: 'first_blood_razor',
    name: 'First-Blood Razor',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 21, max: 33, speed: 1.7, dagger: true },
    stats: { agi: 8, sta: 12 },
    pvpOffenseRating: 22,
    pvpDefenseRating: 22,
    priceHonor: 1200,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue', 'hunter', 'druid'],
  },
  emberglass_warstaff: {
    id: 'emberglass_warstaff',
    name: 'Emberglass Warstaff',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 39, max: 57, speed: 3 },
    stats: { int: 10, sta: 7, spi: 3 },
    pvpOffenseRating: 22,
    pvpDefenseRating: 22,
    priceHonor: 1200,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage', 'priest', 'warlock', 'shaman', 'paladin', 'druid'],
  },
};

export const FURY_STOCK: readonly string[] = Object.keys(WARFARE_ITEMS);

export const FURY_NPC: NpcDef = {
  id: FURY_NPC_ID,
  name: 'FURY',
  title: 'Honor Quartermaster',
  pos: { ...EASTBROOK_NPC_PLACEMENTS_BY_ID.fury.position },
  facing: EASTBROOK_NPC_PLACEMENTS_BY_ID.fury.facing,
  color: 0xb52a2a,
  questIds: [],
  vendorItems: [...FURY_STOCK],
  dynamic: true,
  // The Eastbrook mirror sells the identical stock, so it presents the identical
  // set-divided shop window. One canonical stock, two placements.
  warfareVendor: true,
  greeting: 'The sands remember every victory. Spend your honor well.',
};
