import type { AbilityDef } from '../types';

/** Retained Talents V2 active grants: Hunter, Rogue, Priest, and Shaman. */
export const TALENT_ABILITIES_V2_A = {
  startle_shot: {
    id: 'startle_shot',
    name: 'Startle Shot',
    class: 'hunter',
    learnLevel: 8,
    cost: 25,
    castTime: 0,
    cooldown: 20,
    range: 35,
    minRange: 8,
    school: 'physical',
    scalesWith: 'ranged',
    requiresTarget: true,
    targetType: 'enemy',
    effects: [{ type: 'incapacitate', duration: 4 }],
    description: 'A wild shot that disorients the target for $t sec. Any damage breaks the effect.',
  },
  frost_trap: {
    id: 'frost_trap',
    name: 'Rime Snare',
    class: 'hunter',
    learnLevel: 10,
    cost: 35,
    castTime: 0,
    cooldown: 30,
    range: 0,
    school: 'frost',
    requiresTarget: false,
    // A real trap (G6, combat/hunter_trap.ts): placed at the hunter's feet,
    // arms after 1.5 sec, freezes the FIRST enemy that touches it, one trap
    // at a time. Was a 30yd aimed 8yd-radius instant root+stun nova.
    effects: [
      {
        type: 'aoeRoot',
        duration: 3,
        radius: 3,
        min: 0,
        max: 0,
        stun: true,
        trap: { armTime: 1.5, lifetime: 60 },
      },
    ],
    description:
      'Places a frost trap at your feet that arms after 1.5 sec. The first enemy to touch it is frozen for 3 sec, unable to move or act. One trap at a time. Lasts 60 sec. (Hunter talent)',
  },
  multi_shot: {
    id: 'multi_shot',
    name: 'Splitshot',
    class: 'hunter',
    learnLevel: 10,
    cost: 55,
    castTime: 0,
    cooldown: 8,
    range: 35,
    minRange: 8,
    school: 'physical',
    scalesWith: 'ranged',
    requiresTarget: false,
    targetMode: 'position',
    effects: [{ type: 'aoeDamage', min: 62, max: 74, radius: 8 }],
    description:
      'Loose a spread at the target area, dealing $d Physical damage to enemies within 8 yd. Cannot be aimed within 8 yd of you. (Hunter talent)',
  },
  deterrence: {
    id: 'deterrence',
    name: 'Bristleguard',
    class: 'hunter',
    learnLevel: 10,
    cost: 0,
    castTime: 0,
    cooldown: 300,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    offGcd: true,
    // Balance pass round two (maintainer): 5 min cooldown and 25% dodge (the
    // 50pp wall on 2 min was too much); the all-school damage cut stays so it
    // still works against casters.
    effects: [
      { type: 'selfBuff', kind: 'buff_dodge', value: 0.25, duration: 10 },
      { type: 'selfBuff', kind: 'buff_dr', value: 0.3, duration: 10 },
    ],
    description:
      'Increases your dodge chance by 25 percentage points and reduces all damage taken by 30% for 10 sec. (Hunter talent)',
  },
  aspect_of_the_wild: {
    id: 'aspect_of_the_wild',
    name: 'Wildfang Rally',
    class: 'hunter',
    learnLevel: 10,
    cost: 50,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'nature',
    requiresTarget: false,
    effects: [
      { type: 'aoeAllyAttackPower', amount: 45, duration: 300, radius: 30 },
      { type: 'aoeAllyHaste', mult: 1.05, duration: 300, radius: 30 },
    ],
    description:
      'Inspires allies within 30 yd with wild strength, increasing attack power by 45 and attack speed by 5% for 5 min. (Hunter talent)',
  },

  smoke_screen: {
    id: 'smoke_screen',
    tooltipOmitEffectLines: true,
    name: 'Smoke Screen',
    class: 'rogue',
    learnLevel: 8,
    cost: 25,
    castTime: 0,
    cooldown: 30,
    range: 0,
    requiresTarget: false,
    school: 'physical',
    effects: [{ type: 'selfBuff', kind: 'buff_dodge', value: 0.3, duration: 8 }],
    description: 'Vanish into a cloud of smoke, increasing your chance to dodge by 30% for 8 sec.',
  },
  flurry_of_knives: {
    id: 'flurry_of_knives',
    name: 'Flurry of Knives',
    class: 'rogue',
    learnLevel: 10,
    cost: 35,
    castTime: 0,
    cooldown: 45,
    range: 0,
    requiresTarget: false,
    school: 'physical',
    awardsCombo: 2,
    // Classic never-crits AoE path (no canCrit): zero extra rng per cast.
    effects: [{ type: 'aoeDamage', min: 48, max: 62, radius: 6 }],
    description:
      'Lash every enemy within 6 yd with thrown knives for $d Physical damage and gain 2 combo points. (Rogue talent)',
  },
  thieves_chorus: {
    id: 'thieves_chorus',
    name: "Thieves' Chorus",
    class: 'rogue',
    learnLevel: 10,
    cost: 25,
    castTime: 0,
    cooldown: 90,
    range: 0,
    requiresTarget: false,
    school: 'physical',
    // Shares the group haste-burst exhaustion (combat/haste_burst.ts) so it can
    // never be chained with Storm Chorus or Temporal Acceleration.
    effects: [
      {
        type: 'aoeAllyHaste',
        mult: 1.1,
        duration: 10,
        radius: 30,
        spell: true,
        exhaust: true,
        groupOnly: true,
      },
    ],
    description:
      'A whistled signal spurs your group on, increasing attack, casting, and channeling speed by 10% for 10 sec. Allies recently affected by a group haste burst are too exhausted to benefit. (Rogue talent)',
  },
  venomrend: {
    id: 'venomrend',
    name: 'Venomrend',
    class: 'rogue',
    learnLevel: 10,
    cost: 30,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    spendsCombo: true,
    // The armed Venom Ritual: Dirt Nap transforms into this at 6 stages
    // (actionReplacement on eviscerate); casting consumes the whole ritual.
    // Six stages against a five-thrust combo cycle means the finisher
    // alternates Dirt Nap, then Venomrend: the two-beat rhythm.
    requiresAuraKind: 'venom_ritual',
    requiresAuraStacks: 6,
    // Owner playtest pass: the detonation is self-sustaining. It consumes
    // every bleed (including the wound it opened last time), then reopens the
    // wound itself, so the player never juggles Bleed Out upkeep against the
    // ritual cadence. Consumes fire before the fresh dot applies. Sized for
    // landing every OTHER full finisher (Dirt Nap covers the off-beat).
    effects: [
      { type: 'finisherDamage', base: 100, perCombo: 55, variance: 12 },
      { type: 'consumeDot', dot: 'rupture' },
      { type: 'consumeDot', dot: 'garrote' },
      { type: 'consumeDot', dot: 'venomrend' },
      { type: 'dot', total: 120, duration: 20, interval: 2 },
      { type: 'gainResource', amount: 20 },
    ],
    description:
      'Spends your 6 Venom Ritual: strike for 100 plus 55 per combo point, instantly deal all the damage your bleeds would still have dealt, then apply a fresh venom wound (120 damage over 20 sec). Restores 20 energy. (Knifework)',
  },
  body_blow: {
    id: 'body_blow',
    name: 'Haymaker',
    class: 'rogue',
    learnLevel: 10,
    cost: 35,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    awardsCombo: 2,
    // The Redline builder: Wicked Slash transforms into this while the window
    // runs (actionReplacement on sinister_strike). Each landing deepens the
    // run by one pip (rogueEngineOnCast), feeding the Knockout cash-out.
    effects: [{ type: 'weaponStrike', bonus: 10, weaponMult: 1.3, normalized: true }],
    description:
      'A heavy blow for 130% weapon damage plus 10. Awards 2 combo points and adds 1 Redline (max 4). (Thuggery)',
  },
  knockout_blow: {
    id: 'knockout_blow',
    name: 'Lights Out',
    class: 'rogue',
    learnLevel: 10,
    cost: 30,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    spendsCombo: true,
    // The Redline cash-out: Dirt Nap transforms into this while the window
    // runs. The pip multiplier and the run-ending consumption live in the
    // engine module (knockoutRedlineMult at the finisherDamage case), so a
    // window that expires first forfeits the Knockout entirely.
    effects: [
      { type: 'finisherDamage', base: 45, perCombo: 35, variance: 12 },
      { type: 'gainResource', amount: 25 },
    ],
    description:
      'Ends Redline with a knockout: strike for 45 plus 35 per combo point, hitting 25% harder for each Redline you built, and recover 25 energy. Use it before Redline runs out or the knockout is lost. (Thuggery)',
  },
  veilstrike: {
    id: 'veilstrike',
    tooltipOmitEffectLines: true,
    name: 'Shadow Veil',
    class: 'rogue',
    learnLevel: 10,
    cost: 0,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'shadow',
    requiresTarget: false,
    // Never learned or castable: this def is the display card (icon, name,
    // tooltip) for the veil aura the engine raises when a Duskveil opener
    // detonates a full Gloam bank (rogueGloamDetonation). The owner cut the
    // transformed stealth button: the openers themselves are the trigger,
    // and the Veiled Edge is applied by the same engine hook.
    effects: [{ type: 'selfBuff', kind: 'buff_dmg_done', value: 0.1, duration: 6 }],
    description:
      "For 6 sec: your Duskveil openers work without stealth and from any angle, you deal 10% more damage, and your first Lurker's Strike inside it hits for double. (Skulduggery)",
  },
  preparation: {
    id: 'preparation',
    name: 'Contingency',
    class: 'rogue',
    learnLevel: 10,
    cost: 0,
    castTime: 0,
    cooldown: 300,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    offGcd: true,
    effects: [{ type: 'clearCooldowns', abilities: ['sprint', 'evasion', 'vanish'] }],
    description: 'Finishes the cooldown on Swift Heels, Ghostfoot, and Smokefade. (Rogue talent)',
  },
  ghostly_strike: {
    id: 'ghostly_strike',
    tooltipOmitEffectLines: true,
    name: 'Wraith Strike',
    class: 'rogue',
    learnLevel: 10,
    cost: 40,
    castTime: 0,
    cooldown: 20,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    awardsCombo: 1,
    effects: [
      { type: 'weaponStrike', bonus: 18 },
      { type: 'selfBuff', kind: 'buff_dodge', value: 0.15, duration: 7 },
    ],
    description:
      'Strikes the enemy for weapon damage plus $d and increases your dodge chance by 15% for 7 sec. Awards 1 combo point. (Rogue talent)',
  },
  cloak_of_shadows: {
    id: 'cloak_of_shadows',
    name: 'Shadecloak',
    class: 'rogue',
    learnLevel: 10,
    cost: 0,
    castTime: 0,
    cooldown: 90,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    offGcd: true,
    effects: [{ type: 'absorb', amount: 420, duration: 5 }],
    description: 'Wraps you in shadows, absorbing 420 damage for 5 sec. (Rogue talent)',
  },
  shadowstep: {
    id: 'shadowstep',
    name: 'Shadeslip',
    class: 'rogue',
    learnLevel: 10,
    cost: 20,
    castTime: 0,
    cooldown: 24,
    range: 24,
    school: 'physical',
    requiresTarget: true,
    // Repositioning, not an attack: the step acts on the caster only, so it
    // resolves against an ALLY exactly as it does against an enemy (peeling to
    // a healer, closing on a flag carrier). 'any' routes it through the
    // casting_lifecycle branch that accepts either side.
    targetType: 'any',
    effects: [{ type: 'blinkForward', distance: 24 }],
    description:
      'Steps through the shadows to your target, friend or foe, without breaking Duskveil. (Rogue talent)',
  },

  silence: {
    id: 'silence',
    name: 'Hushword',
    class: 'priest',
    learnLevel: 10,
    cost: 55,
    castTime: 0,
    cooldown: 30,
    range: 30,
    school: 'shadow',
    requiresTarget: true,
    effects: [{ type: 'silence', duration: 4 }],
    description: 'Silences the target for 4 sec. (Priest talent)',
  },
  psychic_scream: {
    id: 'psychic_scream',
    name: 'Terror Canticle',
    class: 'priest',
    learnLevel: 10,
    cost: 45,
    castTime: 0,
    cooldown: 30,
    range: 0,
    school: 'shadow',
    requiresTarget: false,
    effects: [{ type: 'aoeFear', duration: 4, radius: 8 }],
    description: 'Frighten enemies within 8 yards for up to 4 sec. Damage may break the effect.',
  },
  inner_focus: {
    id: 'inner_focus',
    name: 'Stilled Mind',
    class: 'priest',
    learnLevel: 10,
    cost: 0,
    castTime: 0,
    cooldown: 90,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [
      { type: 'selfBuff', kind: 'next_cast_free', value: 1, duration: 60 },
      { type: 'selfBuff', kind: 'cast_shield', value: 1, duration: 60 },
    ],
    description: 'Makes your next Priest spell free and uninterruptible. Lasts 60 sec.',
  },
  desperate_prayer: {
    id: 'desperate_prayer',
    name: 'Last Prayer',
    class: 'priest',
    learnLevel: 10,
    cost: 0,
    castTime: 0,
    cooldown: 90,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'selfHealPctMax', pct: 0.3 }],
    description: 'Instantly heals you for 30% of maximum health.',
  },
  prayer_of_healing: {
    id: 'prayer_of_healing',
    name: 'Choirmend',
    class: 'priest',
    specs: ['holy'],
    learnLevel: 10,
    cost: 130,
    castTime: 3,
    cooldown: 0,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'aoeHeal', min: 100, max: 122, radius: 30 }],
    ranks: [
      {
        rank: 2,
        level: 20,
        cost: 170,
        effects: [{ type: 'aoeHeal', min: 145, max: 177, radius: 30 }],
      },
    ],
    description:
      'Heal allies within 30 yards for $d. Healing increases with Spell Power. (Benison)',
  },
  mind_sear: {
    id: 'mind_sear',
    name: 'Thoughtburn',
    class: 'priest',
    learnLevel: 10,
    cost: 95,
    castTime: 0,
    channel: { duration: 3, ticks: 3 },
    cooldown: 0,
    range: 30,
    school: 'shadow',
    requiresTarget: false,
    targetMode: 'position',
    effects: [{ type: 'aoeDamage', min: 24, max: 28, radius: 8 }],
    description:
      'Channel for 3 sec, dealing $d Shadow damage each second to enemies within 8 yards of the target area. Damage increases with Spell Power. (Priest talent)',
  },

  healing_stream: {
    id: 'healing_stream',
    name: 'Springwell',
    class: 'shaman',
    learnLevel: 10,
    cost: 45,
    castTime: 0,
    cooldown: 0,
    range: 30,
    school: 'nature',
    requiresTarget: true,
    targetType: 'friendly',
    effects: [{ type: 'hot', total: 120, duration: 12, interval: 3 }],
    description: 'Restores 120 health to a friendly target over 12 sec. (Shaman talent)',
  },
  chain_lightning: {
    id: 'chain_lightning',
    name: 'Skybranch',
    class: 'shaman',
    specs: ['elemental'],
    learnLevel: 14,
    cost: 80,
    castTime: 2.5,
    cooldown: 6,
    range: 30,
    school: 'nature',
    requiresTarget: true,
    effects: [
      {
        type: 'chainDamage',
        min: 52,
        max: 60,
        jumps: 2,
        falloff: 1,
        radius: 10,
        hitsPrimary: true,
      },
    ],
    description:
      'Strike up to 3 enemies within 10 yards for $d Nature damage each. Thundercall: a hit grants 1 Thunder. Damage increases with Spell Power.',
  },
  earthbind: {
    id: 'earthbind',
    name: 'Gripping Earth',
    class: 'shaman',
    learnLevel: 10,
    cost: 45,
    castTime: 0,
    cooldown: 30,
    range: 30,
    school: 'nature',
    requiresTarget: false,
    targetMode: 'position',
    effects: [{ type: 'aoeRoot', duration: 2, radius: 4, min: 0, max: 0 }],
    description:
      'Roots enemies within 4 yd of the target point for 2 sec, then slows them by 40% for 6 sec. (Shaman talent)',
  },
  stoneward: {
    id: 'stoneward',
    name: 'Stoneward',
    class: 'shaman',
    learnLevel: 8,
    cost: 40,
    castTime: 0,
    cooldown: 0,
    range: 30,
    school: 'nature',
    requiresTarget: true,
    targetType: 'friendly',
    effects: [],
    description:
      'Protects one ally for 60 sec with 6 charges. Damage consumes a charge to heal 5% maximum health, once every 3 sec. (Shaman talent)',
  },
  primal_exaltation: {
    id: 'primal_exaltation',
    name: 'Primal Exaltation',
    class: 'shaman',
    learnLevel: 17,
    cost: 0,
    castTime: 0,
    cooldown: 120,
    range: 0,
    school: 'nature',
    requiresTarget: false,
    effects: [],
    description:
      'For 12 sec, Thundercall Arc Bolt and Skybranch cast 50% faster, while Arc Bolt grants 2 Thunder; Warspirit triggers its cadence every 2 weapon hits; Spiritcall adds 50% more healing to Mending Current. (Shaman talent)',
  },
  bloodlust: {
    id: 'bloodlust',
    name: 'Storm Chorus',
    class: 'shaman',
    learnLevel: 20,
    cost: 85,
    castTime: 0,
    cooldown: 300,
    range: 0,
    school: 'nature',
    requiresTarget: false,
    // Full haste (attack, cast, and channel) to the group/raid, with the shared
    // exhaustion so it can never be chained with Temporal Acceleration (combat/
    // haste_burst.ts). Owner directive 2026-07-13: convert the shared effect to
    // full haste so caster/healer allies benefit, not only melee.
    effects: [
      {
        type: 'aoeAllyHaste',
        mult: 1.3,
        duration: 15,
        radius: 30,
        spell: true,
        exhaust: true,
        groupOnly: true,
      },
    ],
    description:
      'Increase the attack, casting, and channeling speed of group or raid allies within 30 yards by 30% for 15 sec. Affected allies cannot benefit from Storm Chorus or Temporal Acceleration again for 10 min. (Shaman talent)',
  },
} satisfies Record<string, AbilityDef>;
