// Rift creature pool: the static MobTemplate library the procedural generator
// (src/sim/rift/rift_gen.ts) draws from. These MUST be static entries in the
// merged MOBS table because per-tick mob mechanics are read from
// MOBS[entity.templateId] (see src/sim/mob/locomotion.ts). Infinite variety
// comes from the GENERATOR selecting, theming, re-tinting (entity.color),
// re-scaling (entity.scale) and level-scaling these building blocks, not from
// spawning ad-hoc templates.
//
// Stat lines mirror the hand-authored dungeon elites in ../dungeons.ts so a rift
// stays inside the same balance envelope. Every boss carries a DISTINCT mechanic
// signature so "noticeably different bosses each run" holds, and lists its
// headline mechanics in `rankMechanics` unlock order so the portal rank sets how
// many are live (C=1 .. S=4, src/sim/rift/ranks.ts). Loot: coin plus each
// environment's signature rare (./items.ts) at a slim rate on trash and a fat
// one on its boss, and a Rift Essence trickle, so every run (ranked or dev) has
// real itemisation; the ranked first-clear rings ride rift/progression.ts on top.
//
// Level band note: rift spawn levels are chosen by the generator
// (rift/ranks.ts riftFloorLevel, 18..RIFT_MAX_MOB_LEVEL), so the bands here are
// metadata, not a spawn range. They matter to item_level.buildSourceIndex
// (drops read "current at the top of the dropping mob's band", so 60 would
// misprice every rift rare) and to the deeds creditable-level analysis.

import type { LootEntry, MobTemplate } from '../../types';
import { RIFT_ESSENCE_ITEM_ID } from './items';

/** Trash loot: coin, a slim shot at the environment's signature rare, and a
 * trickle of Rift Essence so clearing packs pays even outside a ranked race. */
const trashLoot = (c: number, rareId: string): LootEntry[] => [
  { copper: c, chance: 1 },
  { itemId: rareId, chance: 0.02 },
  { itemId: RIFT_ESSENCE_ITEM_ID, chance: 0.05 },
];
/** Boss loot: coin, a fat shot at the environment's signature rare, and a
 * guaranteed-plus-bonus essence payout. */
const bossLoot = (c: number, rareId: string, rareChance: number): LootEntry[] => [
  { copper: c, chance: 1 },
  { itemId: rareId, chance: rareChance },
  { itemId: RIFT_ESSENCE_ITEM_ID, chance: 1 },
  { itemId: RIFT_ESSENCE_ITEM_ID, chance: 0.5 },
];

// Shared summoned adds (referenced by bosses' summonAdds.mobId). Low HP, no loot.
const ADDS: Record<string, MobTemplate> = {
  rift_spawnling: {
    id: 'rift_spawnling',
    name: 'Rift Spawnling',
    minLevel: 18,
    maxLevel: 23,
    family: 'demon',
    hpBase: 30,
    hpPerLevel: 11,
    dmgBase: 6,
    dmgPerLevel: 1.9,
    attackSpeed: 1.8,
    armorPerLevel: 10,
    moveSpeed: 7.5,
    aggroRadius: 12,
    loot: [],
    scale: 0.85,
    color: 0x9b59b6,
    xpMult: 0.25,
  },
  rift_bonewalker: {
    id: 'rift_bonewalker',
    name: 'Risen Bonewalker',
    minLevel: 18,
    maxLevel: 23,
    family: 'undead',
    hpBase: 34,
    hpPerLevel: 12,
    dmgBase: 7,
    dmgPerLevel: 2.0,
    attackSpeed: 2.0,
    armorPerLevel: 12,
    moveSpeed: 7,
    aggroRadius: 12,
    loot: [],
    scale: 0.95,
    color: 0xc8cfc8,
    xpMult: 0.25,
  },
};

// ---- Trash: two per environment family, spanning distinct render models ----
const TRASH: Record<string, MobTemplate> = {
  // Frostbound (undead + elemental, blue/white)
  rift_frost_revenant: {
    id: 'rift_frost_revenant',
    name: 'Frostbound Revenant',
    minLevel: 18,
    maxLevel: 23,
    family: 'undead',
    elite: true,
    hpBase: 50,
    hpPerLevel: 20,
    dmgBase: 8,
    dmgPerLevel: 2.3,
    attackSpeed: 2.3,
    armorPerLevel: 18,
    moveSpeed: 6.5,
    aggroRadius: 12,
    loot: trashLoot(120, 'hoarfrost_edge'),
    scale: 1.1,
    color: 0xbfe3ff,
    chillOnHit: { chance: 0.35, mult: 0.6, duration: 4, name: 'Rimebite' },
  },
  rift_rime_elemental: {
    id: 'rift_rime_elemental',
    name: 'Rime Elemental',
    minLevel: 18,
    maxLevel: 23,
    family: 'elemental',
    elite: true,
    hpBase: 54,
    hpPerLevel: 21,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 2.6,
    armorPerLevel: 14,
    moveSpeed: 7,
    aggroRadius: 12,
    loot: trashLoot(130, 'hoarfrost_edge'),
    scale: 1.15,
    color: 0x8fd8ff,
    frostbite: { chance: 0.3, perTick: 6, interval: 2, duration: 8, name: 'Rime' },
  },
  // Emberforge (demon + elemental, orange/red)
  rift_ember_fiend: {
    id: 'rift_ember_fiend',
    name: 'Ember Fiend',
    minLevel: 18,
    maxLevel: 23,
    family: 'demon',
    elite: true,
    hpBase: 48,
    hpPerLevel: 19,
    dmgBase: 9,
    dmgPerLevel: 2.5,
    attackSpeed: 2.0,
    armorPerLevel: 14,
    moveSpeed: 7.5,
    aggroRadius: 13,
    loot: trashLoot(130, 'emberforge_gauntlets'),
    scale: 1.0,
    color: 0xff7a3c,
    cinder: { chance: 0.3, perTick: 7, interval: 2, duration: 8, name: 'Cinders' },
  },
  rift_magma_brute: {
    id: 'rift_magma_brute',
    name: 'Magma Brute',
    minLevel: 18,
    maxLevel: 23,
    family: 'elemental',
    elite: true,
    hpBase: 58,
    hpPerLevel: 22,
    dmgBase: 10,
    dmgPerLevel: 2.6,
    attackSpeed: 2.6,
    armorPerLevel: 20,
    moveSpeed: 6.5,
    aggroRadius: 12,
    loot: trashLoot(150, 'emberforge_gauntlets'),
    scale: 1.25,
    color: 0xd84a2a,
    smolder: { chance: 0.25, perTick: 9, interval: 2, duration: 6, name: 'Smoulder' },
  },
  // Venomweald (spider + beast, green)
  rift_venom_weaver: {
    id: 'rift_venom_weaver',
    name: 'Venom Weaver',
    minLevel: 18,
    maxLevel: 23,
    family: 'spider',
    elite: true,
    hpBase: 46,
    hpPerLevel: 18,
    dmgBase: 8,
    dmgPerLevel: 2.3,
    attackSpeed: 1.8,
    armorPerLevel: 12,
    moveSpeed: 8,
    aggroRadius: 13,
    loot: trashLoot(120, 'broodmother_carapace'),
    scale: 1.2,
    color: 0x9acd32,
    venom: { chance: 0.35, perTick: 8, interval: 2, duration: 8, name: 'Venom' },
    ensnare: { chance: 0.2, duration: 2, name: 'Web' },
  },
  rift_thornback: {
    id: 'rift_thornback',
    name: 'Thornback Stalker',
    minLevel: 18,
    maxLevel: 23,
    family: 'beast',
    elite: true,
    hpBase: 52,
    hpPerLevel: 20,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 1.9,
    armorPerLevel: 16,
    moveSpeed: 8.5,
    aggroRadius: 13,
    loot: trashLoot(130, 'broodmother_carapace'),
    scale: 1.1,
    color: 0x6b8e23,
    bleed: { chance: 0.3, perTick: 7, interval: 2, duration: 8, name: 'Serration' },
    frenzyOnHit: { chance: 0.25, hasteMult: 1.3, duration: 5 },
  },
  // Boneyard (undead + troll, bone-white/grey)
  rift_boneclad: {
    id: 'rift_boneclad',
    name: 'Boneclad Warrior',
    minLevel: 18,
    maxLevel: 23,
    family: 'undead',
    elite: true,
    hpBase: 56,
    hpPerLevel: 22,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.3,
    armorPerLevel: 24,
    moveSpeed: 6.5,
    aggroRadius: 12,
    loot: trashLoot(140, 'bonelord_mantle'),
    scale: 1.15,
    color: 0xcfc8b0,
    cleave: { radius: 7, mult: 0.5, name: 'Sweeping Arc' },
  },
  rift_marrow_troll: {
    id: 'rift_marrow_troll',
    name: 'Marrow Troll',
    minLevel: 18,
    maxLevel: 23,
    family: 'troll',
    elite: true,
    hpBase: 62,
    hpPerLevel: 23,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.7,
    armorPerLevel: 18,
    moveSpeed: 7,
    aggroRadius: 12,
    loot: trashLoot(160, 'bonelord_mantle'),
    scale: 1.2,
    color: 0x8a9a5b,
    frenzyOnHit: { chance: 0.3, hasteMult: 1.35, duration: 6 },
  },
  // Voidscar (demon + humanoid caster, violet)
  rift_void_acolyte: {
    id: 'rift_void_acolyte',
    name: 'Voidscar Acolyte',
    minLevel: 18,
    maxLevel: 23,
    family: 'humanoid',
    elite: true,
    hpBase: 46,
    hpPerLevel: 18,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 2.0,
    armorPerLevel: 12,
    moveSpeed: 7,
    aggroRadius: 12,
    loot: trashLoot(130, 'voidscar_handwraps'),
    scale: 1.0,
    color: 0x8e44ad,
    manaBurn: { chance: 0.3, amount: 120, name: 'Mana Burn' },
    arcaneRot: { chance: 0.25, perTick: 8, interval: 2, duration: 8, name: 'Void Rot' },
  },
  rift_dread_stalker: {
    id: 'rift_dread_stalker',
    name: 'Dread Stalker',
    minLevel: 18,
    maxLevel: 23,
    family: 'demon',
    elite: true,
    hpBase: 50,
    hpPerLevel: 20,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.1,
    armorPerLevel: 16,
    moveSpeed: 8,
    aggroRadius: 13,
    loot: trashLoot(140, 'voidscar_handwraps'),
    scale: 1.05,
    color: 0x5b2c6f,
    dread: { chance: 0.15, duration: 3, name: 'Dread' },
    lifeleech: { healFrac: 0.3, name: 'Siphon' },
  },
  // Stormspire (elemental + dragonkin, cyan/gold)
  rift_storm_caller: {
    id: 'rift_storm_caller',
    name: 'Storm Caller',
    minLevel: 18,
    maxLevel: 23,
    family: 'elemental',
    elite: true,
    hpBase: 50,
    hpPerLevel: 20,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.4,
    armorPerLevel: 14,
    moveSpeed: 7,
    aggroRadius: 13,
    loot: trashLoot(140, 'stormscale_treads'),
    scale: 1.1,
    color: 0x48d1cc,
    concuss: { chance: 0.2, duration: 1.5, name: 'Thunderclap' },
  },
  rift_stormscale: {
    id: 'rift_stormscale',
    name: 'Stormscale Drake',
    minLevel: 18,
    maxLevel: 23,
    family: 'dragonkin',
    elite: true,
    hpBase: 60,
    hpPerLevel: 23,
    dmgBase: 11,
    dmgPerLevel: 2.7,
    attackSpeed: 2.2,
    armorPerLevel: 22,
    moveSpeed: 7.5,
    aggroRadius: 13,
    loot: trashLoot(160, 'stormscale_treads'),
    scale: 1.35,
    color: 0x2e86c1,
    knockback: { chance: 0.2, distance: 6, name: 'Tail Sweep' },
  },
  // Sunken (mudfin + beast, teal)
  rift_tide_thrall: {
    id: 'rift_tide_thrall',
    name: 'Tide Thrall',
    minLevel: 18,
    maxLevel: 23,
    family: 'mudfin',
    elite: true,
    hpBase: 52,
    hpPerLevel: 20,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 2.2,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 12,
    canSwim: true,
    loot: trashLoot(130, 'abyssal_loop'),
    scale: 1.1,
    color: 0x17a589,
    lifeleech: { healFrac: 0.25, chance: 0.5, name: 'Drown' },
  },
  rift_deep_lurker: {
    id: 'rift_deep_lurker',
    name: 'Deep Lurker',
    minLevel: 18,
    maxLevel: 23,
    family: 'burrower',
    elite: true,
    hpBase: 48,
    hpPerLevel: 19,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 2.0,
    armorPerLevel: 14,
    moveSpeed: 7.5,
    aggroRadius: 12,
    loot: trashLoot(130, 'abyssal_loop'),
    scale: 1.0,
    color: 0x148f77,
    corrode: { chance: 0.25, armor: 60, maxStacks: 4, duration: 12, name: 'Corrode' },
  },
  // Ogre bruisers (shared brute trash)
  rift_stone_ogre: {
    id: 'rift_stone_ogre',
    name: 'Stone Ogre',
    minLevel: 18,
    maxLevel: 23,
    family: 'ogre',
    elite: true,
    hpBase: 64,
    hpPerLevel: 24,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.8,
    armorPerLevel: 26,
    moveSpeed: 6.5,
    aggroRadius: 12,
    loot: trashLoot(170, 'graskbreaker_girdle'),
    scale: 1.3,
    color: 0x9b8f6f,
    stunOnHit: { chance: 0.15, duration: 1.2, name: 'Crush' },
  },
  // The Infernal Citadel set-piece (demon guards + the pact cult that binds them).
  rift_hellguard: {
    id: 'rift_hellguard',
    name: 'Hellguard',
    minLevel: 18,
    maxLevel: 23,
    family: 'demon',
    elite: true,
    hpBase: 60,
    hpPerLevel: 23,
    dmgBase: 11,
    dmgPerLevel: 2.7,
    attackSpeed: 2.4,
    armorPerLevel: 22,
    moveSpeed: 7,
    aggroRadius: 13,
    loot: trashLoot(160, 'pactbound_vestments'),
    scale: 1.25,
    color: 0xc23a1a,
    cleave: { radius: 7, mult: 0.5, name: 'Pitsteel Sweep' },
    smolder: { chance: 0.25, perTick: 8, interval: 2, duration: 8, name: 'Searing Brand' },
  },
  rift_pact_acolyte: {
    id: 'rift_pact_acolyte',
    name: 'Pact Acolyte',
    minLevel: 18,
    maxLevel: 23,
    family: 'undead',
    elite: true,
    hpBase: 44,
    hpPerLevel: 17,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 2.2,
    armorPerLevel: 12,
    moveSpeed: 7,
    aggroRadius: 14,
    loot: trashLoot(140, 'pactbound_vestments'),
    scale: 1.0,
    color: 0x7a1020,
    soulrot: { chance: 0.25, perTick: 7, interval: 2, duration: 8, name: 'Pact Rot' },
  },
};

// ---- Bosses: one per environment, each a DISTINCT mechanic signature ----
// GIGA-tier: each is a towering (scale ~2.6-3.3), raid-grade end boss with
// raid-boss HP, ccImmune + slowImmune (never trivially locked down), a hard
// enrage at 30%, and 2-3 layered mechanics. Meant to be a real climactic fight,
// still beatable (the original "balanced & possible" goal holds; /dev god helps
// solo testers). The generator scales HP/damage by floor level on top of this.
const BOSSES: Record<string, MobTemplate> = {
  // Frostbound: anti-kite frost boss (slow aura + frost pulse)
  rift_boss_frost: {
    id: 'rift_boss_frost',
    name: 'Hoarfrost Warden',
    minLevel: 18,
    maxLevel: 23,
    family: 'undead',
    elite: true,
    boss: true,
    ccImmune: true,
    slowImmune: true,
    hpBase: 700,
    hpPerLevel: 60,
    dmgBase: 16,
    dmgPerLevel: 3.2,
    attackSpeed: 2.5,
    armorPerLevel: 30,
    moveSpeed: 7,
    aggroRadius: 18,
    loot: bossLoot(5000, 'hoarfrost_edge', 0.35),
    scale: 2.7,
    color: 0xd6f0ff,
    aoePulse: {
      min: 18,
      max: 28,
      radius: 12,
      every: 9,
      name: 'Glacial Burst',
      school: 'frost',
      fx: 'nova',
    },
    aoeSlow: { radius: 32, mult: 0.4, duration: 4, every: 12, name: 'Howling Gale' },
    stoneskin: { amount: 700, every: 16, duration: 6, name: 'Glacial Carapace', school: 'frost' },
    bigCast: {
      castId: 'rift_whiteout',
      name: 'Whiteout',
      castTime: 2.5,
      every: 16,
      radius: 14,
      min: 30,
      max: 44,
      school: 'frost',
      yell: 'The white wind rises.',
    },
    deathZoneCast: {
      castId: 'rift_frost_execution',
      name: 'Glacial Grave',
      castTime: 4.0,
      every: 22,
      radius: 9,
      school: 'frost',
      yell: 'The frost claims you.',
      detonateText: 'Glacial Grave detonates!',
    },
    deathZoneStrike: {
      castId: 'rift_frost_strike',
      name: 'Absolute Zero',
      castTime: 5.0,
      every: 26,
      radius: 11,
      school: 'frost',
      yell: 'Nothing survives the deep cold.',
      detonateText: 'Absolute Zero erupts!',
    },
    rankMechanics: ['aoePulse', 'aoeSlow', 'deathZoneCast', 'deathZoneStrike'],
    enrage: { belowHpPct: 0.3, dmgMult: 1.4, hasteMult: 1.25 },
    yells: { engage: 'The cold takes all things in the end.', enrage: 'FREEZE!' },
  },
  // Emberforge: telegraphed fire nova + enrage
  rift_boss_ember: {
    id: 'rift_boss_ember',
    name: 'Emberforge Tyrant',
    minLevel: 18,
    maxLevel: 23,
    family: 'demon',
    elite: true,
    boss: true,
    ccImmune: true,
    slowImmune: true,
    hpBase: 720,
    hpPerLevel: 62,
    dmgBase: 17,
    dmgPerLevel: 3.3,
    attackSpeed: 2.6,
    armorPerLevel: 28,
    moveSpeed: 7,
    aggroRadius: 18,
    loot: bossLoot(5000, 'emberforge_gauntlets', 0.35),
    scale: 2.9,
    color: 0xff6b2c,
    bigCast: {
      castId: 'rift_pyre',
      name: 'Pyroclasm',
      castTime: 2.5,
      every: 14,
      radius: 14,
      min: 30,
      max: 44,
      school: 'fire',
      yell: 'BURN.',
    },
    cinder: { chance: 0.4, perTick: 12, interval: 2, duration: 8, name: 'Cinders' },
    aoePulse: {
      min: 16,
      max: 24,
      radius: 11,
      every: 10,
      name: 'Cinder Wave',
      school: 'fire',
      fx: 'nova',
    },
    stomp: {
      radius: 10,
      every: 13,
      duration: 1.2,
      min: 18,
      max: 28,
      name: 'Magma Crash',
      school: 'fire',
    },
    summonAdds: { mobId: 'rift_spawnling', count: 2, atHpPct: [0.6, 0.3] },
    deathZoneCast: {
      castId: 'rift_ember_execution',
      name: 'Magma Well',
      castTime: 3.5,
      every: 22,
      radius: 9,
      school: 'fire',
      yell: 'The magma rises.',
      detonateText: 'Magma Well erupts!',
    },
    deathZoneStrike: {
      castId: 'rift_ember_strike',
      name: 'Core Meltdown',
      castTime: 4.0,
      every: 26,
      radius: 11,
      school: 'fire',
      yell: 'THE FORGE CONSUMES ALL.',
      detonateText: 'Core Meltdown detonates!',
    },
    rankMechanics: ['bigCast', 'aoePulse', 'deathZoneCast', 'deathZoneStrike'],
    enrage: { belowHpPct: 0.3, dmgMult: 1.5, hasteMult: 1.3 },
    yells: {
      engage: 'The forge hungers.',
      summon: 'Rise from the slag!',
      enrage: 'ASH AND CINDER!',
    },
  },
  // Venomweald: summoner with venom
  rift_boss_venom: {
    id: 'rift_boss_venom',
    name: 'Broodmother Vysska',
    minLevel: 18,
    maxLevel: 23,
    family: 'spider',
    elite: true,
    boss: true,
    ccImmune: true,
    slowImmune: true,
    hpBase: 680,
    hpPerLevel: 58,
    dmgBase: 16,
    dmgPerLevel: 3.2,
    attackSpeed: 1.9,
    armorPerLevel: 24,
    moveSpeed: 7.5,
    aggroRadius: 18,
    loot: bossLoot(5000, 'broodmother_carapace', 0.35),
    scale: 2.8,
    color: 0x7cb342,
    summonAdds: { mobId: 'rift_spawnling', count: 3, atHpPct: [0.75, 0.5, 0.25] },
    stackPoison: {
      chance: 0.5,
      perTick: 7,
      interval: 2,
      duration: 10,
      maxStacks: 6,
      name: 'Deadly Venom',
    },
    ensnare: { chance: 0.25, duration: 1.0, name: 'Web' },
    aoeSlow: { radius: 30, mult: 0.5, duration: 4, every: 12, name: 'Clinging Silk' },
    aoePulse: {
      min: 16,
      max: 26,
      radius: 12,
      every: 9,
      name: 'Venom Spray',
      school: 'nature',
      fx: 'nova',
    },
    bigCast: {
      castId: 'rift_venom_deluge',
      name: 'Venom Deluge',
      castTime: 2.2,
      every: 15,
      radius: 13,
      min: 26,
      max: 38,
      school: 'nature',
      yell: 'Drown in venom!',
    },
    deathZoneCast: {
      castId: 'rift_venom_execution',
      name: 'Venom Pool',
      castTime: 4.5,
      every: 22,
      radius: 9,
      school: 'nature',
      yell: 'Drown in poison.',
      detonateText: 'Venom Pool erupts!',
    },
    deathZoneStrike: {
      castId: 'rift_venom_strike',
      name: "Broodmother's Mark",
      castTime: 5.0,
      every: 26,
      radius: 11,
      school: 'nature',
      yell: 'YOU CANNOT FLEE MY CHILDREN.',
      detonateText: "Broodmother's Mark detonates!",
    },
    rankMechanics: ['summonAdds', 'aoeSlow', 'deathZoneCast', 'deathZoneStrike'],
    enrage: { belowHpPct: 0.3, dmgMult: 1.4, hasteMult: 1.25 },
    yells: { engage: 'My children are always hungry.', summon: 'Feast, little ones!' },
  },
  // Boneyard: necrotic summoner + soulrot + desperate heal
  rift_boss_necro: {
    id: 'rift_boss_necro',
    name: 'Bonelord Xarreth',
    minLevel: 18,
    maxLevel: 23,
    family: 'undead',
    elite: true,
    boss: true,
    ccImmune: true,
    slowImmune: true,
    hpBase: 700,
    hpPerLevel: 60,
    dmgBase: 16,
    dmgPerLevel: 3.2,
    attackSpeed: 2.2,
    armorPerLevel: 26,
    moveSpeed: 7,
    aggroRadius: 18,
    loot: bossLoot(5000, 'bonelord_mantle', 0.35),
    scale: 2.7,
    color: 0xb9c4a8,
    summonAdds: { mobId: 'rift_bonewalker', count: 3, atHpPct: [0.7, 0.45, 0.2] },
    soulrot: { chance: 0.4, perTick: 12, interval: 2, duration: 10, name: 'Soulrot' },
    healAbsorb: { chance: 0.3, amount: 600, duration: 8, name: 'Necrotic Blight' },
    desperateHeal: { belowHpPct: 0.25, healPct: 0.2 },
    bigCast: {
      castId: 'rift_marrow_harvest',
      name: 'Marrow Harvest',
      castTime: 2.5,
      every: 15,
      radius: 13,
      min: 26,
      max: 40,
      school: 'shadow',
      yell: 'Your souls are forfeit.',
    },
    aoePulse: {
      min: 14,
      max: 22,
      radius: 11,
      every: 10,
      name: 'Bone Storm',
      school: 'shadow',
      fx: 'nova',
    },
    deathZoneCast: {
      castId: 'rift_necro_execution',
      name: 'Soul Grave',
      // 3.5 to match the roster line (Emberforge, Grask, Nyxaris). At 2.5 the
      // S-rank fuse (castTime * RIFT_S_ZONE_TEMPO) was 1.75s against 1.29s of
      // run-out from the anchor at the centre, leaving 0.46s to react: the
      // only unreactable zone in the game. See riftDeathZoneReactionBudget.
      castTime: 3.5,
      every: 22,
      radius: 9,
      school: 'shadow',
      yell: 'Your soul is forfeit.',
      detonateText: 'Soul Grave detonates!',
    },
    deathZoneStrike: {
      castId: 'rift_necro_strike',
      name: 'Death Sentence',
      // 4.0 for the same reason as Soul Grave above: at 3.0 the S-rank fuse was
      // 2.10s against 1.57s of run-out, and at S this one is the barrage (a
      // zone under EVERY living member), so nobody had a safe anchor to read.
      castTime: 4.0,
      every: 26,
      radius: 11,
      school: 'shadow',
      yell: 'DEATH CLAIMS ALL.',
      detonateText: 'Death Sentence falls!',
    },
    rankMechanics: ['summonAdds', 'bigCast', 'deathZoneCast', 'deathZoneStrike'],
    enrage: { belowHpPct: 0.3, dmgMult: 1.4, hasteMult: 1.25 },
    yells: { engage: 'Death is only the beginning.', summon: 'Rise!' },
  },
  // Bastion of Brutes: stomp + cleave + rampage
  rift_boss_brute: {
    id: 'rift_boss_brute',
    name: 'Warlord Grask',
    minLevel: 18,
    maxLevel: 23,
    family: 'ogre',
    elite: true,
    boss: true,
    ccImmune: true,
    slowImmune: true,
    hpBase: 820,
    hpPerLevel: 70,
    dmgBase: 18,
    dmgPerLevel: 3.6,
    attackSpeed: 2.8,
    armorPerLevel: 34,
    moveSpeed: 7,
    aggroRadius: 18,
    loot: bossLoot(5000, 'graskbreaker_girdle', 0.35),
    scale: 3.3,
    color: 0xa07d4f,
    stomp: { radius: 12, every: 11, duration: 1.5, min: 24, max: 36, name: 'Seismic Stomp' },
    cleave: { radius: 9, mult: 0.6, name: 'Sweeping Arc' },
    rampage: { ap: 40, maxStacks: 8, duration: 8, name: 'Rising Frenzy' },
    terrify: { radius: 12, every: 15, duration: 2, name: "Warlord's Bellow", school: 'physical' },
    bigCast: {
      castId: 'rift_earthbreaker',
      name: 'Earthbreaker',
      castTime: 2.8,
      every: 16,
      radius: 14,
      min: 32,
      max: 48,
      school: 'physical',
      yell: 'I BREAK YOU!',
    },
    desperateHeal: { belowHpPct: 0.3, healPct: 0.15 },
    deathZoneCast: {
      castId: 'rift_brute_execution',
      name: 'Earthshatter',
      castTime: 3.5,
      every: 22,
      radius: 9,
      school: 'physical',
      yell: 'THE EARTH SHATTERS.',
      detonateText: 'Earthshatter detonates!',
    },
    deathZoneStrike: {
      castId: 'rift_brute_strike',
      name: 'Final Judgment',
      castTime: 4.0,
      every: 26,
      radius: 11,
      school: 'physical',
      yell: 'YOU FALL HERE.',
      detonateText: 'Final Judgment lands!',
    },
    rankMechanics: ['stomp', 'terrify', 'deathZoneCast', 'deathZoneStrike'],
    enrage: { belowHpPct: 0.3, dmgMult: 1.5, hasteMult: 1.3 },
    yells: { engage: 'I will crush you!', enrage: 'RAAAGH!' },
  },
  // Voidscar: arcane hardcast + spell-vuln + stoneskin
  rift_boss_arcane: {
    id: 'rift_boss_arcane',
    name: 'Archon Nyxaris',
    minLevel: 18,
    maxLevel: 23,
    family: 'humanoid',
    elite: true,
    boss: true,
    ccImmune: true,
    slowImmune: true,
    hpBase: 680,
    hpPerLevel: 58,
    dmgBase: 16,
    dmgPerLevel: 3.2,
    attackSpeed: 2.0,
    armorPerLevel: 24,
    moveSpeed: 7,
    aggroRadius: 18,
    loot: bossLoot(5000, 'voidscar_handwraps', 0.35),
    scale: 2.6,
    color: 0xaf7ac5,
    bigCast: {
      castId: 'rift_arcane_burst',
      name: 'Arcane Detonation',
      castTime: 2.2,
      every: 12,
      radius: 13,
      min: 28,
      max: 40,
      school: 'arcane',
      yell: 'Witness true power.',
    },
    spellVuln: { chance: 0.35, amp: 0.2, duration: 8, name: 'Arcane Frailty' },
    stoneskin: { amount: 800, every: 15, duration: 6, name: 'Mana Shield' },
    aoeSlow: { radius: 30, mult: 0.5, duration: 4, every: 13, name: 'Temporal Drag' },
    aoePulse: {
      min: 16,
      max: 26,
      radius: 12,
      every: 9,
      name: 'Arcane Volley',
      school: 'arcane',
      fx: 'nova',
    },
    deathZoneCast: {
      castId: 'rift_arcane_execution',
      name: 'Void Rift',
      castTime: 3.5,
      every: 22,
      radius: 9,
      school: 'arcane',
      yell: 'Reality tears.',
      detonateText: 'Void Rift detonates!',
    },
    deathZoneStrike: {
      castId: 'rift_arcane_strike',
      name: 'Arcane Annihilation',
      castTime: 4.0,
      every: 26,
      radius: 11,
      school: 'arcane',
      yell: 'ANNIHILATED.',
      detonateText: 'Arcane Annihilation erupts!',
    },
    rankMechanics: ['bigCast', 'stoneskin', 'deathZoneCast', 'deathZoneStrike'],
    enrage: { belowHpPct: 0.3, dmgMult: 1.4, hasteMult: 1.25 },
    yells: { engage: 'You should not have come.', enrage: 'KNEEL!' },
  },
  // Stormspire: storm pulse + knockback
  rift_boss_storm: {
    id: 'rift_boss_storm',
    name: 'Tempest Vharok',
    minLevel: 18,
    maxLevel: 23,
    family: 'dragonkin',
    elite: true,
    boss: true,
    ccImmune: true,
    slowImmune: true,
    hpBase: 740,
    hpPerLevel: 64,
    dmgBase: 17,
    dmgPerLevel: 3.3,
    attackSpeed: 2.3,
    armorPerLevel: 32,
    moveSpeed: 7.5,
    aggroRadius: 18,
    loot: bossLoot(5000, 'stormscale_treads', 0.35),
    scale: 3.0,
    color: 0x5dade2,
    aoePulse: {
      min: 20,
      max: 30,
      radius: 13,
      every: 8,
      name: 'Chain Lightning',
      school: 'nature',
      fx: 'nova',
    },
    knockback: { chance: 0.3, distance: 9, name: 'Thunder Slam' },
    concuss: { chance: 0.2, duration: 1.5, name: 'Thunderclap' },
    bigCast: {
      castId: 'rift_thunderhead',
      name: 'Thunderhead',
      castTime: 2.4,
      every: 14,
      radius: 13,
      min: 28,
      max: 42,
      school: 'nature',
      yell: 'The sky answers!',
    },
    stomp: {
      radius: 11,
      every: 12,
      duration: 1.2,
      min: 18,
      max: 28,
      name: 'Galecrash',
      school: 'nature',
    },
    aoeSlow: { radius: 30, mult: 0.55, duration: 4, every: 12, name: 'Static Field' },
    deathZoneCast: {
      castId: 'rift_storm_execution',
      name: 'Lightning Rod',
      castTime: 4.5,
      every: 22,
      radius: 9,
      school: 'nature',
      yell: 'The sky answers your call.',
      detonateText: 'Lightning Rod strikes!',
    },
    deathZoneStrike: {
      castId: 'rift_storm_strike',
      name: "Stormcaller's Wrath",
      castTime: 5.0,
      every: 26,
      radius: 11,
      school: 'nature',
      yell: 'THE STORM DEVOURS.',
      detonateText: "Stormcaller's Wrath erupts!",
    },
    rankMechanics: ['aoePulse', 'bigCast', 'deathZoneCast', 'deathZoneStrike'],
    enrage: { belowHpPct: 0.3, dmgMult: 1.4, hasteMult: 1.25 },
    yells: { engage: 'The storm answers to me!', enrage: 'THE SKY FALLS!' },
  },
  // Sunken: drowning boss, lifeleech + terrify + summon
  rift_boss_tide: {
    id: 'rift_boss_tide',
    name: 'Abyssal Maw',
    minLevel: 18,
    maxLevel: 23,
    family: 'mudfin',
    elite: true,
    boss: true,
    ccImmune: true,
    slowImmune: true,
    hpBase: 700,
    hpPerLevel: 60,
    dmgBase: 16,
    dmgPerLevel: 3.2,
    attackSpeed: 2.4,
    armorPerLevel: 26,
    moveSpeed: 7,
    aggroRadius: 18,
    canSwim: true,
    loot: bossLoot(5000, 'abyssal_loop', 0.35),
    scale: 2.9,
    color: 0x16a085,
    terrify: { radius: 13, every: 14, duration: 2.5, name: 'Terrifying Screech' },
    lifeleech: { healFrac: 0.4, name: 'Devour' },
    summonAdds: { mobId: 'rift_spawnling', count: 2, atHpPct: [0.66, 0.33] },
    aoePulse: {
      min: 16,
      max: 26,
      radius: 12,
      every: 10,
      name: 'Riptide',
      school: 'frost',
      fx: 'nova',
    },
    aoeSlow: { radius: 30, mult: 0.5, duration: 4, every: 12, name: 'Undertow' },
    deathZoneCast: {
      castId: 'rift_tide_execution',
      name: 'Abyssal Maw',
      castTime: 5.0,
      every: 22,
      radius: 9,
      school: 'frost',
      yell: 'The deep takes you.',
      detonateText: 'Abyssal Maw closes!',
    },
    deathZoneStrike: {
      castId: 'rift_tide_strike',
      name: 'Crushing Depth',
      castTime: 5.0,
      every: 26,
      radius: 11,
      school: 'frost',
      yell: 'DRAWN INTO THE ABYSS.',
      detonateText: 'Crushing Depth crushes!',
    },
    rankMechanics: ['terrify', 'summonAdds', 'deathZoneCast', 'deathZoneStrike'],
    enrage: { belowHpPct: 0.3, dmgMult: 1.4, hasteMult: 1.25 },
    yells: { engage: 'The deep claims you.', summon: 'Rise from the depths!' },
  },
  // ---- The Infernal Citadel (authored set-piece, two bosses) ----
  // Miniboss on the pentagram rotunda. Deliberately NOT `boss: true`: the floor's
  // one true boss (and therefore the exit + cache + marks) is the pit lord. He is a
  // summoner/attrition fight that gates the temple gates via the Blood Orb.
  rift_boss_ritualist: {
    id: 'rift_boss_ritualist',
    name: "Magus Vel'Kor the Pactbound",
    minLevel: 18,
    maxLevel: 23,
    family: 'undead',
    elite: true,
    ccImmune: true,
    slowImmune: true,
    hpBase: 380,
    hpPerLevel: 40,
    dmgBase: 14,
    dmgPerLevel: 2.9,
    attackSpeed: 2.3,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 18,
    loot: [
      { copper: 2200, chance: 1 },
      { itemId: 'pactbound_vestments', chance: 0.45 },
      { itemId: RIFT_ESSENCE_ITEM_ID, chance: 1 },
      { itemId: RIFT_ESSENCE_ITEM_ID, chance: 1 },
    ],
    scale: 1.8,
    color: 0x8a1a1a,
    bigCast: {
      castId: 'rift_pact_flame',
      name: 'Pact Flame',
      castTime: 2.5,
      every: 16,
      radius: 10,
      min: 24,
      max: 36,
      school: 'shadow',
      yell: 'The pact is sealed in fire!',
    },
    summonAdds: { mobId: 'rift_spawnling', count: 2, atHpPct: [0.75, 0.5, 0.25] },
    soulrot: { chance: 0.35, perTick: 10, interval: 2, duration: 10, name: 'Pact Rot' },
    desperateHeal: { belowHpPct: 0.25, healPct: 0.18 },
    aoePulse: {
      min: 14,
      max: 22,
      radius: 10,
      every: 11,
      name: 'Blood Sigil',
      school: 'shadow',
      fx: 'nova',
    },
    rankMechanics: ['bigCast', 'summonAdds', 'aoePulse', 'desperateHeal'],
    yells: {
      engage: 'You trespass on bound ground.',
      summon: 'Answer me, things below!',
    },
  },
  // The citadel's giga-boss, loosed once the gates open: a towering pit lord.
  rift_boss_pitlord: {
    id: 'rift_boss_pitlord',
    name: 'Azgorath, Lord of the Pit',
    minLevel: 18,
    maxLevel: 23,
    family: 'demon',
    elite: true,
    boss: true,
    ccImmune: true,
    slowImmune: true,
    hpBase: 780,
    hpPerLevel: 66,
    dmgBase: 18,
    dmgPerLevel: 3.5,
    attackSpeed: 2.7,
    armorPerLevel: 32,
    moveSpeed: 7,
    aggroRadius: 20,
    loot: [
      { copper: 5000, chance: 1 },
      { itemId: 'pitlords_cleaver', chance: 0.4 },
      { itemId: 'pactbound_vestments', chance: 0.15 },
      { itemId: RIFT_ESSENCE_ITEM_ID, chance: 1 },
      { itemId: RIFT_ESSENCE_ITEM_ID, chance: 1 },
    ],
    scale: 3.2,
    color: 0xff3a1a,
    bigCast: {
      castId: 'rift_brimstone',
      name: 'Rain of Brimstone',
      castTime: 3,
      every: 15,
      radius: 12,
      min: 32,
      max: 46,
      school: 'fire',
      yell: 'THE PIT CLAIMS YOU.',
    },
    stomp: { radius: 11, every: 13, duration: 1.5, min: 22, max: 34, name: 'Hoof of Ruin' },
    knockback: { chance: 0.2, distance: 7, name: 'Wing Buffet' },
    summonAdds: { mobId: 'rift_spawnling', count: 3, atHpPct: [0.6, 0.3] },
    aoePulse: {
      min: 16,
      max: 26,
      radius: 12,
      every: 10,
      name: 'Pitfire Ring',
      school: 'fire',
      fx: 'nova',
    },
    rankMechanics: ['bigCast', 'stomp', 'summonAdds', 'aoePulse'],
    enrage: { belowHpPct: 0.3, dmgMult: 1.5, hasteMult: 1.3 },
    yells: { engage: 'Kneel, or burn.', enrage: 'THE CITADEL DEVOURS!' },
  },
};

export const RIFT_MOBS: Record<string, MobTemplate> = {
  ...ADDS,
  ...TRASH,
  ...BOSSES,
};

/** Every rift boss template id (the generator's boss pool). */
export const RIFT_BOSS_IDS: readonly string[] = Object.keys(BOSSES);
/** Every rift trash template id. */
export const RIFT_TRASH_IDS: readonly string[] = Object.keys(TRASH);
